### ISSUE TITLE
Issue when installing package when no non-repo are installed

### ISSUE THREAD

**Issue by benfrasersimpson** [polygamma/aurman#1]
I have a fresh installation of Archlinux, with no user packages installed.
It is exiting with the following error message
`2018-01-31 18:38:17,759 - Utils - all_installed_not_repo_packages - INFO - could not fetch the list of installed aur packages                                                                                                                                               `

It seems that `pacman -Qm` is exiting with an exit code of 1, so the if condition here is failing.

I have fixed this locally by changing `if pacman_return.returncode != 0` to `if pacman_return.returncode not in [0,1]:`

**Comment by polygamma** [comment]
Thanks! Has been fixed!
