### ISSUE TITLE
Make solver errors explicit

### ISSUE THREAD

**Issue by rmarquis** [polygamma/aurman#10]
One aspect of pacaur that is quite useful is that the solver pinpoints encountered errors, helping the user to know which package should be fixed by its maintainer. This is especially useful when upgrading a set of AUR packages, with one of them having an erroneous dependency deeply hidden in the tree.

Note that I'm using a very simple case here, but a more extreme case has been decribed [here](https://github.com/falconindy/auracle/issues/2).

Compare:

```
$ pacaur -S aura
:: Package aura not found in repositories, trying AUR...
:: resolving dependencies...
:: no results found for haskell-aur>=6.0 (dependency tree: aura haskell-aur)
```

```
$ aurman -S --pk aura

analyzing installed packages...
fetching upstream repo packages...
fetching needed aur packages...
calculating solutions...
2018-02-17 15:36:47,561 - classes - validate_and_choose_solution - ERROR - No valid solutions found
we could not find a solution.
if you think that there should be one, rerun aurman with the --deep_search flag
```
Note: Using the --deep_search flag produces the same output.

I'd suggest adding more explicit error messages with the following objectives:

* make it easy to locate the faulty PKGBUILD
* determine which is the target requiring that dependency, so it can be --ignored allowing the update of the others packages
* instead of stopping at the first detected error, find all errors at once then stops

**Comment by polygamma** [comment]
Added example screenshot for plasma-git-meta

![screenshot from 2018-02-17 20-57-24](https://user-images.githubusercontent.com/20651500/36345118-7bb95818-1425-11e8-9922-5a0791ff1f87.png)

**Comment by rmarquis** [comment]
Much better, thanks!

```
While searching for solutions the following errors occurred:
Not provided: haskell-aur>=6.0 but needed by aura-1.4.0-1
```

**Comment by polygamma** [comment]
Should be fine now.

![screenshot from 2018-02-23 16-13-20](https://user-images.githubusercontent.com/20651500/36601076-7a470a3c-18b4-11e8-8762-4a344ae74ba2.png)
