### ISSUE TITLE
Elevate Forwarded Commands

### ISSUE THREAD

**Issue by mtrimolet** [polygamma/aurman#100]
## Description
When using forwarded commands (i.e. anything besides `aurman -S`), pacman is not elevated as sudo. As one cannot `sudo aurman`, call to `pacman` becomes necessary.

## Expected Behavior
Ask password to elevate forwarding to pacman.

## Current Behavior
```bash
$ aurman -Fy
error: you cannot perform this operation unless you are root.
```

## Steps to Reproduce
`aurman -Fy`

**Comment by polygamma** [comment]
-F is going to be added to the pacman params called with sudo

**Comment by polygamma** [comment]
fixed, see: https://github.com/polygamma/aurman/commit/d2520b7c54d9ae490604a5cfafd060c7d80b744e
