### ISSUE TITLE
Option to rebuild package

### ISSUE THREAD

**Issue by groutr** [polygamma/aurman#101]
Aurman is a great AUR wrapper, but one feature that is critical for me is to rebuild a package.  Many packages in AUR are -git versions, and as such, the versions are almost never useful or accurate.  I have several git packages that I build the latest versions of, however aurman tries to be too clever and install the previously built package if the version number hasn't changed.

My feature request: Allow me to rebuild a package at will, or otherwise ignore any cached/previously built  packages.

**Comment by polygamma** [comment]
going to add a command line flag for rebuilding tomorrow.

**Comment by polygamma** [comment]
done. see: https://github.com/polygamma/aurman/commit/a8d25fdabf152317fd3c618babe784adfce4602c

does it work as expected?

**Comment by groutr** [comment]
@polygamma wow! That was quick.  I updated aurman, it a quick test seems to show it working correctly.  Thanks 👍 .

**Comment by polygamma** [comment]
You're welcome :)
