### ISSUE TITLE
`gcc6` and other SVN-sources fail to install; SVN is not in `base-devel`

### ISSUE THREAD

**Issue by kwshi** [polygamma/aurman#103]
## Description
Installation of `gcc6` fails when SVN is not installed on the Arch system, because makepkg depends on SVN to fetch SVN sources.  However, SVN is not in `base-devel` and so cannot quite be expected to already exist on the box.  Nor does aurman depend on SVN as it depends on git, so aurman's presence cannot guarantee that SVN is installed.

## Expected Behavior
`gcc6` should install.  It does not.  It would be nice if aurman gave some more useful output, i.e. the error message from makepkg.  It does not (see #71).  Regardless, the *correct* expected behavior may be some sort of a design choice under the Arch infrastructure (more details below).

## Current Behavior
While trying to install `gcc6`, this happens:
```
$ aurman -S gcc6
~~ initializing aurman...
~~ calculating solutions...

:: The following 7 package(s) are getting installed:
   extra/apr           /          ->  1.6.3-1
   extra/apr-util      /          ->  1.6.1-2
   extra/dejagnu       /          ->  1.6.1-1
   extra/doxygen       /          ->  1.8.14-1
   extra/expect        /          ->  5.45.4-1
   extra/serf          /          ->  1.3.9-2
   extra/subversion    /          ->  1.9.7-4

:: The following 1 package(s) are getting reinstalled:
   aur/gcc6            6.4.1-5    ->  6.4.1-5

?? Do you want to continue? Y/n: y
~~ looking for new pkgbuilds and fetch them...
Cloning into 'gcc6'...
remote: Counting objects: 47, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 47 (delta 10), reused 46 (delta 9)
Unpacking objects: 100% (47/47), done.
?? Do you want to see the changes of gcc6? N/y: n
2018-05-25 00:32:07,931 - wrappers - makepkg - ERROR - makepkg query makepkg --printsrcinfo failed
```
The installation fails, and the error message is not very helpful (issue #71 discusses the question of having error messages be propagated to help with debugging).  

## Possible Solution
The same installation was attempted in pacaur, and the following error message indicated the source of the error:
```
==> ERROR: Cannot find the subversion package needed to handle svn sources.
```
Subversion is not installed on my computer.  It is not expected as a dependency of `makepkg`; nor is it in the `base` or `base-devel` groups.  Consequently, `makepkg` does not have guaranteed access to SVN, causing it to fail when it attempts to fetch SVN sources.  A similar error, I imagine, would arise if one attempted to fetch git sources using makepkg without git installed.  This doesn't happen, however, because git is almost guaranteed to be installed when an Arch user installs their first AUR package (i.e. aurman, perhaps), while SVN (whose popularity is waning in comparison) is less likely to be installed before an Arch user first touches the AUR.

The problem lies in the fact that gcc6 requires sources to be fetched from an SVN repository, despite SVN not being installed.  Furthermore, while `gcc6` does list `svn` as one of its make-dependencies, evidently expecting that doing so would cause `svn` to be installed prior to sources being fetched for `gcc6`, aurman does not make the same assumption, instead fetching sources before installing any make-dependencies, causing makepkg to fail to fetch the package sources.

There's a slight question as to what *should* be considered the correct "interpretation" of the make-dependencies field, and consequently, what the correct fix should be.  That is, is it unfair for the `gcc6` PKGBUILD to assume that make-dependencies are installed before sources are fetched?  If so, here are some possible resolutions:

- `makepkg` should depend on `svn`.
- `svn` should be included in `base-devel`.
- **`aurman` should depend on `svn`.**  This solution, I suspect, is most preferred, because it appears to be the same way `aurman` currently ensures that it is able to fetch git sources.

On the other hand, if it is fair for `gcc6` to assume that make-dependencies are installed before sources are fetched, then accordingly aurman should install all make-dependencies before fetching any AUR sources.

More broadly, it is worth considering propagating error messages from wrapped commands such as makepkg to make debugging issues like this easier.  See---you guessed it---issue #71.

## Steps to Reproduce

1. Make sure `subversion` is not installed.  Just for kicks, reinstall `base-devel` to convince yourself that `subversion` is not in `base-devel`.
2. Try to install `gcc6` via `aurman`: `$ aurman -S gcc6`
3. (Optional) To check a useful error message, install `pacaur` and try installing `gcc6` from `pacaur`: `$ aurman -S pacaur && pacaur -y gcc6`.
4. Just to confirm that `subversion` is the thing causing the issue, install `subversion` and try again: `aurman -S subversion && aurman -S gcc6`.

**Comment by polygamma** [comment]
the problem was, that `aurman` used to fetch pgp keys from pkgbuild by running `makepkg --printsrcinfo`. this command was being run before any building of packages started, to ensure no interrupts during building due to missing pgp keys. with this commit https://github.com/polygamma/aurman/commit/a73dd663b2f1c3353792a913c31aff49938ebd42 i implemented manual parsing of pgpkeys from the pkgbuild. it's not "nice" but less problematic, since `makepkg` is not needed anymore. may you try if everything works as expected for you right now? the changes are in the master branch, hence using and updating `aurman-git` allows to test the changes. if everything's fine, i'll push a new `aurman` release.

**Comment by polygamma** [comment]
I am closing this issue for now, because `gcc6` should not be a problem anymore. If I am mistaken, feel free to reopen the issue
