### ISSUE TITLE
Sourcing PKGBUILD of devel packages even being ignored with --ignore or in pacman.conf

### ISSUE THREAD

**Issue by frealgagu** [polygamma/aurman#104]
## Description
If you try to update the system ignoring some devel packages, the packages are not upgraded as well, but it source the PKGBUILD to obtain the package version.

## Expected Behavior
Ignored packages should not be sourced in any moment.

## Current Behavior
Although the packages are not upgraded, they are sourced (downloading the required packages and executing pkgver)

## Possible Solution
Take out the ignored packages from the list of devel packages

## Steps to Reproduce (using java-design-patterns-git as example)
1. To have a devel package installed.
2. Try to upgrade the system including the devel packages -> aurman --sync --refresh --sysupgrade --devel --ignore java-design-patterns-git
3. Look that package is sourced and pkgver function is executed
    ==> Making package: java-design-patterns-git 1.19.0.r36.d7893c1f-1 (sáb may 26 16:53:19 -05 2018)
    ==> WARNING: Skipping dependency checks.
    ==> Retrieving sources...
      -> Cloning java-design-patterns git repo...
    Cloning into bare repository '/home/frealgagu/.cache/aurman/java-design-patterns-git/java-design-patterns'...
    remote: Counting objects: 49249, done.
    remote: Compressing objects: 100% (14/14), done.
    remote: Total 49249 (delta 4), reused 20 (delta 3), pack-reused 49224
    Receiving objects: 100% (49249/49249), 20.69 MiB | 838.00 KiB/s, done.
    Resolving deltas: 100% (18342/18342), done.
    ==> WARNING: Skipping all source file integrity checks.
    ==> Extracting sources...
      -> Creating working copy of java-design-patterns git repo...
    Cloning into 'java-design-patterns'...
    done.
    ==> Starting pkgver()...
    ==> Sources are ready.
    ==> Cleaning up...

**Comment by polygamma** [comment]
Thanks, going to change that
