### ISSUE TITLE
The new pgp fetcher in a73dd66 doesn't fetch all the gpg keys

### ISSUE THREAD

**Issue by jambonmcyeah** [polygamma/aurman#106]
## Description
I'm using commit a73dd66 and it doesn't fetch one of the pgp keys for mingw-w64-gcc. With version 2.9.28 it works 

## Expected Behavior
It should fetch all the pgp keys for mingw-w64-gcc

## Current Behavior
It misses one pgp keys for mingw-w64-gcc

## Possible Solution
Maybe revert to the old pgp fetcher which uses makepkg --printsrcinfo

## Steps to Reproduce
1. Run `aurman -S mingw-w64-gcc --noedit --noconfirm --pgp_fetch`
2. Fails to fetch pgp key

Here's the full log
```
[builduser@root1 aurman-git]$ aurman -S mingw-w64-gcc --noedit --noconfirm --pgp_fetch
~~ initializing aurman...
~~ calculating solutions...

:: The following 1 package(s) are getting installed:
   aur/mingw-w64-gcc       /        ->  8.1.0-1

:: The following 1 package(s) are getting removed:
   aur/mingw-w64-gcc-base  4.9.2-1  ->  /
:: Package mingw-w64-gcc-base will be removed due to a conflict with mingw-w64-gcc
~~ looking for new pkgbuilds and fetch them...
==> Making package: mingw-w64-gcc 8.1.0-1 (Sun May 27 11:04:29 EDT 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found gcc-8.1.0.tar.xz
  -> Found gcc-8.1.0.tar.xz.sig
  -> Found isl-0.18.tar.bz2
  -> Found bz85638.patch
==> Validating source files with sha256sums...
    gcc-8.1.0.tar.xz ... Passed
    gcc-8.1.0.tar.xz.sig ... Skipped
    isl-0.18.tar.bz2 ... Passed
    bz85638.patch ... Passed
==> Verifying source file signatures with gpg...
    gcc-8.1.0.tar.xz ... FAILED (unknown public key A328C3A2C3C45C06)

```

**Comment by polygamma** [comment]
not going to revert it, since `makepkg --printsrcinfo` yields problems. see https://github.com/polygamma/aurman/issues/103

i have to implement proper parsing, fuck bash

**Comment by polygamma** [comment]
@AladW do you know a proper solution for parsing pgpkeys from pkgbuilds?

**Comment by polygamma** [comment]
@jambonmcyeah may you try it again?

**Comment by AladW** [comment]
Parsing PKGBUILDs (outside `source PKGBUILD` in `bash`) will always lead to failure, no matter what you do.

----
Considering it's highly unlikely anyone uses this functionality to selectively verify PGP fingerprints, I'd say this flag only appeals to users not willing to read the makepkg wiki or man page. So if it were me I'd just reomve it and tell those users auto-key-retrieve is a thing.

**Comment by jambonmcyeah** [comment]
It works now, thanks. By the way, the dependency parser in aurman is superb. No other AUR helper I have used have ever been able to install mingw-w64-gcc correctly.

**Comment by AladW** [comment]
Hm, interestingly it seems that `mingw` no longer has any dependency cycles (even when naively combining `depends` and `makedepends` as `makepkg` and other helpers do).
```
user@v22016103960739491:~/aurutils (master u=)$ echo mingw-w64-gcc | aur depends | cut -f1,2 | tsort
mingw-w64-gcc
gcc-ada
mingw-w64-winpthreads
mingw-w64-crt
mingw-w64-gcc-base
mingw-w64-headers-bootstrap
mingw-w64-binutils
cloog
ppl
libmpc
mingw-w64-headers
zlib
texlive-bin
texlive-core
isl
osl
gmp
```
I wonder if there's some test-case for the old behavior? (that made `aurman` consider `depends` and `makedepends` separately)

**Comment by AladW** [comment]
Another thing: `validpgpkeys` should be part of `.SRCINFO` by default. If it is present in the PKGBUILD, but not .SRCINFO, it's a clear error on behalf of the maintainer and `aurman` shouldn't workaround that. Compare:

https://aur.archlinux.org/cgit/aur.git/tree/.SRCINFO?h=cower#n15

It was even reported on the AUR page of mingw-w64-gcc.

**Comment by polygamma** [comment]
regarding the dep cycle with mingw-w64-gcc, see: https://github.com/polygamma/aurman/issues/17#issuecomment-369364036

i guess nothing changed about mingw, the naive approach leads to a valid result if conflicts are not checked beforehand and conflicting packages just get deleted during installation. the difference with aurman is, that those conflicts are presented to the user beforehand, it "really" works and not just because of forcing installations.

regarding the pgp keys: this changes are not meant as workaround for .srcinfo mismatches, they are meant as `makepkg --printsrcinfo` replacement since that leads to issues as being described in https://github.com/polygamma/aurman/issues/103

i thought parsing them from the pkgbuild is more sensible than to parse them from the .srcinfo, since mismatches between those two lead to problems in the past for pacaur, hence i wanted to use the "real" source which is the pkgbuild, since the .srcinfo gets generated from the pkgbuild

**Comment by AladW** [comment]
Yeah, sure. It's just that a few months ago there were explicit cycles when using tsort, which somehow is no longer the case now.

If you want to parse PKGBUILDs, just keep in mind that people put all kinds of weird constructs (e.g. `aws-cli-git`) in them which opens up to a myriad of bugs. If you strictly to it for validpgpkeys you can cross fingers you don't encounter these issues, if you do it for other fields things will fail quickly.

**Comment by polygamma** [comment]
I only want to use it to fetch pgp keys, nothing else. aurman does not touch pkgbuilds for other reasons, well, besides showing them to the user. the "worst" case which can happen is, that pgp keys do not get detected, which is not nice, but does not break anything
