### ISSUE TITLE
remove pyalpm dependency

### ISSUE THREAD

**Issue by polygamma** [polygamma/aurman#107]
use `pacman-conf` which is available since `pacman 5.1` to remove the `pyalpm` dependency.
`aurman` is currently not usable with `pacman 5.1` due to `pyalpm` problems.

**Comment by polygamma** [comment]
ready for merge, see: https://github.com/polygamma/aurman/commit/482af45d31472190af996ae983377847afbaa993

**Comment by polygamma** [comment]
@AladW - it is sensible to use `pacman-conf` instead of `pyalpm` I guess?

**Comment by AladW** [comment]
`pacman-conf` is strictly superior for pacman.conf parsing than `pyalpm`; latter uses its own manual implementation while former uses `alpm` directly. If you don't use `pyalpm` for anything else I don't see why you'd keep using it.

**Comment by polygamma** [comment]
Great, with the mentioned commit I got rid of `pyalpm`. But there is one more problem...
Current `aurman` is unusable with `pacman 5.1`, if the `pyalpm` problems do not get fixed.
The "new" `aurman` version in the pacman_5.1 branch is not usable without 5.1 since it is using `pacman-conf` which got introduced with `pacman 5.1`. 

How should `aurman` deal with the transition to 5.1? I guess manually installing the `new` aurman version is unavoidable?

**Comment by AladW** [comment]
Just put a versioned dependency in the updated PKGBUILD. (`depends=(pacman>=5.1 ...)`) If users didn't upgrade to pacman 5.1 the update to the new aurman version will fail.

**Comment by polygamma** [comment]
Great idea, thanks!

**Comment by polygamma** [comment]
Has been merged, pkgbuilds have been updated, everything's fine
