### ISSUE TITLE
Trying to update a package that does not use versioning (firefox nightly) doesn't work

### ISSUE THREAD

**Issue by Akrai** [polygamma/aurman#108]
So i have firefox nightly from aur, which doesn't use the versioning system except for major version changes (60->61), so if you want to update it you just reinstall it compiling the package, with trizen/yaourt i just did it as usual, trizen -S firefox-nightly, but with aurman it detects that the package in the aur didn't changed the version, so first checked if i had a local package installed, if so it just prompts me to use that package. I tried the --rebuild option but it seems it is not implemented yet.
By the way, would be cool to have like a way to set in the config a list of packages that are "always outdated" so i can put there firefox and so everytime i do a system update firefox is always in the list or something like that

**Comment by polygamma** [comment]
i guess you want `--devel`

**Comment by Akrai** [comment]
Using -S --devel seems to fetch every development package i have instead of only the one im trying to update, and using --rebuild i get this:
akrai ~ $ aurman -S firefox-nightly-es-es --rebuild
!! The following parameters are not recognized yet: ['rebuild']
:: aurman --help or aurman -h

akrai ~ $

**Comment by polygamma** [comment]
what aurman version are you using?

**Comment by Akrai** [comment]
I have aurman installed from aur so the latest i think
aurman 2.9.26-1

okay --devel is a nice option to have but if you only want to update 1 package? there should be a way to force the download without fetching all the other ones, because if you have a lot of other development packages it would take a lot of time which could be a waste of time if i know there is no need to update the other ones (i have for example some theme packages from git, would take a lot of time and would be useless because i know it wont be updated, even more in a shitty laptop would take a lot of time to compress those packages)
so would be very cool to have a way to just ignore the cached packages when fetching packages
by the way, i love aurman, thanks for your job

**Comment by polygamma** [comment]
its not even close to the latest version. --rebuild is what you want, just update aurman and use that flag

**Comment by Akrai** [comment]
okay sorry i didnt thought it would be so updated, i will try
just a  question about --devel, im using it and it seems like it downloads the packages but doesnt compile it, does it check if there are changes with respect the already installed packages without compiling it?

**Comment by polygamma** [comment]
--devel is not compiling, just fetching new sources to calculate the current version of the package by running the part of the pkgbuild, which is being used for that.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/blob/master/src/aurman/classes.py#L1082

**Comment by Akrai** [comment]
its weird, when using devel, it started checking the git packages i have, and firefox was the last one, but it did this:

~~ calculating solutions...

:: The following 1 package(s) are getting updated:
   aur/firefox-nightly-es-es  61.0a1.20180507-1  ->  61.0a1.20180314-1
~~ looking for new pkgbuilds and fetch them...
[sudo] password for akrai: 
cargando los paquetes...
advertencia: firefox-nightly-es-es-61.0a1.20180507-1 está actualizado -- reinstalándolo
resolviendo dependencias...
buscando conflictos entre paquetes...

Paquetes (1) firefox-nightly-es-es-61.0a1.20180507-1

Tamaño total de la instalación:  151,44 MiB
Tamaño neto tras actualizar:      0,00 MiB

:: ¿Continuar con la instalación? [S/n] 
(1/1) comprobando las claves del depósito                                                                                      [############################################################################] 100%
(1/1) verificando la integridad de los paquetes                                                                                [############################################################################] 100%
(1/1) cargando los archivos de los paquetes                                                                                    [############################################################################] 100%
(1/1) comprobando conflictos entre archivos                                                                                    [############################################################################] 100%
(1/1) comprobando el espacio disponible en el disco                                                                            [############################################################################] 100%
:: Procesando los cambios de los paquetes...
(1/1) reinstalando firefox-nightly-es-es                                                                                       [############################################################################] 100%
:: Ejecutando los «hooks» de posinstalación...
(1/3) Updating icon theme caches...
(2/3) Arming ConditionNeedsUpdate...
(3/3) Updating the desktop file MIME type cache...

sorry for the spanish usage, but in summary it reuses the cached package
im sorry for bothering you, im gonna update aurman right now and try with --rebuild, just wanted to try devel to check updates of other packages
thanks for all!

**Comment by polygamma** [comment]
`firefox-nightly-es-es` is not being detected as development package, only `firefox-nightly` is since aurman is not able to tell that about `firefox-nightly-es-es`. you really have to manually use --rebuild for `firefox-nightly-es-es`

**Comment by Akrai** [comment]
ooooh i see, that makes sense, thanks for all

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/blob/master/src/aurman/aur_utilities.py#L58

**Comment by Akrai** [comment]
mmmm maybe some way to add in the config file names of packages to be manually considered as development packages?

also, the sudo loop utility is nice for when using --noconfirm, could be made that it asks for the sudo password just in the beggining of the command instead of when it is needed for the first time (when installing the first package of the command)?

**Comment by polygamma** [comment]
going to add a config option, good idea. for the sudo loop: i dont want to implement starting the loop before it is actually needed. but you may simply workaround that by executing a sudo command and aurman afterwards, you are not going to be asked for the password again

**Comment by Akrai** [comment]
yeah that is a nice workaround too
thanks for all!

**Comment by Akrai** [comment]
the very very last question, i cant find an option to change the cache folder of aur compiling, i prefer that all files of the aur package compiling process stay in tmp so it gets erased after a reboot, could we have a way to set it in the config file? thank you!

**Comment by polygamma** [comment]
rtfm :(

**Comment by Akrai** [comment]
i really did it but the only option says that will be forwarded to pacman :(

**Comment by polygamma** [comment]
https://github.com/polygamma/aurman/issues/105

**Comment by Akrai** [comment]
i think would be better to have a parameter in the config file to set it instead of using a variable every time or using an alias because would be more intuitive and maybe avoid problems if using other terminals or other shells i think

**Comment by polygamma** [comment]
i really want to stick to xdg base directories at that point. it's possible to change the cache dir of aurman, i don't want to introduce multiple options to achieve the same thing

**Comment by Akrai** [comment]
okay no problem, add a note or something in the readme about aurman using XDG_CACHE_HOME as cache dir so people know
thank you!
