### ISSUE TITLE
Impossible to upgrade pacman to version 5.1.0

### ISSUE THREAD

**Issue by frealgagu** [polygamma/aurman#109]
There is a restriction to install pacman to version 5.1.0 due to dependency in aurman that explicitly requires pacman<5.1

Why that restriction?

**Comment by iboyperson** [comment]
I cant say for sure but it is likely because some change or another in pacman 5.1 causes problems for aurman. If you look at this commit: https://github.com/polygamma/aurman/commit/5a2e98591d7a1244c417891ced55b29497d4504a you can see that prep work is being done for the aurman release supporting pacman 5.1.

**Comment by polygamma** [comment]
Because `pyalpm` was broken, seems to be fixed now, but `aurman` no longer requires that package.

**Comment by burningTyger** [comment]
I still can't update. Even if trying to go directly through pacman and `--force`. Same message with aurman and plain old `-Syu`.

```bash
# pacman -S pacman
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: aurman: installing pacman (5.1.0-1) breaks dependency 'pacman<5.1'
# pacman -S pacman --force
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: aurman: installing pacman (5.1.0-1) breaks dependency 'pacman<5.1'
```

Otherwise a great replacement for pacaur which I really liked. Thank you!

**Comment by dschrempf** [comment]
This is expected, because --force only skips checks for file conflicts. You can install the new pacman with `sudo pacman -S -d pacman` but then `aurman` will not work and has to be reinstalled directly from the aur. Maybe `aurman -S -d pacman aurman` works but I did not check this.

**Comment by burningTyger** [comment]
ok, I see. Should've checled the aur pages, too. Thank you.

**Comment by BurhanDanger** [comment]
Suicide note 😅
`sudo pacman -Rsn aurman && sudo pacman -Syu && cd /tmp/ && wget https://aur.archlinux.org/cgit/aur.git/snapshot/aurman.tar.gz && tar xf aurman.tar.gz && cd aurman && makepkg -sir`
