### ISSUE TITLE
Crashes trying to import PGP key

### ISSUE THREAD

**Issue by reverendhomer** [polygamma/aurman#111]
## Description

I can't install linux-ck because aurman crashes importing PGP key

```
λ aurman -S linux-ck
~~ initializing aurman...
~~ calculating solutions...

:: The following 2 package(s) are getting installed:
   extra/bc      /  ->  1.07.1-1
   aur/linux-ck  /  ->  4.16.12-2

?? Do you want to continue? Y/n:
~~ looking for new pkgbuilds and fetch them...
?? Do you want to see the changes of linux-ck? N/y:
?? PGP Key 647F28654894E3BD457199BE38DBBDC86092693E found in PKGBUILD of linux-ck and is not known yet. Do you want to import the key? Y/n:
gpg: WARNING: unsafe permissions on homedir '/home/ecko/.gnupg'
gpg: key 38DBBDC86092693E: 1 duplicate signature removed
gpg: key 38DBBDC86092693E: 136 signatures not checked due to missing keys
gpg: key 38DBBDC86092693E: public key "Greg Kroah-Hartman <gregkh@linuxfoundation.org>" imported
gpg: public key of ultimately trusted key 22ED9BD7FDE47335 not found
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   2  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 2u
gpg: Total number processed: 1
gpg:               imported: 1
2018-05-29 11:36:13,350 - classes - search_and_fetch_pgp_keys - ERROR - Import PGP key 647F28654894E3BD457199BE38DBBDC86092693E failed.
2018-05-29 11:36:13,351 - main - main - ERROR -
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 538, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 463, in process
    package.show_pkgbuild(noedit, show_changes, pgp_fetch, keyserver, always_edit, default_show_changes)
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 1033, in show_pkgbuild
    self.search_and_fetch_pgp_keys(fetch_always, keyserver)
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 917, in search_and_fetch_pgp_keys
    raise ConnectionProblem("Import PGP key {} failed.".format(pgp_key))
aurman.own_exceptions.ConnectionProblem: Import PGP key 647F28654894E3BD457199BE38DBBDC86092693E failed.
```

## Expected Behavior
No crash, linux-ck installed

## Current Behavior
Crash with traceback (or human-readable error message, at least)

## Steps to Reproduce

1. aurman -S linux-ck
2.
3.
4.

> **Notice**: If you do not fill out one of the fields, without mentioning **why** you left it out, the issue will be closed without any comment.

I didn't fill field "How to fix this problem" because I don't know why.

**Comment by reverendhomer** [comment]
Hmm, it's strange. Now it has imported key successfully. All I've done is
- install xclip to copy-paste error log from tmux to the chromium
- locked screen
- unlocked screen

Any ideas?

**Comment by polygamma** [comment]
fetching the key via the keyserver failed as indicated by the stacktrace, maybe set a specific server via the aurman config to reduce the possibility of that to happen, but all in all no aurman problem

**Comment by reverendhomer** [comment]
Err, and stack trace is cool? It's better than friendly error message?

**Comment by polygamma** [comment]
well, it's an unexpected error, a connection problem. i want to see the full stacktraces in those cases

**Comment by polygamma** [comment]
As I said: In those cases, I want to see the full stacktrace. I am not sure what aurman should 'handle' in those cases, if the connection is actually gone, retrying etc. yields nothing, hence aurman is never even going to try that. simply rerun aurman to achieve that. those stacktraces may yield nothing useful for the user, but i am not going to implement any --debug flags or whatever so that users have to rerun their commands with that flag to post stacktraces on github.

**Comment by polygamma** [comment]
maybe relevant for you: https://github.com/polygamma/aurman/issues/67#issuecomment-382538701
