### ISSUE TITLE
[Q/FR] Is it possible to display package size when acting as pacman wrapper?

### ISSUE THREAD

**Issue by aqua36** [polygamma/aurman#112]
When I try to install a package from the official repos by ``aurman -S PACKAGE`` it displays the packages that are going to be installed but not their size like pacman does

**Comment by polygamma** [comment]
that would only be possible for already built packages, but no, that's not yet implemented. good idea, but not important, so it will be implemented, but no ETA, maybe never

**Comment by polygamma** [comment]
I am closing this issue, because I am actually not planning to start working on it. Nevertheless: If one wants to have that feature, feel free to implement it in a sensible way and open a PR.
