### ISSUE TITLE
User-local makepkg.conf not supported

### ISSUE THREAD

**Issue by pilophae** [polygamma/aurman#116]
## Description
The configuration PKGDEST is not being read from ~/.makepkg.conf even though makepkg does.

## Expected Behavior
User-local makepkg config should trumph system config.

## Current Behavior
The following is logged when trying to install AUR package 'downgrade':
```2018-05-31 19:57:46,253 - classes - install - ERROR - package file of downgrade not available```

## Steps to Reproduce
_Provide an unambiguous set of steps to reproduce this bug._

1. ```echo "PKGDEST=/tmp" > ~/.makepkg.conf```
2. ```aurman -S downgrade```

**Comment by polygamma** [comment]
has been implemented, see https://github.com/polygamma/aurman/pull/118

**Comment by polygamma** [comment]
relevant: https://github.com/polygamma/aurman/issues/121
