### ISSUE TITLE
Integration with aria2

### ISSUE THREAD

**Issue by Crandel** [polygamma/aurman#119]
Hello. This project looks very good. I want to ask if it is possible to integrate [aria2](https://github.com/aria2/aria2) into this project? Right now I use [powerpill](https://wiki.archlinux.org/index.php/Powerpill) and [bauerbill](https://aur.archlinux.org/packages/bauerbill/) for AUR packages, but it has few issues and I want to try this project. I used to speed, provided by integration with aria2.

**Comment by polygamma** [comment]
at which point would one include aria2? there's basically one point where `aurman` really fetches data itself, that is when AURJson is used to fetch aur packages information. everything else is `makepkg` itself.

**Comment by Crandel** [comment]
Oh, I see. No problem
