### ISSUE TITLE
aurman does not properly read makepkg.conf

### ISSUE THREAD

**Issue by Morganamilo** [polygamma/aurman#121]
## Description
makepkg.conf is a bash file, aurman appears to parse it manually and expand shell variables. This causes error when there is anything non trivial in the file.

For example, my pkgdest is set to `PKGDEST="$home/pkg"`. Sourcing this with bash would cause the quotes to disappear. When aurman tries to parse the file it includes the quotes in the file path. 

## Expected Behavior
makepkg.conf is a bash file, therefore it should be sourced.

## Current Behavior
makepkg.conf parsed + shell variables expanded

## Possible Solution
Source the file or use `--packagelist` instead.

## Steps to Reproduce
1. set  `PKGDEST="$home/pkg"`` in makepkg.conf.
2. `aurman -S aurman`

**Comment by polygamma** [comment]
thanks for your report!

**Comment by Morganamilo** [comment]
Perfect. 18 less lines of code too.

**Comment by polygamma** [comment]
damnit, i really could have known about `--packagelist` - https://lists.archlinux.org/pipermail/pacman-dev/2018-February/022284.html

@rmarquis pointed that out in the third aurman issue on github, https://github.com/polygamma/aurman/issues/3

thanks again for your report, @Morganamilo
