### ISSUE TITLE
Feature request: work with deleted AUR packages programmatically

### ISSUE THREAD

**Issue by tuxfusion** [polygamma/aurman#122]
Thank you so much first of all for noting that I had gathered 27 dead packages on my system over the years (AUR). on aurman -Su first use I get that list. However I can't "work" with it. I have to store it manually and delete those packages. (awk, cut , etc ...)
Request: would it be possible to have an option to delete exactly those packages, meaning piping them directly to pacman -R <dead package list> ? I talked to people in #archlinux IRC all had great ideas, however no such option exists directly/easyly. It would be a great and rather simply thing to have.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/350d2af1301aa140e6f8001fe0ddfe61e281fe27 and https://github.com/polygamma/aurman/wiki/Using-aurman-as-dependency-solver/_compare/88c4036119a322d8dd0e91260f0dadcaaecdd88f

so you may install `aurman-git` to test the feature and execute `aurmansolver -Su --show_unknown` which yields all of those packages in a single line, space separated. You may pipe that output to `pacman -R`

**Comment by Morganamilo** [comment]
>which yields all of those packages in a single line, space separated.

As far as I know Pacman expects packages to be new line separated on stdin.

**Comment by polygamma** [comment]
e.g. `sudo pacman -Rsc $(aurmansolver -Su --show_unknown)` seems to work fine, is there anything wrong with it?

**Comment by tuxfusion** [comment]
You guys are legendary. It took you less time for a patch, then it took me to manually work with the text line. When I try it I get this: https://pastebin.com/rbgzTVUr  (i3, urxvt)  (empty brackets and errors)

**Comment by polygamma** [comment]
Is anything regarding `bash` *ever* intended?
Going to change separating to `\n` after @tuxfusion gave feedback.

**Comment by polygamma** [comment]
@tuxfusion seems like you have not installed the latest `aurman-git` version

**Comment by tuxfusion** [comment]
something is broken i did a aurman -S aurman-git and still it pulled an old version. Nevermind different topic. The old problem still remains, just for me? https://pastebin.com/p9NKsp7u

**Comment by polygamma** [comment]
You have to use `--devel` or `--rebuild` since `aurman-git` is a development package with the latest aur version being `2.9.36.r0.g35efd26-1`

**Comment by polygamma** [comment]
nevermind: your version is the current one, are the packages still installed or have you removed them?

**Comment by tuxfusion** [comment]
I already removed them manually. I did "aurman -S aurman-git --rebuild" and now I get an empty line as expected. But why do I need to parse --rebuild? This bugs the hell out of me. Also aurman says things it doesn't do. Big no no for the most important programm on my system ^^
https://pastebin.com/P99cYQQL It want's to delete stuff, I didn't ask for that but well, why not -> "Y" stuff gets not deleted. Scares me

**Comment by polygamma** [comment]
Well, I am not sure what you expect when the packages are already removed?
It's not like `aurmansolver` could list them in that case.

Also: You should read the readme. `--devel` is being explained, `--rebuild` and it is also being explained that `aurman` only predicts what is going to happen, `aurman` never removes things on its own. 
Seems like you forcefully installed packages without the needed dependencies, hence that output. `aurman` does exactly what it`s supposed to do, you just ruined your system.

**Comment by polygamma** [comment]
I am closing this issue, since the feature has been implemented, everything else you mentioned works as expected, you just did not read the readme, which is the users fault.

**Comment by tuxfusion** [comment]
I installed a git package. I expect it to pull the latest commit. It didn't. That was the root problem. Hence the error output with the "[..]"
I didn't complain about anything as a knew and already said that I removed the packages.
I find your tone absurd
