### ISSUE TITLE
[feature request] support running as root

### ISSUE THREAD

**Issue by johnnybubonic** [polygamma/aurman#123]
Hear me out.

So I'm well aware that makepkg no longer has --asroot.

However, aurman should be smart enough to be run as root/with sudo by dropping privileges to an unprivileged user present on every Arch Linux install: **nobody/nobody**.

These functions should help.

```python
def get_privileges() -> dict:
    privs = {'uid': os.geteuid(),
             'gid': os.getegid()}
    return(privs)
```
```python
def drop_privileges(privs) -> None:
    """
    drops privileges to the "nobody" user/group if running with sudo/as root
    """
    if privs['uid'] != 0:
        # Already non-root; no-op
        return
    uid = pwd.getpwnam('nobody').pw_uid
    gid = grp.getgrnam('nobody').gr_gid
    # Do NOT use os.setuid()/os.setgid()! You won't be able to regain root privs.
    # Use e(ffective) UID/GIDs instead.
    os.seteuid(uid)
    os.setegid(gid)
    # Note: you *may* need to set the umask via os.umask(new_umask)
    # Should be unnecessary, though.
```

```python
def restore_privileges(privs) -> None:
    os.seteuid(privs['uid'])
    os.setegid(privs['gid'])
```

you'd run `get_privileges()` to store the current (_effective_) user/group (so you can revert back to them afterwards for root-requiring operations), `drop_privileges()` would perform any necessary drop in privileges (the return on non-root is so it plays nicely with the sudo functionality, though you'd want to skip the sudo calls if privs have already been dropped to nobody user), and `restore_privileges()` would take the result from `get_privileges()` beforehand as a param.

ta-da.

i think this would be a very valuable feature because it would let users safely and securely run e.g. makepkg and other package parsing as a non-root user (in fact, a VERY unprivileged user - as it would also ensure no malicious PKGBUILD could ever even touch a user's own data such as SSH keys, etc.) while ALSO eliminating the need for a non-root user with an interactive shell (which saves a step with e.g. an already-active root shell, and reduces attack surface by not requiring the creation of a non-root user at all).

**Comment by johnnybubonic** [comment]
because this user would need an interactive shell associated with it. consider the following:

* a regular user is added on a system on which only services run (e.g. nginx, for instance, which adds a system user "nginx" itself when installed to drop privs to), in order to
* use aurman only, which has (by necessity)
* root privs via sudo

now you went from existing "system" users (e.g. useradd -r), which are users installed by pacman and have a very limited scope of access (i.e. no sudo access) to a user that has full control of system access (unless the sudo rules were incredibly explicit to the exact subprocess.run()'s that aurman calls, which even then would allow further malicious activity e.g. an intentional crafted .pkg.tar.xz - which most users also do not take the time to do). further, it requires a login shell (the nobody user is set to /sbin/nologin) unless one does something convoluted like `chsh -s /bin/bash someuser && su someuser - && chsh -s /sbin/nologin someuser`. it also requires a password (in order to use sudo, unless password-less escalation is configured for this user in sudo - in which case you're even worse off). because of this, you went from one user-interactable account (root) to two user-interactable accounts - root plus another account which requires sudo access. as a system's complexity grows, so does its security considerations/implications.

does this make sense?

**Comment by AladW** [comment]
@polygamma `makechrootpkg` runs makepkg twice, once to fetch the sources (as an unprivileged user) and a second time to build the package (with a specific user account `builduser`). I extended the former to take any unprivileged user as argument with [`makechrootpkg -U`](https://git.archlinux.org/devtools.git/commit/?id=cda9cf436b2897b063c1e40efb144404aad8b821). 

If you explicitely want to use `nobody`, there's much more effort involved like having an actual place where `nobody` can write files as well as handle remaining `makepkg` invocations like `makepkg --pkglist` (`makepkg` fails unconditionally when called as root, for good reason since it sources arbitrary PKGBUILDs).

As such while I don't prevent these contrived use cases, I don't support them either. The goal here seems to circumvent PKGBUILD inspection for arbitrary AUR packages which is always required, even with some mechanism in place that supposedly prevents changes on the host where the package is built.

**Comment by polygamma** [comment]
@AladW - thank you very much for the explanation!

@johnnybubonic - it makes sense, but it's really too complicated to implement in a "proper" way, if it's even possible.

**Comment by johnnybubonic** [comment]
@AladW "If you explicitely[sic] want to use nobody, there's much more effort involved like having an actual place where nobody can write files"

this is easy: /var/tmp.

from a fresh [bootstrap tarball](https://arch.mirror.square-r00t.net/iso/latest/archlinux-bootstrap-2018.06.01-x86_64.tar.gz) chroot:
```bash
[root@root ~]# sudo -u nobody touch /var/tmp/testfile
[root@root ~]# ls /var/tmp/
testfile
```

(or /tmp)

as for "the goal", you are incorrect. the goal is to avoid creating a regular user where it is unnecessary. hardly a "contrived use case".

@polygamma it's most assuredly possible. i've presented working examples for each step. as for complication, it's only necessary for steps in which non-root user is required (makepkg), and where operations don't require root (e.g. searching for packages).

**Comment by polygamma** [comment]
@johnnybubonic - sorry, I am nevertheless not going to implement it. It's something I would not use, hence there's no motivation for me to implement it. Besides that: This needs very thorough testing, which I do not want to do either, since I am not interested in using the feature. I also do not know enough about Linux privileges in general, hence I am not confident that I'd be able to implement this in a sensible manner, even if I wanted to.

**Comment by AladW** [comment]
Those "working examples" only represent the act itself of changing privileges... all the heavy lifting surrounding it is conveniently ignored. Anyway @polygamma already made his call so I have nothing to add here.

**Comment by leodutra** [comment]
Another great use is Arch on Windows Subsystem for Linux. 
We don't have a good reason for it not to run as root and this force a user creation, which is considerably complicated on this case because of the mounted Windows access.

**Comment by Morganamilo** [comment]
> which is considerably complicated on this case because of the mounted Windows access.

I've used arch wsl quite a bit. All I had to do to add a new user was useradd, I don't know what you're on about. Then I simply added `su myuser` to the bashrc of the root account and all is good.

**Comment by eli-schwartz** [comment]
Feel free to write a `makepkg` wrapper script which is able to run as root, but handles the dropping of privileges.

This would be something generic which every AUR helper could use...

**Comment by AladW** [comment]
Anyone who wants to do this should arguably first propose to move some makepkg functions (e.g. `remove_pkg`) to `libmakepkg` first.

**Comment by eli-schwartz** [comment]
Why?

I'm not suggesting a makepkg fork which is allowed to run as root, I'm suggesting something to handle cp, mv, and `sudo -u nobody makepkg --wrapper-opts`. How does libmakepkg help here?

**Comment by AladW** [comment]
Because how else are you going to replicate `makepkg -r` in your root wrapper without mindlessly copy-pasting or reimplementing functions from makepkg? Or do you suggest something akin to makechrootpkg where a `build` user is created with sudo rights to `pacman`?

**Comment by AladW** [comment]
...if latter, people should just use `makechrootpkg` which has `-U` already. Pretty sure that works with `nobody`...

**Comment by leodutra** [comment]
@Morganamilo Yep, had a issue not related to Arch user when accessing underlying system.
