### ISSUE TITLE
Ignored packages get updated when using wildcards in pacman.conf

### ISSUE THREAD

**Issue by KorvinSilver** [polygamma/aurman#127]
## Description
_When I have something in `pacman.conf` in `IgnorePkg` with a wildcard (in my case `xorg-server*`), it gets updated by aurman_

## Expected Behavior
_Don't update ignored packages specified by wildcards_

## Current Behavior
_Ignored packages specified by wildcards get updated_

## Possible Solution
_No idea_

## Steps to Reproduce
_Provide an unambiguous set of steps to reproduce this bug._

1. have pacman ignore packages with `IgnorePkg = some-packages-with-available-updates*` in `pacman.conf` under `[options]`
2. run `aurman -Syu`
3. see that after `~~ initializing aurman...` the specified packages won't be listed as being ignored and aurman will try and update them.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/228a82867fc4ba79b109f9673d5932d6dbce4dad may you check with the current `aurman-git` version if it works as expected?

**Comment by KorvinSilver** [comment]
Yes, it does work.

**Comment by polygamma** [comment]
Great :)
