### ISSUE TITLE
Targets starting with dash are being interpreted as option flags

### ISSUE THREAD

**Issue by gonX** [polygamma/aurman#128]
## Description
Attempting to search for a package by using a target starting with a dash (-) (ie. `aurman -Qs -git`) will result in an error.

## Expected Behavior
Targets starting with dash should not be considered options.

## Current Behavior
Searching for my packages containing '-ck', returns with this error:
```
$ aurman -Qs -ck
2018-06-02 20:05:44,083 - parse_args - parse_pacman_args - ERROR - Parameters for search are needed
```

## Possible Solution
Do like BASH does with its built-in commands - a double dash to indicate a separation of options and args, ie: `aurman -Qs -- -ck`

## Steps to Reproduce
```
aurman -Ss -git
```

**Comment by benoit-pierre** [comment]
Try `aurman -Ss -- -git`; see #114.

**Comment by polygamma** [comment]
Have you even tried to run `aurman -Ss -- -git`?

**Comment by gonX** [comment]
Yes, I tried exactly that. I had it in the post originally but decided it was not relevant since it seemed like it wasn't handling it in the first place:

```
$ aurman -Ss -- -git
2018-06-02 23:59:44,870 - parse_args - parse_pacman_args - ERROR -  is too short
```

**Comment by gonX** [comment]
Seems updated as per #114 
Really nice timing because I must have been in between the commits where this was fixed and unfixed.

Sorry for the noise

**Comment by polygamma** [comment]
No worries :) At least it works as expected now!
