### ISSUE TITLE
Handling of personal repos

### ISSUE THREAD

**Issue by stefanhusmann** [polygamma/aurman#13]
I have a personal repo named "my". aurman does not handle it well.

~/paketierung/meine_Pakete/otf-ibm-plex $ LANG=C aurman -Suy
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 xyne-x86_64 is up to date
 my is up to date
:: Starting full system upgrade...
 there is nothing to do

analyzing installed packages...
fetching upstream repo packages...
2018-02-25 14:29:33,872 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 281, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 140, in process
    upstream_system = System(System.get_repo_packages())
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 836, in get_repo_packages
    return Package.get_packages_from_expac("-S", (), PossibleTypes.REPO_PACKAGE)
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 264, in get_packages_from_expac
    to_expand['repo']):
ValueError: 'my' is not in list

**Comment by polygamma** [comment]
may you tell me how the "my" repo is listed in your pacman.conf ?

**Comment by rmarquis** [comment]
Since you're parsing pacman.conf with python directly, some more complex setup using `Include` could fail when parsing.

That's not trivial to handle, and in fact the next pacman will include `pacman-conf`, a new utility that you could rely on instead (not in master yet).

**Comment by polygamma** [comment]
I am just parsing the names, so Includes shouldn't matter I guess.
But I could think of the following: https://github.com/polygamma/aurman/commit/59b688e0ba4a03fe5160b615497d7b48690c7ce0

Maybe @stefanhusmann had a comment in the same line, like
[my] # my personal repo

But besides that I can't think of another reason for the parsing to fail.
Nevertheless, pacman-conf will be the solution when it's in master.

**Comment by stefanhusmann** [comment]
In pacman.conf I have

Include = /etc/pacman.d/my

and in pacman.d directory 

cat /etc/pacman.d/my
[options]
CacheDir = /var/cache/pacman/pkg
CacheDir = /home/haawda/repo
CleanMethod = KeepCurrent

[my]
SigLevel = Optional TrustAll
Server = file:///home/haawda/repo

**Comment by polygamma** [comment]
may you try it again with the new release?

**Comment by polygamma** [comment]
Have reproduced your setup and it seems to work now.
