### ISSUE TITLE
Failing docker tests

### ISSUE THREAD

**Issue by polygamma** [polygamma/aurman#134]
Not sure why this happens, may be a travis-ci problem?

Going to investigate if they are still failing tomorrow.

edit: stole label from aurutils

**Comment by polygamma** [comment]
Not failing anymore, call me a wizard.

**Comment by polygamma** [comment]
fml...

**Comment by AladW** [comment]
Did you try turning it off and on again?

----
FWIW, for all the recent commits I see "The Travis CI build succeeded"

**Comment by polygamma** [comment]
I actually did try that, I reran all tests again... Now they are green. Really looks like some travis-ci connection problem. The tests fail sometimes due to failing fetching of packages.

**Comment by AladW** [comment]
Wild guess, maybe it helps if you generate a new mirror list with `reflector` before each pass?

**Comment by polygamma** [comment]
good idea, implemented that. going to close this for now, let's hope that i do not have to reopen it ever again.
