### ISSUE TITLE
Connection timeout when checking for updates

### ISSUE THREAD

**Issue by vtrottier** [polygamma/aurman#135]
It looks like the 5 seconds timeout when requesting the AUR api is causing an exception at the moment. The api seems slow to respond and I keep getting timeout errors when running $ aurman -Syu. I'm not sure if it's the cause of the issue, but if so maybe it could be raised a little? Here's a screenshot of the error: 
![image](https://user-images.githubusercontent.com/17169508/40943527-7350be70-681f-11e8-9eb1-5a33df30ea12.png)

**Comment by polygamma** [comment]
Going to add a config option to be able to configure the timeout. Does that seem sensible to you?

**Comment by vtrottier** [comment]
Thanks for your quick response. Good idea for the option! Maybe raise the default one a little also (ex. 10 secs), or you think it would be too much?

**Comment by polygamma** [comment]
Actually you are the first one to ever mention such timeout, hence the default of 5 seconds should be fine. I am currently implementing the feature. Will let you know when it's merged, you may try it out with `aurman-git` then

**Comment by vtrottier** [comment]
Maybe the API is rarely slow, I'm not a long time user. I think it could have been less trouble to just put a default with a higher chance of success, since I don't see any don't see any downside to it.. but I'm fine with an option! :)

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/c7394d5fcfb4f76ad17a7ff40a75e83157fa51b5 let me know if it works as expected

**Comment by polygamma** [comment]
the downsides would be very, very long aurman startup times if the queries are actually going to take very long, e.g. 15 seconds. the user could think it's an aurman problem, but a low timeout makes very clear what the problem in that case is, hence the user may set a higher timeout, without thinking that aurman is faulty.

**Comment by vtrottier** [comment]
It works well, thanks! :)

**Comment by polygamma** [comment]
Great :)
