### ISSUE TITLE
Updating to urllib3-1.23-1 breaks aurman

### ISSUE THREAD

**Issue by craigdods** [polygamma/aurman#136]
## Description
Arch updated to python-urllib3-1.23-1 today which caused a traceback in aurman

## Expected Behavior
No traceback! Dependency is no longer met

## Current Behavior
$ aurman -Syyu
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.23 (/usr/lib/python3.6/site-packages), Requirement.parse('urllib3<1.23,>=1.21.1'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aurman", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'urllib3<1.23,>=1.21.1' distribution was not found and is required by requests

## Possible Solution
Fix dependency to allow for sub-versions of 1.23

## Version of aurman you are using
Latest - running version triggers traceback :|

## Steps to Reproduce
See above - simply running aurman creates the same trace (as would be expected with a dependency issue)

**Comment by polygamma** [comment]
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/python-requests&id=cd793259b3595b148a05f7c238aaf97327503454

**Comment by Taijian** [comment]
Still not quite done: 

```
$ Qii pcmciautils
/usr/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

**Comment by polygamma** [comment]
I cannot do anything about that, it has nothing to do with aurman

**Comment by craigdods** [comment]
Still get a warning with 2.9.39-1, but at least it's functional. Thanks!

`/usr/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
`

**Comment by polygamma** [comment]
I have not changed anything, since it still is no aurman problem.

**Comment by polygamma** [comment]
heads up: https://github.com/requests/requests/pull/4669

**Comment by frealgagu** [comment]
It starts to happen as soon as upgraded, tested in three PCs and each one behaves the same

**Comment by polygamma** [comment]
@frealgagu - not sure what you want to tell us.

**Comment by polygamma** [comment]
Reopening for visibility and also add a statement:

I am not going to change code of `aurman` because of this problem. With `python-requests 2.18.4-2` everything works, there is just an annoying warning after executing `aurman`. A `python-requests` dev wrote on their GitHub, that they are working on the next release, which is going to be fully compatible with the new `urllib3` version, hence the warning will disappear after the next `python-requests` update.

And to make it clear, once and for all: This is **not** an `aurman` problem, every python program using `python-requests 2.18.4` and `python-urllib3 1.23` is affected.

**Comment by polygamma** [comment]
no more warning: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/python-requests&id=ea3543c02bff79786c7ac2af9e1cfdd3cba24c97

**Comment by shreyansvm** [comment]
I rolled back to 1.22 and it worked for me. 

`sudo pip install urllib3==1.22`

**Comment by Morganamilo** [comment]
Please don't install stuff globally through pip.

**Comment by polygamma** [comment]
lolwut? How is this even still a thing?
