### ISSUE TITLE
Take input directy instead of waiting for enter

### ISSUE THREAD

**Issue by FrederikLauber** [polygamma/aurman#138]
Hello,

I would request that aurman takes a user input directly and not wait for enter.
This is in particular very annoying for the yes no questions. Pressing y or n should just accept the answer instead of waiting for enter to be pressed afterwards.

Thanks in advance

**Comment by polygamma** [comment]
Good idea, but i have to look how to implement this oroper

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/ada3f7f1299d1b48197cf295f3976d5347141361

**Comment by polygamma** [comment]
The feature should work, have tested in on multiple PCs, friends of mine also confirmed the feature to be working.

**Comment by FrederikLauber** [comment]
Works awesome, thanks!
