### ISSUE TITLE
Do not pass `--show_changes` to pacman

### ISSUE THREAD

**Issue by Ape** [polygamma/aurman#139]
I like to always automatically see the package diffs so I aliased aurman to `aurman --show_changes`. It works great with `-S`, but when I try to use other commands (which are passed to pacman) it fails with `pacman: unrecognized option '--show_changes'`.

I'd like to always use that `show_changes` option, but also use pacman commands.

**Comment by polygamma** [comment]
Sorry aurman does not filter anything in those cases, which is also not going to be added. It is just being passed to pacman

**Comment by AladW** [comment]
See the README...
