### ISSUE TITLE
Output without arguments

### ISSUE THREAD

**Issue by ChuckDaniels87** [polygamma/aurman#14]
Providing no arguments to `aurman` results in a wall of text that seems to be in markdown format. The output in that case should be something like `aurman --help` output. That would make usage a bit more readable.

Nice work, btw.

_Edit: I've noticed that `aurman --help` just passes that argument to `pacman`. `aurman` should have its own help._

**Comment by polygamma** [comment]
Currently that is really just a part of the Readme.MD. I am working on a rewrite of the output of aurman, that will include a proper help, too.

**Comment by polygamma** [comment]
![screenshot from 2018-02-27 10-59-11](https://user-images.githubusercontent.com/20651500/36722240-4fe9f0a0-1bad-11e8-8e69-283569e21567.png)

**Comment by ChuckDaniels87** [comment]
Much nicer but it still looks like a man page. In fact, you could extend that a little a use it as man page. In my opinion, the descriptions should be shorter and the format more compact in a `--help` command output.

Look at the help of other managers:
* Pacman:
![captura de pantalla de 2018-02-27 11-23-34](https://user-images.githubusercontent.com/8478202/36724092-6303f51e-1bb2-11e8-8018-9aa19af2c50a.png)
* Pacaur:
![captura de pantalla de 2018-02-27 11-23-57](https://user-images.githubusercontent.com/8478202/36724104-713f7784-1bb2-11e8-9724-9498d54f1eb6.png)
* Trizen:
![captura de pantalla de 2018-02-27 11-37-29](https://user-images.githubusercontent.com/8478202/36724171-a5a88bc8-1bb2-11e8-8041-a3d016ae7e2e.png)

**Comment by polygamma** [comment]
Have shortened the options descriptions.

**Comment by ChuckDaniels87** [comment]
I'd like to add several points about this that in my opinion would improve the style:
* Remove initial hyphens.
* Add description to all parameters. 
* Align option descriptions as other managers do, this would greatly improve readability.
* Colors and escape characters should be removed when output is not a terminal. For example, when you use a pipe or write to a file (`aurman --help | cat`).

**Comment by polygamma** [comment]
you are right, i am going to implement those things

**Comment by polygamma** [comment]
https://github.com/polygamma/aurman/commit/232115bdd90123b5adc077dfcec043e06a775dd4
