### ISSUE TITLE
Combine update plan for system upgrade and AUR package upgrade

### ISSUE THREAD

**Issue by felixwiemuth** [polygamma/aurman#142]
For now `aurman -Syu` first does a full system upgrade with only Arch repository packages and then continues with the upgrade process for AUR packages.

It would be nice if `aurman -Syu` would first show the "update plan" for all packages (Arch repository and AUR), like it does for AUR packages after having upgraded non-AUR packages.

In a second step, the user could be asked for all the confirmations/diffs for AUR packages (at least for those known at this point, see also #76). Only then building of non-AUR packages and installation of all packages should proceed.

This way one reduces the times the user has to come back to the process for confirmations, which is especially of interest if the non-AUR system upgrade takes longer.

**Comment by felixwiemuth** [comment]
Thank you for pointing out the option, I didn't find it as the option's description only indirectly explains why my desired behaviour would be achieved.

I'm not really sure why the procedure I described is not recommended (even with the additional explanation in [e06ed1b](https://github.com/polygamma/aurman/commit/e06ed1b5ab9c5dbab2826cfe7d0267c21fcba0ea) later removed) - is it because then pacman can't decide the order of installing packages?

If the use case I described is a reasonable one, it would be nice if it'd be documented in Readme. Otherwise, maybe documenting why not would soothe people looking for it ;).

**Comment by polygamma** [comment]
I am not sure what you mean by "in e06ed1b later removed" - how has that been removed?
And your usecase is being described in the README, now?

**Comment by felixwiemuth** [comment]
My mistake, I though you linked to an old commit because I had an old version of Readme open. Thanks for adding the information!

**Comment by polygamma** [comment]
regarding your other question, why `--do_everything` is not recommended in general: https://wiki.archlinux.org/index.php?title=Talk:AUR_helpers&oldid=515423#Separation_of_pacman_commands_-_Summary
