### ISSUE TITLE
Fix bad english in the README and aurman itself

### ISSUE THREAD

**Issue by polygamma** [polygamma/aurman#144]
Since I am not a native speaker, the english in the README and aurman itself is quite german, hence I'd appreciate pull requests fixing the english.

**Comment by AladW** [comment]
Probably the most german thing in the writing is the frequent use of commas. Compare:

https://en.oxforddictionaries.com/punctuation/comma

**Comment by polygamma** [comment]
I honestly love commas.

**Comment by AladW** [comment]
Somewhat offtopic, how do you feel about using man pages instead of / in addition to the README? Makes references from other man pages easier and it's convenient to use from the terminal. Only asking about the principle, you don't have to implement this yourself.

**Comment by polygamma** [comment]
man pages are fine, i've just been to lazy to create one

**Comment by AladW** [comment]
#145

**Comment by shaygover** [comment]
#210

**Comment by polygamma** [comment]
I do not think it is currently needed to have this as an open issue, one may nevertheless open a PR to change anything about the output, if one wants to.
