### ISSUE TITLE
Sudo loop prompts for the password regardless of settings in sudoers

### ISSUE THREAD

**Issue by DoMiNeLa10** [polygamma/aurman#147]
## Description
`aurman` uses `sudo -v` to escalate privileges, which always prompts for the password, ignoring `sudo` configuration. 

## Expected Behavior
`aurman` should respect configuration from `/etc/sudoers` and not prompt for the password if it's not asked to.

## Current Behavior
`aurman` prompts for the password regardless of contents of `sudoers`. Disabling sudo loop fixes the problem, but defaults aren't sane.

## Possible Solution
Don't use the `-v` switch with `sudo`.

## Version of aurman you are using
`:: 2.10-1`

## Steps to Reproduce
1. Run a command that will install or remove packages such as `aurman -Syu`.

## Read the README
I've read through the README.

**Comment by polygamma** [comment]
not going to parse `/etc/sudoers`, I also think the defaults are sane, not going to change anything, because you may simply disable the loop

**Comment by Mikotochan** [comment]
@polygamma 
You don't need to parse anything, just not use the -v..

**Comment by polygamma** [comment]
And use what instead?

**Comment by DoMiNeLa10** [comment]
Running something like `/bin/true` would suffice and allow for easy checking if it succeeded.

**Comment by eli-schwartz** [comment]
Agreed. The only time sudo -v will prompt for a password when sudo pacman does not, is if the sudoers configuration specifies NOPASSWD specifically for the command being run. In which case, sudo -v is regardless trying to create a password timestamp, even though the command you *wish* to run doesn't need said timestamp (and you may not have capabilities for any other command).

In this case I could get flat-out incorrect behavior if my sudoers specifies `ALL ALL=(ALL) NOPASSWD: /bin/true`
