### ISSUE TITLE
Feature Request: Aurman should show dependency problems and package list to be updated

### ISSUE THREAD

**Issue by sukovec** [polygamma/aurman#150]
Hello!

I've been using yaourt for long time but as yaourt is not developed anymore and because it has problems with split packages, I moved to aurman. Hovewer after some time, aurman is now useless for me. Why?

When I now try aurman -Syu, it just offers me high number of solutions. Hovewer, I would like to know what are these solutions. I can see, that I can install and remove combinations of packages, but without a clue why. Why should I remove packages X, Y and Z and install packages wtf, idontneedthis, uselesspackage? What is the reason for this? Is there some evil package that really needs wtf (which collides with X)? 

I believe you understand me - when I see some solutions, I need to know of what problem. I tried --debug, but that doesn't show even a word about AUR. 

Thank you for understanding and have a nice day,
S.

**Comment by polygamma** [comment]
Useless report, closing.

**Comment by sukovec** [comment]
So showing what problem is being solved is "useless" or I'm doing/understanding something wrong?

**Comment by polygamma** [comment]
You are doing something wrong. You do not provide ANY kind of useful information for me as developer.

**Comment by sukovec** [comment]
When I run `aurman -Syu`, it just informs me, that

    !! we could not find a solution
    !! if you think that there should be one, rerun aurman with the --deep_search flag

When I write `aurman -Syu --deep_search`, the aurman will offer me number of solutions of unknown problem. These solutions offer me packages I dont want to be installed and packages to be removed (some of them are wanted by me).

If you think it's bug and you want some info from me, just say - I can send you all the outputs, package list and whatever you want - I just thought it's not a bug but (incomplete?) feature. Sorry for that. 

Btw, when I use `--debug`, number of solutions is 5 times longer.

**Comment by polygamma** [comment]
Please provide every information needed, so that I am able to understand what is going on. Including the version of `aurman` you are using, the content of your `aurman config`, every output, etc.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/2412b13afdad32230acc376a5370f8972c034643

please use `aurman-git`, you may install it via `aurman -S aurman-git --rebuild` and run `aurman -Syu` again. You may now enter `0` when being shown different solutions, which allows to inspect every solution in detail without the need to select every solution once. Even though you have not responded again, that feature should be enough to make clear why those solutions are a thing.

**Comment by sukovec** [comment]
Hi, sorry for not responding, I'm still compiling an answer for you (deep search took several minutes to offer me a solutions). I will do what you have wanted and post outputs.

**Comment by polygamma** [comment]
The new feature is part of the new `aurman` release, if that's not enought, reopen the issue with enough information.
