### ISSUE TITLE
Feature Request: build signing

### ISSUE THREAD

**Issue by madblobfish** [polygamma/aurman#152]
Could you create a release PGP key and sign your builds?

**Comment by polygamma** [comment]
Where exactly should I sign builds? Do you mean the commits on GitHub?

**Comment by madblobfish** [comment]
You could sign the builds found on the [release](https://github.com/polygamma/aurman/releases) page and upload the signature files there.
In the PKGBUILD this could be used to have verification.

**Comment by polygamma** [comment]
The PKGBUILDs do not use tarballs

**Comment by madblobfish** [comment]
Thanks for your hard work & time

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/954c187bd5fb3a547dfc68e920e2d188a8b6c2e7

and thanks for your kind words.

**Comment by AladW** [comment]
Note that signed tags have some issues, see https://www.usenix.org/conference/usenixsecurity16/technical-sessions/presentation/torres-arias

**Comment by polygamma** [comment]
@madblobfish - see: https://github.com/polygamma/aurman/commit/64047c5d07ba0cfe901986ea77c989f2a9f46922

**Comment by Morganamilo** [comment]
@polygamma Could you link me to where you got `?singed` from by any chance. Can't seem to find any documentation on it.

**Comment by Morganamilo** [comment]
And I just realised I need I needed to escape the question mark to search for it `/\?`. Found it now, thanks anyway.
