### ISSUE TITLE
Set the default response to "show changes" to no

### ISSUE THREAD

**Issue by Mishio595** [polygamma/aurman#157]
The docs clearly show how to set the default response of this to yes, but nowhere am I able to find an option to set it to no. Other wrappers I have used gave me an option to do this, but I don't see it in this one.

**Comment by polygamma** [comment]
Uhm, what do you think, the default is going to be, if you do not set it to "yes"?

**Comment by Mishio595** [comment]
Setting nothing causes it to prompt for each package, the only option you have in config is documened as only allowing Yes

**Set the default for the question: `Do you want to see the changes of x?` to yes**

create a key called `default_show_changes` in the section `miscellaneous` to do that.

Examples:
```
[miscellaneous]
default_show_changes
```

This does not provide a way to default to no. There's no need to be a snide and not answer the question.

**Comment by Mishio595** [comment]
It is very unclear in the README. "Do you want to see the changes" and `--noedit` do not logically correlate. Just because something is clear to you, as the developer, does not mean it is clear to your users.

**Comment by polygamma** [comment]
They do, since the description for `--noedit` states: 

> Will not show changes of PKGBUILDs, .install and other relevant files. just assumes you are okay with the changes.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/0a39add038df329b322fdc01b3c046c80df8dbf3
