### ISSUE TITLE
aurman predicts falsely that a package would be removed

### ISSUE THREAD

**Issue by SpineEyE** [polygamma/aurman#158]
## Description

When I install any aur package like this: `aurman -Syu aurman-git`, aurman predicts that one of my packages would get removed, because the dependency is not fulfilled (anymore). However, it doesn't actually get removed.

I'm not sure whether this is intended behavior but to me it seems that it isn't.

Also, this doesn't happen when I just do `aurman -Syu`

## Expected Behavior

Should not predict that the package gets removed.

## Current Behavior

aurman predicts that a package gets removed.

## Possible Solution

better prediction, i.e. a completely unrelated package won't get touched by pacman. Maybe your algorithm can save time when it doesn't need to check every package?

## Version of aurman you are using

2.11.r0.ga7b61c1-1

## Steps to Reproduce
I guess...

1. sudo aurman -Syu virtualbox-ck-host-modules 5.2.10-1
2. sudo aurman -Syu linux-ck
3. aurman -Syu aurman-git

## Read the README
At least I did Ctrl+F predict.

complete log:
```
aurman -Syu aurman-git
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do

~~ initializing aurman...
:: Ignoring installed package virtualbox-ck-host-modules
~~ calculating solutions...

:: The following 1 package(s) are getting reinstalled:
   aur/aurman-git                  2.11.r0.ga7b61c1-1  ->  2.11.r0.ga7b61c1-1

:: The following 1 package(s) are predicted to get removed:
   aur/virtualbox-ck-host-modules  5.2.10-1            ->  /
:: Dependency linux-ck<4.16 of package virtualbox-ck-host-modules is not fulfilled

?? Do you want to continue? Y/n: 
~~ looking for new pkgbuilds and fetching them...
remote: Counting objects: 48, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 48 (delta 24), reused 40 (delta 16)
Unpacking objects: 100% (48/48), done.
From https://aur.archlinux.org/aurman-git
   8330fb5..6921f14  master     -> origin/master
?? Do you want to see the changes of aurman-git? N/y: 
loading packages...
warning: aurman-git-2.11.r0.ga7b61c1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)  Old Version         New Version         Net Change

aurman-git   2.11.r0.ga7b61c1-1  2.11.r0.ga7b61c1-1    0,00 MiB

Total Installed Size:  0,45 MiB
Net Upgrade Size:      0,00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                           [------------------------------] 100%
(1/1) checking package integrity                         [------------------------------] 100%
(1/1) loading package files                              [------------------------------] 100%
(1/1) checking for file conflicts                        [------------------------------] 100%
(1/1) checking available disk space                      [------------------------------] 100%
:: Processing package changes...
(1/1) reinstalling aurman-git                            [------------------------------] 100%
:: Running post-transaction hooks...
(1/2) Removing old cached packages...
==> no candidate packages found for pruning
==> no candidate packages found for pruning
(2/2) Arming ConditionNeedsUpdate...
```

**Comment by polygamma** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by SpineEyE** [comment]
lol you can read this whole thing in 20 seconds?

**Comment by polygamma** [comment]
I can assure you, that this exact report is not valid, since you did not provide proof, that the mentioned dependency `linux-ck<4.16` of `virtualbox-ck-host-modules` is fulfilled. The README states, that this behavior is intended, if the dependency is unfulfilled, and since your report does not mention what I just said, it is invalid. And yes, I read that in less than 20 seconds.

**Comment by polygamma** [comment]
I dug a bit: You ran `aurman -Syu`, since `aurman` did not want to update `linux-ck`, you have the latest version installed, which is `4.16.15`. Hence `linux-ck<4.16` is not fulfilled and your report invalid.

**Comment by SpineEyE** [comment]
Well, the readme doesn't say that it's intended for completely unrelated packages and that's was confusing. So I thought you overlooked that. But apparently not, so sorry for the formal bug report...

**Comment by polygamma** [comment]
I quote:

> This behavior of aurman may even occur, if there are no .so dependencies involved. In that case check, if the dependencies are really fulfilled on your system. If they are not, because you forced installations of packages with pacman -d, that behavior of aurman is explicitly wanted. It warns you about broken package dependencies of your system. To remove that output of aurman you have to fulfill the dependencies.

**Comment by SpineEyE** [comment]
Yeah, I didn't force install it, so if pacman doesn't want to remove it I don't see why a user would want to remove it. But ok, it must be useful sometimes, so never mind, I don't want to open another discussion about an AUR helper that I don't contribute code to.

**Comment by polygamma** [comment]
You must have used `-d` or `-dd` at some point, otherwise those packages would not be installed on your PC as they are. Otherwise you found a `pacman` bug, which you may want to report.

**Comment by polygamma** [comment]
Have you used `trizen` before?

**Comment by SpineEyE** [comment]
Didn't do that. Maybe it has something to do with the fact that it's in my pacman.conf ignore line.

Yeah I have once used trizen, but I don't remember if I installed the package with it.

**Comment by SpineEyE** [comment]
Well, thanks. But I will leave it installed anyway since otherwise I probably can't use VirtualBox and it works now, so maybe this is rather a case of a non-appropriate PKGBUILD.
