### ISSUE TITLE
Shouldn't aurman first download a PKGBUILD and then ask if we'd like to view / edit BEFORE installing dependencies?

### ISSUE THREAD

**Issue by fireio** [polygamma/aurman#163]
## Description
 What if we want to edit something in a PKGBUILD which results in editing deps?

## Expected Behavior
aurman should ask whether we'd like to review PKGBUILD and give option N/y before installing dependencies.
## Current Behavior
aurman asks if we would like to install dependencies

## Version of aurman you are using
2.11-1

## Steps to Reproduce
1. $ aurman -S matlab
2. aurman asks to install deps without asking to edit matlab PKGBUILD

## Read the README
_Confirm, that you have read the entire README_
I confirm that I've read the entire README

> **Notice**: If you do not fill out one of the fields, without mentioning **why** you left it out, the issue will be closed without any comment.

**Comment by polygamma** [comment]
Obviously you have already seen the pkgbuild or you use noedit. otherwise provide steps to reproduce, which really help reproduce the problem. but i bet it is nonexistent

**Comment by fireio** [comment]
Here's a video screen of this problem: https://streamable.com/6s92s
Could you specify where is your aurman's behaviour different from mine in the stream?

**Comment by polygamma** [comment]
As I said, that is nothing which I am going to ever implement. If you change dependencies in PKGBUILDs, you have to install those deps manually. aurman does not parse dependencies from PKGBUILDs and will never do

**Comment by frealgagu** [comment]
Is there any reason to not overwrite the .SRCINFO (makepkg --printsrcinfo) and use it as new dependency solver instead of use the original?

I want to know if is because it's something we shouldn't do (bad practice) or it's something you are not interested to implement.

**Comment by eli-schwartz** [comment]
> because aurman only uses AUR RPC for fetching dependencies and is never going to parse PKGBUILDs or .SRCINFOs for that.

Parsing the .SRCINFO is slow, therefore the latter...

**Comment by Morganamilo** [comment]
Actually parsing a .SRCINFO is quite fast, generating them, that's the slow part. The whole point is moot though.

>Is there any reason to not overwrite the .SRCINFO (makepkg --printsrcinfo) and use it as new dependency solver instead of use the original?

You seem to think aurman uses the .SRCINFO for dependency resolving. It does not, in any way. It was already pointed out that it uses the RPC. So simply overwriting the file is not enough. You need to rewrite the dependency solver to be able to use .SRCINFOS and the RPC interchangeably.

**Comment by eli-schwartz** [comment]
> Actually parsing a .SRCINFO is quite fast, generating them, that's the slow part. The whole point is moot though.

Compared to the RPC, even that's slow. ;) And of course rewriting the metadata resolver would need to either carry around two modes, or slow down -Si actions with a large number of GET requests which is also pretty slow...

**Comment by polygamma** [comment]
It's about me not being interested in implementing it. This is an absolute rare usecase, there is nothing wrong with installing 1 or 2 packages manually for me. Actually I've never changed the dependencies in a PKGBUILD.

**Comment by frealgagu** [comment]
Of course, installing some packages manually is not an inconvenient, the issue here are the restrictions which forbid install a package if the version requirements are not met. Although you are right, it is not a common case and change the behavior just for this is not a good idea.
