### ISSUE TITLE
Support building in a clean chroot

### ISSUE THREAD

**Issue by jambonmcyeah** [polygamma/aurman#165]
I would like this feature because some packages have make makedepends conflicting with the packages I currently have installed. For example [code](https://aur.archlinux.org/packages/code/) requires [nodejs-lts-carbon](https://www.archlinux.org/packages/community/x86_64/nodejs-lts-carbon/) to build. However I can't install nodejs-lts-carbon because I have the regular version installed.

You could try integrating `mkarchroot` and `makechrootpkg` to achieve this.
https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot

**Comment by polygamma** [comment]
Sorry, I have no intention to implement that, since I am not interested in using it. You may want to take a look at aurutils, which provides this feature
