### ISSUE TITLE
Support PKGDEST

### ISSUE THREAD

**Issue by zaplo00** [polygamma/aurman#166]
THIS TEMPLATE IS FOR BUG REPORTS,
YOU DO NOT HAVE TO USE IT FOR FEATURE REQUESTS

## Description
AUR packages succesfully build but aurman fails to install them because of PKGDEST environment variable (destination dir for .pkg.tar.xz packages, found in makepkg.conf). pacman -U does work. 

## Expected Behavior
aurman should install the built AUR application and look for it in $PKGDEST if it's set.

## Current Behavior
file not found error.

## Possible Solution
Add support for PKGDEST

## Version of aurman you are using
:: 2.9.32-1

## Steps to Reproduce
_Provide an unambiguous set of steps to reproduce this bug._

1. Install or upgrade any package from the AUR

## Read the README
Confirm

**Comment by polygamma** [comment]
great steps to reproduce

**Comment by polygamma** [comment]
also: maybe do not use an aurman version ca. 1 year old...
