### ISSUE TITLE
wrappers - makepkg - ERROR - makepkg query makepkg --printsrcinfo failed

### ISSUE THREAD

**Issue by Cysioland** [polygamma/aurman#168]
## Description
Basically it outputs `wrappers - makepkg - ERROR - makepkg query makepkg --printsrcinfo failed` when installing packages such as `brp-pacu` from AUR, not disclosing any other relevant info

## Expected Behavior
It should print out more detail about what is wrong

## Current Behavior
It prints out solely that line

## Possible Solution
Make it print out more detail about what is wrong, such as the output of build commands

## Version of aurman you are using
2.9.28-1

## Steps to Reproduce
1. aurman -S brp-pacu
2. Confirm all the PKGBUILDs
3. Error happens

## Read the README
I confirm that I've read the entire README and it didn't solve my issue

**Comment by Cysioland** [comment]
But why is it invalid, any justification? Did I forget something?

**Comment by polygamma** [comment]
You have an aurman version from the last century installed

**Comment by polygamma** [comment]
Conclusion: Do not use Antergos

**Comment by Cysioland** [comment]
Or verify, whether there's a newer version in AUR

**Comment by polygamma** [comment]
Or write

```
[aur_packages]
aurman
```

into the `aurman config` because `aurman` offers exactly that feature

**Comment by polygamma** [comment]
Nevertheless, see: https://github.com/polygamma/aurman/commit/bd1a0366065a14c3280f258b9fc0ed179cf6caa3

I am not interested in supporting anything besides Arch Linux, hence new Issues need to provide the operating system and will be closed, if the user is not running Arch.

**Comment by Cysioland** [comment]
There's the thing:

```
cysioland ~ λ cat /etc/*-release                                        10:21:44
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

Antergos, contrary to Manjaro, is still bona fide Arch. The only relevant difference is the additional `antergos` repository, which basically boils down to "make sure you don't run the ancient version".

**Comment by polygamma** [comment]
Not sure how that has anything to do with "Arch elitism". It's not Arch and still `cat /etc/*-release` lists Arch only. Also: I am definitely not going to add such a default, because it is unneeded, if one uses Arch.

**Comment by Cysioland** [comment]
It still uses Arch's core, extra, testing, community, etc. repositories. The difference is basically them packaging some popular AUR packages into their own repository so that users don't have to spend their resources build it. AUR still works.

**Comment by polygamma** [comment]
Yeah, and that obviously does not yield any problems. And it may use Arch repos, it's still not Arch, and I think `cat /etc/*-release` should not list Arch only.

**Comment by Cysioland** [comment]
I still gonna continue using your wrapper despite your lazy attitude towards supporting another "distro" with just two lines of code. Thank you for providing me (but not others) with a workaround.

**Comment by polygamma** [comment]
Lazy attitude. ROFL.

**Comment by polygamma** [comment]
And yeah, `aurman` definitely should fix the flaws of linux distributions instead of the users using those distributions by reading the README of the tools they use and using their brain.

**Comment by polygamma** [comment]
Relevant to read: https://github.com/polygamma/aurman/issues/140

**Comment by Cysioland** [comment]
Fair points you've brought up there. Funnily, I also started using `aurman` because of `pacaur` being unsupported and quitting on me. I do feel, however, that situation with AUR wrappers is kind of bad, with too many of them competing with each other while having minute differences from each other, but I guess I can make my own one if I find it bad, further contributing to the issue.

Anyway, thank you for releasing your personal project so that I can use it to install AUR packages, instead of me having to cook up my own personal project and release it (or not).

**Comment by polygamma** [comment]
I do not think, that there are AUR wrappers with only minute differences from each other. If you look at the [table](https://wiki.archlinux.org/index.php/AUR_helpers#Active), most of them use different programming languages, wrap `pacman` in different ways, some use the AUR RPC, others parse the .SRCINFOs for the dependencies, support for "full batch interaction" is different, etc. Some use completely different approaches, see e.g. [aurutils](https://github.com/AladW/aurutils)

It may be a good idea, to list in the table, whether AUR Helpers use AUR RPC or parse .SRCINFOs, what do you think, @Morganamilo, @AladW?

**Comment by polygamma** [comment]
interesting to read: https://github.com/Antergos/antergos-packages/pull/345

using Antergos really is a great idea

**Comment by Cysioland** [comment]
It indeed is, especially, when its maintainers adhere to a suggestion of a package developer and drop the package causing problems.

**Comment by polygamma** [comment]
The package was not causing problems. The Antergos developers caused the problems by using outdated and wrong PKGBUILDs to build the package. But yeah man, Antergos is great, have fun using it.

**Comment by Foxboron** [comment]
Antergos should provide a proper  `etc/*-release` file. It just so happens that the file gets updated by an Arch package every now and then and nukes the Antergos information.

**Comment by polygamma** [comment]
Well, at least they tried... Thanks for the information, @Foxboron

**Comment by eli-schwartz** [comment]
> Antergos, contrary to Manjaro, is still bona fide Arch. The only relevant difference is the additional antergos repository, which basically boils down to "make sure you don't run the ancient version".

The Antergos developers disagree with you.

Speaking in my official capacity as an Arch Linux staff member (Bug Wrangler, Trusted User), I disagree with you.

The official position of Arch Linux is and has always definitively been that Antergos is not Arch Linux.
The difference is that unlike Manjaro (a non-Arch distro), we don't consider Antergos (a non-Arch distro) to be actively dangerous just to install on your hard drive, and even more dangerous to boot into.

Please do not suggest that Antergos is Arch Linux again. You're doing a disservice to both communities.

...

And lo and behold, Antergos' policy of providing binary packages for AUR helpers results in them lagging behind the AUR and causing issues. This is exceedingly more benevolent as derivative issues go than Manjaro's deadly security malfeasances, but it is still hardly indicative of how a real Arch system works...

**Comment by eli-schwartz** [comment]
On the topic of `/etc/*-release`, it looks like contrary to expectations they still have not fixed https://github.com/Antergos/Cnchi/issues/853#issuecomment-372465876

**Comment by AladW** [comment]
>It may be a good idea to list in the table whether AUR Helpers use AUR RPC or parse .SRCINFOs, what do you think, @Morganamilo, @AladW?

IDK, to me the cases where this distinction is relevant are too specific, i.e. when a maintainer was negligent in running `mksrcinfo` or when dealing with certain split packages or versioned dependencies. Some helpers use both, too (aurutils, pakku).
