### ISSUE TITLE
Certain packages are 'not found' in AUR

### ISSUE THREAD

**Issue by ypnos** [polygamma/aurman#169]
This works as expected:
```
johannes@boron ~/i/b/d/v/mingood_3> pacaur -S aur/package-query
:: Package package-query not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (1) package-query-1.9-3

:: Proceed with installation? [Y/n]
```

This does not:
```
johannes@boron ~/i/b/d/v/mingood_3> aurman -S --aur package-query
~~ initializing aurman...
!! No providers for package-query found.
```

Note that in both cases I explicitely specify to search in AUR because I include a repo that has an outdated version of said package. If I do not specify AUR, both `pacaur` and `aurman` will go ahead and downgrade the package to repo version (which is fine).

**Comment by polygamma** [comment]
Thank you very much for not using the issue template.

**Comment by polygamma** [comment]
Put

```
[aur_packages]
package-query
```

into the `aurman config` and everything should work. Be warned: If you ever "not use" the issue template again, I will block you on GitHub and you won't be able to open issues for `aurman` any further.

**Comment by ypnos** [comment]
I see, this is going all the way back to #23

**Comment by polygamma** [comment]
It indeed is going all the way back to that issue, it's also being pointed out why using "aur/package_name" is not a good idea.
