### ISSUE TITLE
Edit dependencies in PKGBUILD from expac-git to expac

### ISSUE THREAD

**Issue by ajnieset** [polygamma/aurman#170]
THIS TEMPLATE IS FOR BUG REPORTS,
YOU DO NOT HAVE TO USE IT FOR FEATURE REQUESTS

## Description
in the package build file the dependencies list expac-git yet no such package is available and only links to the expac github in the link provided.

## Expected Behavior
when makepkg is run with -s flag it should download all the missing dependencies required to run

## Current Behavior
cannot find the missing dependency expac-git

## Possible Solution
replace in the PKGBUILD file expac-git with expac. i did this when i built it and aurman runs fine

## Version of aurman you are using
2.12 (package built on 6/17/2018

## Steps to Reproduce
_Provide an unambiguous set of steps to reproduce this bug._

1.
2.
3.
4.

## Read the README
_Confirm, that you have read the entire README_

## Running linux distribution
_Write, which linux distribution you are using. If you are using anything besides Arch Linux, e.g. Antergos or Manjaro, you may simply not submit this issue, because those are unsupported._

> **Notice**: If you do not fill out one of the fields, without mentioning **why** you left it out, the issue will be closed without any comment.

**Comment by polygamma** [comment]
You are the first one to be banned from this repository - congratz.
