### ISSUE TITLE
aurman -Syu --do_everything wants to remove openbsd-netcat

### ISSUE THREAD

**Issue by desbma** [polygamma/aurman#174]
## Description
`aurman -Syu --do_everything` always tries to replace `openbsd-netcat` by `gnu-netcat`, even if I have explicitely installed the former.

## Expected Behavior
`aurman -Syu --do_everything` should not do that.

## Current Behavior
See description.

## Possible Solution
Do the expected behavior.
_Seriously this issue template is needlessly verbose._

## Version of aurman you are using
```
$ aurman -V 
:: 2.12-1
```

## Steps to Reproduce

```
$ sudo pacman -Sy openbsd-netcat
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 sublime-text is up to date
resolving dependencies...
looking for conflicting packages...
:: openbsd-netcat and gnu-netcat are in conflict. Remove gnu-netcat? [y/N] y

Package (2)               Old Version  New Version  Net Change

gnu-netcat                0.7.1-6                    -0.06 MiB
community/openbsd-netcat               1.178_3-1      0.07 MiB

Total Installed Size:  0.07 MiB
Net Upgrade Size:      0.01 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                             [####################################################] 100%
(1/1) checking package integrity                                                           [####################################################] 100%
(1/1) loading package files                                                                [####################################################] 100%
(1/1) checking for file conflicts                                                          [####################################################] 100%
(2/2) checking available disk space                                                        [####################################################] 100%
:: Running pre-transaction hooks...
(1/2) Performing snapper pre snapshots for the following configurations...
==> root: 187
(2/2) Removing old entries from the info directory file...
:: Processing package changes...
(1/1) removing gnu-netcat                                                                  [####################################################] 100%
(1/1) installing openbsd-netcat                                                            [####################################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Performing snapper post snapshots for the following configurations...
==> root: 188

$ aurman -Syu --do_everything
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 sublime-text is up to date

~~ initializing aurman...
~~ calculating solutions...

:: The following 1 package(s) are getting installed:
   extra/gnu-netcat          /          ->  0.7.1-6

:: The following 1 package(s) are predicted to get removed:
   community/openbsd-netcat  1.178_3-1  ->  /
:: Package openbsd-netcat will be removed due to a conflict with gnu-netcat

?? Do you want to continue? Y/n: 
~~ looking for new pkgbuilds and fetching them...
resolving dependencies...
looking for conflicting packages...
:: gnu-netcat and openbsd-netcat are in conflict. Remove openbsd-netcat? [y/N] y

Package (2)       Old Version  New Version  Net Change

openbsd-netcat    1.178_3-1                  -0.07 MiB
extra/gnu-netcat               0.7.1-6        0.06 MiB

Total Installed Size:   0.06 MiB
Net Upgrade Size:      -0.01 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                             [####################################################] 100%
(1/1) checking package integrity                                                           [####################################################] 100%
(1/1) loading package files                                                                [####################################################] 100%
(1/1) checking for file conflicts                                                          [####################################################] 100%
(2/2) checking available disk space                                                        [####################################################] 100%
:: Running pre-transaction hooks...
(1/1) Performing snapper pre snapshots for the following configurations...
==> root: 185
:: Processing package changes...
(1/1) removing openbsd-netcat                                                              [####################################################] 100%
(1/1) installing gnu-netcat                                                                [####################################################] 100%
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating the info directory file...
(3/3) Performing snapper post snapshots for the following configurations...
==> root: 186
```

## Read the README
I have read the README, please don't ban me.

## Running linux distribution
Arch Linux, up to date. Please don't ban me I'm not lying.

Thanks.

**Comment by polygamma** [comment]
You are right, `aurman` should not do that, because `pacman` does not try to replace the package. However: https://www.archlinux.org/packages/community/x86_64/openbsd-netcat/ lists `netcat` as being provided and https://www.archlinux.org/packages/extra/x86_64/gnu-netcat/ lists `netcat` as to be replaced. @eli-schwartz - what are the EXACT conditions for `pacman` when to replace other packages?

**Comment by polygamma** [comment]
https://github.com/polygamma/aurman/blob/master/src/aurman/main.py#L618 seems to be wrong.

**Comment by eli-schwartz** [comment]
It should only replace the pkgname itself, not things which provide it.

Since we don't have a netcat package, but rather two replacement packages either one of which is sufficient to replace older netcat packages and provide the unified dependency, this ordinarily results in nothing at all happening... except when --do_everything tries to parse the -u list and provide it manually, but gets it wrong.

It's an... interesting feature, I'm decidedly unsure that I'd want to use my AUR helper to choose which repo to install official packages from.

**Comment by polygamma** [comment]
Why would `aurman` choose the repo? The current implementation is wrong, sure, but where is `aurman` choosing the repo? Not quite getting what you mean

**Comment by polygamma** [comment]
@desbma - please check with `aurman-git`, if the issue has been resolved for you.

**Comment by polygamma** [comment]
@eli-schwartz - now I got you... Yeah, sure, some people do not want to do that, but since that feature is completely optional, there is nothing wrong with it, in my opinion. One may simply not use it.

**Comment by desbma** [comment]
@polygamma I confirm this is fixed with `aurman-git`, thanks.

Also on an unrelated note, please consider rewording you issue template, the threatening/infantilizing tone does not encourage users to report issues.

Thanks for making aurman, and have a nice day.

**Comment by polygamma** [comment]
@desbma - Sorry, the issue template is written with that wording, with that exact intention, to stop most users from creating issues. see e.g.

https://www.reddit.com/r/archlinux/comments/8sh1r9/be_careful_if_you_create_an_issue_for_aurman/
https://github.com/polygamma/aurman/issues/140
https://github.com/polygamma/aurman/issues/175
https://github.com/polygamma/aurman/issues/170
https://github.com/polygamma/aurman/issues/160
https://github.com/polygamma/aurman/issues/153

I could go on and on...

**Comment by polygamma** [comment]
You may also look at the recent issue and you may notice that ca. 80% of them are labeled with `invalid`.

**Comment by desbma** [comment]
A simple sentence "If you do not respect the above template, your issue will be ignored and closed" has the same meaning, and remains welcoming.

I know you get a lot of abuse from some users, but you don't have to adopt their aggressive tone.

If you truly don't want people to report issues (I believe you do), you can simply disable them on GitHub.

**Comment by polygamma** [comment]
Well, but in that case banning the users without "warning" is unfair, in my opinion. And I do want to ban the users, not only close the issues, I really do. I am always grateful for sensible feature requests or well written bug reports, like your report, but I am simply not in the mood to simply close issues and argue with the ones whose issues have been closed afterwards. You may also look at recent issues for that, see e.g. https://github.com/polygamma/aurman/issues/168

Banning is easier for me, I have no intention to communicate with users, who are unable to fill out an issue template in a sensible way, hence banning is the way to go for me. I am not mad at the real persons (at least most of the time), I simply do not want to deal with them as users of `aurman` on GitHub.

**Comment by polygamma** [comment]
You may use `aurman` again, a new release with that bugfix has been pushed to the AUR.

**Comment by polygamma** [comment]
@desbma - see: https://github.com/polygamma/aurman/commit/4cd1e0c2e7f598b140507211ce98954076c741af
