### ISSUE TITLE
Option to show upgradable AUR packages 

### ISSUE THREAD

**Issue by simonbcn** [polygamma/aurman#176]
Currently there is no option to check for AUR packages that have updates without installing them.

**Comment by polygamma** [comment]
`aurman -Syu` or https://github.com/polygamma/aurman/wiki/Using-aurman-as-dependency-solver

**Comment by simonbcn** [comment]
I use an [Update indicator for ArchLinux and Gnome-Shell](https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/) which checks periodically for available updates.
`aurman -Syu` is to update the packages not to get a list of upgradeable packages and also does not return the list of AUR packages that can be upgraded until after running the update with `pacman`.
And the dependency solver is no use here either.

**Comment by polygamma** [comment]
Lol, the dependency solver is of use, you just have to parse the output. If you are not willing to do that, not my problem.
