### ISSUE TITLE
Can't install/update aurman: One or more PGP signatures could not be verified!

### ISSUE THREAD

**Issue by SuddenGunter** [polygamma/aurman#178]
## Description
I've tried to update AUR packages with "aurman -Syu". It was said, that I can install new version of aurman.
I've agreed.
It's said that one or more package signature could not be verified, and if I want to add it or no (or something like that). Didn't helped. Removed aurman. Trying to install it:
```
git clone https://aur.archlinux.org/aurman.git 
cd aurman
makepkg -si
==> Making package: aurman 2.13-1 (Wed 20 Jun 2018 05:41:06 PM EEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning aurman_sources git repo...
Cloning into bare repository '/home/gunter/aurman/aurman_sources'...
remote: Counting objects: 3371, done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 3371 (delta 61), reused 66 (delta 22), pack-reused 3251
Receiving objects: 100% (3371/3371), 635.04 KiB | 1.60 MiB/s, done.
Resolving deltas: 100% (2137/2137), done.
==> Validating source files with md5sums...
    aurman_sources ... Skipped
==> Verifying source file signatures with gpg...
    aurman_sources git repo ... FAILED (unknown public key 465022E743D71E39)
==> ERROR: One or more PGP signatures could not be verified!
```
## Expected Behavior
Aurman installs correctly from AUR

## Current Behavior
ERROR: One or more PGP signatures could not be verified!

## Possible Solution
Fix signature

## Version of aurman you are using
Latest AUR package

## Steps to Reproduce
1.git clone https://aur.archlinux.org/aurman.git 
2.cd aurman
3.makepkg -si

## Read the README
I've read README. Even found "PGP fetching keyserver" part. Didn't helped

## Running linux distribution
Arch 4.17.2-1-ARCH

**Comment by polygamma** [comment]
I... I... I... really want to cry. And I wanna scream.

**Comment by polygamma** [comment]
You mean, **another** pinned comment, which people do not read anyway? The amount of comments removed from the https://aur.archlinux.org/packages/aurman/ package is ridiculous. I honestly do not feel responsible for people not able to solve this GPG *problems*, it's fine if they are unable to use `aurman`. One may simply google `arch unknown public key` to find the *solution*.

**Comment by SuddenGunter** [comment]
Man, just pin it
I've read it and found somewhere in the bottom, that you've publushed your gpg key there.
And why it was working with older aurman version (just install via makepg -si), and not working with newer?

**Comment by polygamma** [comment]
I quote @eli-schwartz from the AUR aurman package page:

> @Cavsfan, I've already explained this. This is a GnuPG issue, not an issue with aurman itself. It is erroneous to ask for GnuPG support here, please consult one of the many Arch Linux support channels, e.g. the Wiki, the BBS, #archlinux on Freenode, and ask for help fixing your GnuPG which is unable to import PGP keys. This will get you an actual solution, unlike complaining here that this one key does not work (to which the only answer is "yes it does, you're wrong").
> 
> The aurman developer does not want to know about your GnuPG issues. His GnuPG works fine, and aurman works fine too. He's not necessarily an expert in GnuPG, but it's irrelevant because if he wanted to spend time providing support for GnuPG, he'd be on those other support channels providing general support on miscellaneous topics. Whereas this is the aurman-specific location for getting support specific to aurman itself.
> 
> There's no reason to "wait until it sorts itself out" -- if your GnuPG is broken, that won't magically fix itself, and it is something you should try to get fixed... by asking for support for GnuPG, in the appropriate places to get support for GnuPG on Arch Linux. Which is not here.

**Comment by polygamma** [comment]
I am going to cherrypick that commit and will merge it later today, @eli-schwartz

**Comment by polygamma** [comment]
I have done that.

**Comment by polygamma** [comment]
I've decided not to append any kind of additional information regarding the import of PGP keys anywhere. Be it in the Issue template, the README in this repo or the page of the aurman package at aur.archlinux.org

This has absolutely nothing to do with aurman itself or the PKGBUILD of aurman. This is a completely normal thing to put into PKGBUILDs in general, and what this means or how to handle it is being explained a thousand times across the internet, one really only has to use google. If that's a hurdle for some users to use aurman, fine, in that case they should not use an AUR Helper anyway.

I'll simply be closing issues regarding this *problem* or even ban the users, depends on how they use the issue template.

**Comment by eli-schwartz** [comment]
Seems reasonable. The new error message clarifies where the problem came from, so users should understand *where* the underlying issue comes from; once they know the issue comes from GnuPG, they are enabled to determine how to fix it in a manner which does not depend on the specific tool (aurman) which **happened** to expose the issue.

**Comment by PetruNN** [comment]
Good evening,
I have a problem with "aurman"
`[ cd aurman-git
[ aurman-git]$ makepkg si
==> Making package: aurman-git 2.14.r0.g6edb4f7-1 (Sun 24 Jun 2018 05:56:29 PM UTC)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning aurman_sources git repo...
Cloning into bare repository '/home/furry/aurman-git/aurman_sources'...
remote: Counting objects: 3454, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 3454 (delta 22), reused 25 (delta 10), pack-reused 3407
Receiving objects: 100% (3454/3454), 640.61 KiB | 1.50 MiB/s, done.
Resolving deltas: 100% (2193/2193), done.
==> Validating source files with md5sums...
    aurman_sources ... Skipped
==> Verifying source file signatures with gpg...
    aurman_sources git repo ... FAILED (unknown public key 465022E743D71E39)
==> ERROR: One or more PGP signatures could not be verified!`

**Comment by ttsrg** [comment]
" gpg --recv-keys 465022E743D71E39"  It's the solution of problem and than you should exec "makepkg -sri"

**Comment by PetruNN** [comment]
thank you. work

**Comment by aissarmurad** [comment]
You need just type `gpg --recv-keys 465022E743D71E39` to fix that problem. ;)

**Comment by oja** [comment]
@polygamma it would be helpful if you posted your key's GPG fingerprint on your github/website, as this is standard practice.

**Comment by polygamma** [comment]
It is already available on Github.

**Comment by eli-schwartz** [comment]
Luckily it is in fact there, just like every other Github user's GPG key available via the Github API.
