### ISSUE TITLE
Request: don't output formatting escape codes when not connected to a tty

### ISSUE THREAD

**Issue by ingolemo** [polygamma/aurman#179]
Currently aurman will output formatting escape codes (for colour and boldness and stuff) unconditionally. But when aurman is outputting somewhere that doesn't support terminal escape codes they can make the output difficult to read. An easy way to see this would be to pipe aurman's output to something like `less`. Here's the output of `aurman -Ss spectrwm | less` as an example:

    community/spectrwm 3.1.0-1 [installed]
        A minimalistic automatic tiling window manager that tries to stay out of the way.
    ESC[1mESC[95maur/ESC[39mESC[22mESC[1mspectrwm-gitESC[22m ESC[1mESC[32m20161209-1ESC[39mESC[22m (16, 0.030555)
        A minimalistic dynamic tiling window manager that tries to stay out of the way.
    ESC[1mESC[95maur/ESC[39mESC[22mESC[1msscrotwm-gitESC[22m ESC[1mESC[32mr33.07c58bf-1ESC[39mESC[22m (3, 0)
        Shriveled scrotwm: A minimalist fork of scrotwm/spectrwm.

The first entry looks correct, presumably because it comes from pacman which knows how to deal with this issue even when colour is otherwise enabled. The other two entries show the issue.

In the particular case of _less_ it is possible to pass the `-R` flag to get less to interpret the escape codes, but that's not true for everything you might want to pipe to.

The usual way to solve this issue is to check if stdout is a tty with `sys.stdout.isatty`, and use that to determine whether to print escape codes.

Relatedly, I'm not quite sure if aurman is supposed to respect pacman's `--color never` flag, but it doesn't seem to do so. Interestingly, `aurman --help` seems to behave correctly.

Thank you for your time.

**Comment by polygamma** [comment]
Aurman indeed handles stripping colors etc. when calling `-V` or `-h`, but not when being called with `-S`. Sorry, I have no intention to change that, because I'd need to touch the whole printing of `aurman` which I am not going to do. Regarding the `--color never` flag, `aurman` does not support that, correct, and will also never do.

**Comment by polygamma** [comment]
Addition: `never` may be wrong, if someone else is willing to implement those things, I'd have no problem with merging those changes.

**Comment by polygamma** [comment]
Well, the lecture I am currently sitting in is quite boring, hence: https://github.com/polygamma/aurman/commit/76d3209aa4d4d49635235dc0087f098e7da12246

Actually it was not problematic to implement. May you install the current `aurman-git` version and check if it works as expected?

**Comment by ingolemo** [comment]
Yep. I tried several commands (including an `aurman -Syu | less`, which I don't recommend by the way) and couldn't find a trace of any escape codes. Everything seems to be working correctly. At least, well enough for what I need.

Thank you for writing aurman and thank you for taking the time to implement this.

**Comment by polygamma** [comment]
You're welcome :)
