### ISSUE TITLE
Ignore Package

### ISSUE THREAD

**Issue by Kuchenm0nster** [polygamma/aurman#18]
Hi there, beeing able to ignore packages would be nice. 
There already is an option in the pacman.conf to ignore a list of packages or whole groups.

**Comment by polygamma** [comment]
https://github.com/polygamma/aurman/commit/8ce38877f307ada83cc6f757f236bc7f856ef94d

**Comment by polygamma** [comment]
Should be the final version by now. Let me know what you think and if it works for you as expected

**Comment by Kuchenm0nster** [comment]
works great, thanks. keep your awesome work up

**Comment by polygamma** [comment]
You're welcome :)
