### ISSUE TITLE
Option to clone an AUR package in the current directory?

### ISSUE THREAD

**Issue by simonbcn** [polygamma/aurman#180]
Is there any option to clone/download an AUR package in the current directory?

**Comment by polygamma** [comment]
you can configure the aurman cache dir and thus set it to the "current dir".

**Comment by simonbcn** [comment]
Ok, and how can I indicate to aurman to just download the package?

**Comment by polygamma** [comment]
you cannot.

**Comment by simonbcn** [comment]
Then there is no option to just download an AUR package.
Could you add it as a [_Feature request_]?

**Comment by polygamma** [comment]
no, because you may simply do that via `git clone`
