### ISSUE TITLE
FYI: A new expac version (v9) is out

### ISSUE THREAD

**Issue by yan12125** [polygamma/aurman#181]
## Description
https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/expac

expac v9 is out 27 minutes ago! Let's go back to the good official package :D

## Expected Behavior
aurman depends on extra/expac v9

## Current Behavior
aurman depends on aur/expac-git

## Possible Solution
`sed#expac-git#expac#`

## Version of aurman you are using
```
$ aurman --version
:: 2.13.1-1
```
I use a prebuilt version from a 3rd-party repository [archlinuxcn], which is [maintained by me](https://github.com/archlinuxcn/repo/commit/ee490793048a9592022f70e38af9b1857b0245f7).

## Steps to Reproduce

1. Check dependencies of aurman: `pacman -Qi aurman | grep expac-git`

## Read the README
_Confirm, that you have read the entire README_

Yes!

## Running linux distribution
Authentic Arch Linux x86_64, with some 3rd-party repositories enabled: [yan12125] and [lxqt] from https://dl.chyen.cc/arch-repo/ and [archlinuxcn] from https://github.com/archlinuxcn/repo.

**Comment by polygamma** [comment]
Thank you, dependency has been changed
