### ISSUE TITLE
--noconfirm still prompts for confirmation during AUR package updates

### ISSUE THREAD

**Issue by GitHubNemo170216** [polygamma/aurman#185]
## Description
When the --noconfirm flag is used, such as:
`aurman -Syu --noconfirm`,
repo packages will be updated without confirmation, as desired; 
however, AUR updates would still get prompts, waiting for confirmation:
```
 The following 1 package(s) are getting updated:
 aur/dropbox    52.4.58-2  ->  52.4.60-1
 ~~ looking for new pkgbuilds and fetching them...
 ?? Do you want to see the changes of dropbox? N/y:
```
## Expected Behavior
The default option is auto-confirmed (e.g. in this case "N").

## Current Behavior
If (and only if) an AUR package is to be updated, updates will pause at the abovementioned question, waiting for confirmation.

## Possible Solution
Allowing aurman to auto-confirm the default option for AUR package updates.

## Version of aurman you are using
_Output of `aurman -V` or `aurman --version`_
```
$ aurman -V
:: 2.14-1
```

## Steps to Reproduce

1. Run
`aurman -Syu --noconfirm`

2. If an AUR package is to be updated, this would happen.

## Read the README
Yes.

## Running linux distribution
Archlinux.

Thank you very much!

**Comment by eli-schwartz** [comment]
I'd expect noconfirm to only accept defaults for options where it is safe to do so, and ask me to review AUR packages which download and execute code from the internet. So this is behaving according to my expectations...

**Comment by polygamma** [comment]
`--noconfirm` does not imply `--noedit`. use both, if you really want that.

**Comment by GitHubNemo170216** [comment]
@eli-schwartz Yeah fair enough, I thought maybe this was designed so as well.

@polygamma Oh awesome, thanks! I think case is closed. 

Thank you guys.

**Comment by polygamma** [comment]
I also want to add, that the descriptions in the README are accurate. `--noconfirm` is a pacman option, also used by `aurman` for aur packages and the manpage of pacman states:

> Bypass any and all “Are you sure?” messages. It’s not a good idea to do this unless you want to run pacman from a script.

Diffs of PKGBUILDs etc. are not "Are you sure?" messages, hence not covered by `--noconfirm`.
The description of `--noedit` states

> Do not show changes of PKGBUILDs, .install, and other relevant files. It assumes you will be okay with the changes.

There is one thing left, which is not covered yet and may lead to needed manual user intervention: `--pgp_fetch`

> Fetch needed PGP keys without asking.
