### ISSUE TITLE
version_comparison() is very slow

### ISSUE THREAD

**Issue by paulie4** [polygamma/aurman#186]
## Description
Since `aurman.utilities.version_comparison()` creates a new process to call `vernum`, it is extremely slow for making over a thousand calls, which is what happens in the `for package in installed_packages` loop in `main.py`.

## Expected Behavior
My computer has 1292 installed packages, so it should take much less than a second to figure out which ones are out of date.

## Current Behavior
With the current implementation of `version_comparison()`, it took my computer about 8.566 seconds to complete the `for package in installed_packages` loop in main.py.

## Possible Solution
Since [vercmp](https://git.archlinux.org/pacman.git/tree/src/util/vercmp.c) is essentially just a shell on top of `alpm_pkg_vercmp()` in `libalpm.so`, it would be much faster to use that library directly. I made that change locally, and the loop time goes from 8.566 seconds down to 0.005 seconds. This is the diff of the version I have locally (if you'd like, I could make a pull request for this):
```
diff --git a/src/aurman/utilities.py b/src/aurman/utilities.py
index 58f3914..93f41fb 100644
--- a/src/aurman/utilities.py
+++ b/src/aurman/utilities.py
@@ -8,6 +8,8 @@ from subprocess import run, DEVNULL, PIPE
 from typing import Tuple, Sequence
 
 import regex
+from ctypes import cdll
+vercmp = cdll.LoadLibrary('libalpm.so').alpm_pkg_vercmp
 
 from aurman.aur_utilities import get_aur_info
 from aurman.coloring import Colors, aurman_error, aurman_question
@@ -161,8 +163,7 @@ def version_comparison(version1: str, comparison_operator: str, version2: str) -
     :return:                        True if the conditional relationship holds, False otherwise
     """
 
-    vercmp_return = int(run("vercmp '{}' '{}'".format(version1, version2), shell=True, stdout=PIPE, stderr=DEVNULL,
-                            universal_newlines=True).stdout.strip())
+    vercmp_return = int(vercmp(bytes(version1, encoding='utf-8'), bytes(version2, encoding='utf-8')))
 
     if vercmp_return < 0:
         return "<" in comparison_operator
```

## Version of aurman you are using
```
$ python aurman/main.py --version
:: 2.14-1
```

## Steps to Reproduce
To check the run time of the loop, I put `from time import time; start = time()` right before the for loop and printed this after the for loop:
```
print(f'loop over installed_packages took {time() - start} seconds')
```

**Comment by eli-schwartz** [comment]
Well, this used to use pyalpm: 482af45d31472190af996ae983377847afbaa993

**Comment by polygamma** [comment]
How do you two think about making `pyalpm` an optional `aurman` dependency? `aurman` would use the direct `libalpm` bindings in case of them being available, otherwise use the current method. In that case a broken `pyalpm` does not break `aurman` and a *fast mode* for `aurman` is always available when `pyalpm` is available.

**Comment by paulie4** [comment]
Oooh, I didn't know there was a `pyalpm`. Yes, that would be better. Why was it removed?  482af45 just says, "remove pyalpm" but doesn't say why.

BTW, I added this code right before the `for package in installed_packages` loop, and `pyalpm.vercmp()` is 4.4 times faster than my suggested call to `alpm_pkg_vercmp()`, so `pyalpm` is definitely the way to go:
```
import pyalpm
from ctypes import cdll
alpm_pkg_vercmp = cdll.LoadLibrary('libalpm.so').alpm_pkg_vercmp
from timeit import timeit
print('timeit 1:', timeit('[vercmp(bytes(upstream_system.all_packages_dict[p.name].version, encoding="utf-8"), bytes(p.version, encoding="utf-8")) for p in installed_packages]',
                          'vercmp = alpm_pkg_vercmp', number=1000, globals=locals()))
print('timeit 2:', timeit('[vercmp(upstream_system.all_packages_dict[p.name].version, p.version) for p in installed_packages]',
                          'vercmp = pyalpm.vercmp', number=1000, globals=locals()))
```

**Comment by eli-schwartz** [comment]
For a very short period of time, pacman 5.1 was in the repos but pyalpm could not be rebuilt for the new libalpm version because of new gcc8 warnings in combination with -Werror. Thus incidentally reaffirming my hatred of -Werror.

**Comment by polygamma** [comment]
great, definitely going to use pyalpm then. Leaves us with the question: optional dependency or not?

Making it optional surely has the benefit of never breaking aurman, on the other hand is it weird to have by far slower vercmp calls by default. I think adding pyalpm back as normal dependency should be done. If it ever going to break again, then I'd only use it as optional.

**Comment by eli-schwartz** [comment]
It's used by our own projects too, e.g. namcap, which is run automatically every time official packages are built. It was a major WTF moment when it broke, and we fixed it pretty fast...

**Comment by paulie4** [comment]
Yeah, if we can avoid forking a lot of separate processes, then that sounds good to me.

**Comment by eli-schwartz** [comment]
Yes, it should. Optimized python bindings should be used if available, and it was only ever removed because you were afrair pyalpm would be totally broken...

If you're still worried that rebuild issue will occur again, you could make pyalpm a hard dependency in the setup.py/PKGBUILD, but guard the import with try/except to fall back on subprocess implementations in the event that pyalpm is installed but broken.

**Comment by polygamma** [comment]
I am going to make use of pyalpm as hard dependency again, not only for vercmp but also instead of pacman-conf usages. will do that today or tomorrow, no need for anyone to open a PR

**Comment by paulie4** [comment]
Awesome, thanks!

**Comment by polygamma** [comment]
the release `2.15` includes the usage of `pyalpm`
