### ISSUE TITLE
Don't pass aurman-specific options to pacman

### ISSUE THREAD

**Issue by HaleTom** [polygamma/aurman#187]
## Description
Currently options applicable only to `aurman` are being passed to `pacman`, causing it to baulk.

If any of these options are setup as part of `alias pacman=aurman --my_fav_option` this will cause a problem.

## Expected Behavior
`aurman`-specific options are not passed through

## Current Behavior

With no alias:
```
$ pacman -Ql zsh-lovers | head -n1
zsh-lovers /usr/
```

With alias:
```
$ alias pacman='aurman --do_everything'
$ pacman -Ql bash
pacman: unrecognized option '--do_everything'
```

## Possible Solution
Filter out `aurman`-only args

## Version of aurman you are using
_Output of `aurman -V` or `aurman --version`_
```
:: 2.14-1
```

## Read the README
Yes

## Running linux distribution
```
$ uname -a
Linux svelte 4.16.14-2-MANJARO #1 SMP PREEMPT Fri Jun 8 20:10:17 UTC 2018 x86_64 GNU/Linux
```

**Comment by polygamma** [comment]
All pacman operations are supported, and calling aurman with an operation besides --sync or -S passes the arguments to pacman.

**Comment by polygamma** [comment]
Also not sure why you are using an alias to use do_everything. You wrote, that you read the readme, so why don't you use the appropriate config option for persistent usage?
