### ISSUE TITLE
When does "Packages you want to be not removed must be aur or repo packages." occur?

### ISSUE THREAD

**Issue by Risen-phoenix** [polygamma/aurman#188]
## Description
While attempting to make some translation corrections, I noticed an error message that I do not understand.  Could someone please explain under what conditions this error is thrown so that I can clarify the message?

Message:

https://github.com/polygamma/aurman/blob/efc1f818bb8a452160ca2cfbdcfd58d898439afa/src/aurman/main.py#L514
## Read the README
Yes.

**Comment by polygamma** [comment]
When using "--holdpkg" or the pacman.conf, the names of the packages you yield must be known packages. either in the aur or the repos
