### ISSUE TITLE
Duplicated/triplicated commits in git history

### ISSUE THREAD

**Issue by ChuckDaniels87** [polygamma/aurman#19]
I just open this issue since there are many (almost all) recent commits that are duplicated/triplicated in different branches. This makes following the progress quite difficult. Previous commits can be fixed with a rebase, but I don't know what is generating these duplicates.

Are you using any git manager in particular or just the command line?

**Comment by polygamma** [comment]
I've rebased, develop and master are now even and the latest commit https://github.com/polygamma/aurman/commit/959531a27915da87e7b19cc38139bde1a1a32aae has appeared only once. Will have an eye on that from now on

**Comment by ChuckDaniels87** [comment]
You can use [interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits) `rebase -i` and squash/drop duplicated commits to clean up previous git history. But use it carefully, it can eat your breakfast and start a nuclear war!

**Comment by polygamma** [comment]
Well, they are not listed...
![](https://user-images.githubusercontent.com/20651500/36938862-4cee825c-1f28-11e8-98a5-a2eb82e33939.png)

**Comment by ChuckDaniels87** [comment]
Yeah, there are very strange problems here. Duplicates are not present but you cannot rebase without changes either:
![captura de pantalla de 2018-03-03 21-41-08](https://user-images.githubusercontent.com/8478202/36939082-c2a533ee-1f2b-11e8-8b99-d3f3e3a957f9.png)
![captura de pantalla de 2018-03-03 21-41-20](https://user-images.githubusercontent.com/8478202/36939083-cb88f144-1f2b-11e8-8aa0-61d109d01776.png)

**Comment by polygamma** [comment]
I merged via smartgit but I changed to do it by hand with the last commit

**Comment by ChuckDaniels87** [comment]
> I merged via smartgit but I changed to do it by hand with the last commit

It seems that it is not that _smart_. [Previous report.](https://stackoverflow.com/questions/19634066/duplicate-commit-on-github-using-smartgit)

I'll take a look at this issue but it seems that history is messed up in some strange way.

**Comment by rmarquis** [comment]
Yeah, I've never seen a single-user [git history](https://github.com/polygamma/aurman/network) so chaotic 😄

**Comment by ChuckDaniels87** [comment]
Ok, I've found a solution.

1. Use an interactive rebase until the first commit ever. In this case, the first commit is `9c72f28`, so:
`git rebase -i 9c72f28`
1. Skip all conflicts using `git rebase --skip`.
1. Take some time to admire the clean and linear history of the branch.
1. Repeat this with all needed branches and force push it to the upstream repository since all hashes will be changed.
1. Never use again _SmartGit_. :laughing:

I've checked the results with an original clone of the repo with messy history, and it seems that there are no differences in any actual file. I've used `diff original_aurman/src modified_aurman/src` and it is clean. In any case, check this out yourself because this solution can potentially destroy the world.

I can tell which is my workflow with git:
1. Create a new branch, p.e. `make-a-coffee`.
1. Do changes and commit changes in this branch.
1. Always rebase this branch to `master` or the branch you will merge those changes into. This will show conflicts in the case original branch has changed in the meantime.
1. Checkout to `master` (or whatever branch) and merge our previous branch (`make-a-coffee`).

**Comment by polygamma** [comment]
Done, thank you very much :)
