### ISSUE TITLE
Machine readable output

### ISSUE THREAD

**Issue by shenghaoyang** [polygamma/aurman#191]
Hello, 

I'm utilizing `aurman` as an `AUR` upgrade checker for quite a few headless Arch Linux machines. I've been running the scripts manually through `SSH`, along with the venerable `checkupdate` script, to check for main repo updates without assuming `root` privileges. Since there's quite a few machines, I was thinking of integrating the whole process through something like `SaltStack`.

Since the `checkupdate` script dumps a database of upgradable packages, but `aurman` doesn't have this functionality, I wrote a little parser to parse the output of `aurman --aur -Syu` to list the upgradable `AUR` packages. It's not _that_ pretty (`aurman` outputs quite a few interactive messages).

This led me to wonder if `aurman` could implement a `--machinereadable` output flag for these kinds of scenarios where you want to call into `aurman` from other programs, a little bit akin to how there is a `--json` flag for some shell utilities.

**Comment by polygamma** [comment]
https://github.com/polygamma/aurman/wiki/Using-aurman-as-dependency-solver

**Comment by shenghaoyang** [comment]
Ah, thanks. Wasn't aware that `aurmansolver` could be used that way. Sorry for the noise on the issues feed.

**Comment by polygamma** [comment]
I guess the dependency solving description is not clear enough, since you are not the first one, who did not notice, that the dependency solver may be used for update notifications. Do you have a suggestion for a better wording to be put in the README?

**Comment by shenghaoyang** [comment]
Hmm, because the _dependency solver_ does way more than simply _solve_ dependencies, it also queries upstream for new packages, etc, it's more of a way to extract `aurman`'s solutions to operations input on the command line, (_a-la_ `-Syu`, `-S`).

I think the header line should probably be changed to:
> Extracting `aurman`'s solutions (packcage changes), to command line operations for use in custom applications

As opposed to:
> Using aurman as dependency solver
