### ISSUE TITLE
Termination during installing/updating of aur/kubectl-bin

### ISSUE THREAD

**Issue by mind-blowing** [polygamma/aurman#194]
## Description
Error during execution of command `aurman -Syu --aur`, looks like problem is in fetching git repository for `aur/kubectl-bin`.

## Expected Behavior
Execution of command `aurman -Syu --aur` should be without any problems because from same environment I can successfully execute command `git clone https://aur.archlinux.org/kubectl-bin.git`.

## Current Behavior
Execution is terminating with this error in output:
```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-07-01 10:17:42,093 - classes - fetch_pkgbuild - ERROR - git fetch of kubectl-bin failed
2018-07-01 10:17:42,093 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 802, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 707, in process
    package.fetch_pkgbuild()
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 900, in fetch_pkgbuild
    raise ConnectionProblem("git fetch of {} failed".format(self.name))
aurman.own_exceptions.ConnectionProblem: git fetch of kubectl-bin failed
```

## Possible Solution
Unfortunately I don't know about possible solution. 

## Version of aurman you are using
`:: 2.15-1`.

## Steps to Reproduce
You should be able to reproduce it if you will try to install kubectl-bin `aurman -S kubectl-bin`.

## Read the README
I did this.

## Running linux distribution
Arch Linux with Linux version `4.17.2-1-ARCH`

**Comment by eli-schwartz** [comment]
Is there a cached kubectl-bin folder in `${XDG_CACHE_HOME:-$HOME/.cache}/aurman/kubectl-bin` that is *not* a git repository?

You may have a broken cache which is confusing aurman. In theory this is only ever created by git itself, which will delete a failed clone...

**Comment by mind-blowing** [comment]
@eli-schwartz you are right, I had empty folder in `${XDG_CACHE_HOME:-$HOME/.cache}/aurman/kubectl-bin`, and when I removed it I didn't had the problem during updating of `kubectl-bin`.

Most probably empty folder was created few days ago when I had very bad WiFi connection with many disconnects, so most probably folder was created but `git clone ...` didn't finish successfully.

But in same time maybe `aurman` should be ready for such case and remove empty folder instead of throwing error that folder is not a git repository.

**Comment by eli-schwartz** [comment]
Again -- I'm confused how this would happen, since `git clone ...` should delete the folder if it exits with a failure.

**Comment by polygamma** [comment]
I think the error messages are clear enough. An advanced user should know, what to do. I am not going to change anything here.

**Comment by frealgagu** [comment]
It happened to me twice the last week with another package. I solved them deleting the folder. I don't know the exact cause of those failed clones but being that ~/.cache/aurman should be used only by aurman, aurman could delete the folder once the error is obtained (but I suppose you need the error code in order to avoid delete folders by other reasons)

**Comment by polygamma** [comment]
I honestly do not want to implement any kind of automatic behavior deleting "malformed directories". I've clarified some of the regarding error messages during a refactor of aurman, see https://github.com/polygamma/aurman/commit/b56691dd72f25d3e0ba0f6d0ea7debaea2ac36dd

The user should be aware of what happened, hence he has to delete those directories manually. It's really not that big of a deal, one execution of `rm`, that's it.

Nevertheless: It would be nice, if one is able to provide steps to reproduce this problem 100% of the time.

**Comment by frealgagu** [comment]
Exactly, but I guess the issue is caused either by network issues or by availability of source which causes the malformed git (talking about not of aur.archlinux but some of downloaded sources) if I'm able to reproduce it again I'll tell you.

**Comment by frealgagu** [comment]
The trace which happens to me eventually is this:

~~ looking for new pkgbuilds of devel packages and fetching them...
fatal: no upstream configured for branch 'makepkg'
2018-07-10 17:26:51,636 - classes - fetch_pkgbuild - ERROR - sources of linphone-desktop-all-git could not be fetched in directory /home/frealgagu/.cache/aurman/linphone-desktop-all-git
2018-07-10 17:26:51,636 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 842, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 610, in process
    package.fetch_pkgbuild()
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 915, in fetch_pkgbuild
    "sources of {} could not be fetched in directory {}".format(self.name, package_dir)
aurman.own_exceptions.ConnectionProblem: sources of linphone-desktop-all-git could not be fetched in directory /home/frealgagu/.cache/aurman/linphone-desktop-all-git

**Comment by polygamma** [comment]
so?

**Comment by eli-schwartz** [comment]
That's great news! It means the new enhanced error message is successfully telling you what folder to investigate...

**Comment by eli-schwartz** [comment]
But aurman should not blindly delete things when it doesn't know why they're broken...

We still don't even understand how this would be possible for aurman to create.

**Comment by mind-blowing** [comment]
> But aurman should not blindly delete things when it doesn't know why they're broken...

From one point of view you are correct, but in same time we are talking about `.cache` folder, so in worst case package git repository will be just cloned again.

If this is persistent problem for someone, then this may be solved as configurable behavior, for example by default it will not delete package cache folder and will require manual analyzing, but user will be able to enable this behavior in case of persistent problem and then package cache folder will be automatically cleaned in case of error.

**Comment by polygamma** [comment]
no, the user may do that manually. I am not interested in supporting such things un aurman

**Comment by eli-schwartz** [comment]
> From one point of view you are correct, but in same time we are talking about .cache folder, so in worst case package git repository will be just cloned again.

I'm not saying it's fundamentally horrifically evil to delete it.

I'm saying you want to add additional code and configuration keys, resulting in an additional maintenance burden, in order to fix a heisenbug that no one understands or can duplicate.

If we understood why it happened and had a reason for thinking that aurman users are likely to run into this as an occasional issue, then it would be much more likely that @polygamma would add cleaning routines to cope with it... but currently the cause is unknown and the issue is "supposed" to be impossible for aurman itself to cause.

**Comment by polygamma** [comment]
@frealgagu - please install the latest `aurman-git` version and post the stacktrace for the problem produced by that `aurman` version

**Comment by polygamma** [comment]
@frealgagu - I am btw not able to build your mentioned package `linphone-desktop-all-git`, see: https://pastebin.com/raw/HNME5ukm

**Comment by frealgagu** [comment]
Got it.

    $ aurman --sync aurman-git
    $ mkdir -p ~/.cache/aurman/aurman-git/src/aurman_sources
    ~~ initializing aurman...
    ~~ looking for new pkgbuilds of devel packages and fetching them...
    ==> Making package: aurman-git 2.16.2.r2.g5636abf-1 (Wed 11 Jul 2018 02:55:43 PM -05)
    ==> WARNING: Skipping dependency checks.
    ==> Retrieving sources...
      -> Updating aurman_sources git repo...
    Fetching origin
    ==> WARNING: Skipping all source file integrity checks.
    ==> Extracting sources...
      -> Creating working copy of aurman_sources git repo...
    Switched to a new branch 'makepkg'
    ==> Starting pkgver()...
    ==> Updated version: aurman-git r87.aed158a-1
    ==> Sources are ready.
    ==> Cleaning up...
    ~~ calculating solutions...
    :: nothing to do... everything is up to date
    $ aurman --sync --sysupgrade --verbose --devel --aur
    ~~ initializing aurman...
    ~~ looking for new pkgbuilds of devel packages and fetching them...
    fatal: no upstream configured for branch 'makepkg'
    There is no tracking information for the current branch.
    Please specify which branch you want to merge with.
    See git-pull(1) for details.
    
        git pull <remote> <branch>
    
    If you wish to set tracking information for this branch you can do so with:
    
        git branch --set-upstream-to=origin/<branch> makepkg
    
    
    2018-07-11 14:59:10,826 - classes - fetch_pkgbuild - ERROR - git pull failed in directory 
    /home/frealgagu/.cache/aurman/aurman-git
    2018-07-11 14:59:10,826 - main - main - ERROR - 
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/aurman/main.py", line 841, in main
        process(argv[1:])
      File "/usr/lib/python3.6/site-packages/aurman/main.py", line 609, in process
        package.fetch_pkgbuild()
      File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 925, in fetch_pkgbuild
        raise ConnectionProblem("git pull failed in directory {}".format(package_dir))
    aurman.own_exceptions.ConnectionProblem: git pull failed in directory /home/frealgagu/.cache/aurman/aurman-git

Then, you are right, something is corrupting the git sources which the next execution is not able to understand.
Something in the makepkg process check out the makepkg branch and does unusable for consequent executions.

**Comment by polygamma** [comment]
steps to reproduce without `aurman` usage:

```
git clone https://aur.archlinux.org/aurman-git.git
cd aurman-git/
mkdir -p src/aurman_sources
makepkg -odc --noprepare --skipinteg
```

at this point the folder is "broken", see e.g.
```
[jonny@jonny-arch-pc aurman-git]$ makepkg --printsrcinfo 
pkgbase = aurman-git
	pkgdesc = AUR helper with almost pacman syntax
	pkgver = r87.aed158a
	pkgrel = 1
	url = https://github.com/polygamma/aurman
	arch = any
	license = MIT
	depends = python
	depends = expac
	depends = python-requests
	depends = git
	depends = python-regex
	depends = python-dateutil
	depends = pyalpm
	provides = aurman
	conflicts = aurman
	source = aurman_sources::git+https://github.com/polygamma/aurman.git?signed#branch=master
	validpgpkeys = 4C3CE98F9579981C21CA1EC3465022E743D71E39
	md5sums = SKIP

pkgname = aurman-git
```

notice the wrong version. or see:
```
[jonny@jonny-arch-pc aurman-git]$ git status
On branch makepkg
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   PKGBUILD

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	aurman_sources/

no changes added to commit (use "git add" and/or "git commit -a")
```

notice being on the branch `makepkg`

all in all: one fiddled around with the folder, added things manually which should have been created by `makepkg`. This is **clearly** not an `aurman` bug, hence I am not going to change anything of `aurman`.

**Comment by eli-schwartz** [comment]
> I've added an empty folder in src/${pkgname} to demonstrate that.

As polygamma said, that's clearly stupid. makepkg explicitly treats that directory as a valid git clone, but you've manually prepared the $srcdir before makepkg ever saw it, thus tricking it into thinking it is continuing on from something else... you've deliberately gone ahead and violated low-level portions of the underlying makepkg command flow.

There's no way to fix this utter and complete garbage. You cannot perform out-of-band modifications of the internal data structure of a program and expect it to go well -- it's no different from attaching a debugger to a running C program and overwriting the active memory with junk.

It's also not something that can be caused simply by runninga makepkg (whether you use an AUR helper like aurman or not). No PKGBUILD code is even run until after the git clone is *correctly* made by makepkg.
