### ISSUE TITLE
Coloring pacman by default

### ISSUE THREAD

**Issue by augustozanellato** [polygamma/aurman#195]
## Description

I think that coloring pacman by default passing --color=always would be a great thing to mantain consistency between pacman and aurman.
## Expected Behavior

Pacman should be colored
## Current Behavior

Pacman isn't colored
## Possible Solution

Pass by default --color=always to pacman, unless the user specify something else in the command line
## Version of aurman you are using

2.14-1
## Steps to Reproduce

1. Launch any command involving pacman (ex. aurman -Syu)

## Read the README

Yes, I've read it
## Running linux distribution

Arch Linux

**Comment by polygamma** [comment]
no, use the pacman.conf if you want pacman to be in color

**Comment by polygamma** [comment]
https://github.com/polygamma/aurman/commit/3d0067a720c286cf4d9077fe4e80be3e904160ea
