### ISSUE TITLE
Implement --overwrite, depreciate --force

### ISSUE THREAD

**Issue by Libbum** [polygamma/aurman#199]
Seems that `--force` is giving us a depreciation warning when attempting to resolve conflicts now.
I'd be happy to push a PR with effectively a search/replace of `force` to `overwrite` to save you the trouble, but I'm not 100% certain if `force` is used in other contexts or not. Since you work more closely with `pacman` perhaps you know a little more about the situation?

**Comment by eli-schwartz** [comment]
Do what what? Aurman does not use force in your behalf, it just passes that option to pacman when you use it.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/compare/1876973b446de7573ddf887d75e446ca03172d95...39dbc0ca4814ade96393cd81d11dbb524f7cf09a

**Comment by polygamma** [comment]
@Libbum - may you check with `aurman-git` if everything works as expected?

**Comment by polygamma** [comment]
Great, I am currently waiting for new issues anyway, since the `2.16` release changed **a bit**, see: https://github.com/polygamma/aurman/compare/2.15...2.16

If everything's fine in 1-2 days, I am pushing a new release including `--overwrite`.

**Comment by Libbum** [comment]
Sounds great! 

When posting this issue I saw your discussions concerning some of the flack you're getting. Sorry to hear that & please don't let it get you down. This is the second enhancement I've requested that has been solved by you in a matter of minutes&mdash;by far the most proactive developer on a critical open source project I've come across.

**Comment by polygamma** [comment]
Thank you very much for the kind words, really appreciate it :) You may close this issue, if you are confident that there are no questions left. Otherwise I will do that after the new release has been pushed

**Comment by Libbum** [comment]
Have done a number of tests today without issue and just read over the codebase again: your changes look good and doesn't look like anything is missing. So I'll close this now, thanks again.

**Comment by Depado** [comment]
Hello :wave: 

First of all, thanks a lot for this great project, it works just fine :ok_hand: 

I'm just a bit troubled by this `--overwrite` flag. I can't seem to use it properly, and have no idea why. This flag isn't intended to work with AUR packages ? 

When using it like so : `aurman -S --overwrite vue-cli`, aurman just exits. I checked the usage of this flag [on the Arch wiki](https://wiki.archlinux.org/index.php/pacman#Troubleshooting). 

```
$ aurman --version
:: 2.16.2-1
$ aurman -S --overwrite vue-cli

$ aurman -v -S --overwrite vue-cli

```

Sorry if I'm just misusing `aurman`

**Comment by polygamma** [comment]
https://www.archlinux.org/news/libutf8proc211-3-update-requires-manual-intervention/ it worked.
