### ISSUE TITLE
Solver doesn't check versioning of repo providers correctly

### ISSUE THREAD

**Issue by rmarquis** [polygamma/aurman#20]
aurman `r257.f2ce5f5-1`.

My system is fully up-to-date, and reinstalling a random AUR packages seem to requier removal of unrelated repo packages:

```
$ aurman -S pacaur-git

~~ analyzing installed packages...
~~ fetching upstream repo packages...
~~ fetching needed aur packages...
~~ fetching ignored packages...
~~ calculating solutions...

:: The following 2 package(s) are getting removed:
   community/intellij-idea-community-edition  2:2017.3.4-1          ->  /
   extra/jdk9-openjdk                         9.0.4.u11-1           ->  /

:: The following 1 package(s) are getting updated:
   aur/pacaur-git                             4.7.10.47.ga0f232d-1  ->  4.7.10-1
?? Do you want to continue? Y/n: n
```

The issue seems related to versioned providers. `jdk9-openjdk` provides `java-environment=9`, while `intellij-idea-community-edition` depends on `java-environment`.
As a side note, the package `jre8-openjdk,` providing `java-runtime=8`, is also installed (though it shouldn't matter here I guess).

With `--deep_search`, other repo packages need to be reinstalled for some reason:
```
$ aurman -S pacaur-git --deep_search

~~ analyzing installed packages...
~~ fetching upstream repo packages...
~~ fetching needed aur packages...
~~ fetching ignored packages...
~~ calculating solutions...

:: The following 2 package(s) are getting installed:
   aur/cower                                  /                      ->  17-2
   core/pacman                                /                      ->  5.0.2-2

:: The following 5 package(s) are getting removed:
   aur/cower-git                              17.5.g59ecf02-1        ->  /
   community/intellij-idea-community-edition  2:2017.3.4-1           ->  /
   extra/jdk9-openjdk                         9.0.4.u11-1            ->  /
   aur/pacman-contrib-git                     0.0.1.r25.g2a5fc09-1   ->  /
   aur/pacman-git                             5.0.1.223.ga7dbe463-1  ->  /

:: The following 1 package(s) are getting updated:
   aur/pacaur-git                             4.7.10.47.ga0f232d-1   ->  4.7.10-1

:: The following 73 package(s) are getting reinstalled:
   core/acl                                   2.2.52-4               ->  2.2.52-4
   core/archlinux-keyring                     20180108-1             ->  20180108-1
   core/attr                                  2.4.47-3               ->  2.4.47-3
   core/bash                                  4.4.019-1              ->  4.4.019-1
   core/bzip2                                 1.0.6-7                ->  1.0.6-7
   core/ca-certificates                       20170307-1             ->  20170307-1
   core/ca-certificates-cacert                20140824-4             ->  20140824-4
   core/ca-certificates-mozilla               3.35-1                 ->  3.35-1
   core/ca-certificates-utils                 20170307-1             ->  20170307-1
   core/coreutils                             8.29-1                 ->  8.29-1
   core/cracklib                              2.9.6-1                ->  2.9.6-1
   core/curl                                  7.58.0-1               ->  7.58.0-1
   core/db                                    5.3.28-3               ->  5.3.28-3
   core/e2fsprogs                             1.43.9-1               ->  1.43.9-1
   extra/expac                                8-1                    ->  8-1
   core/expat                                 2.2.5-1                ->  2.2.5-1
   core/filesystem                            2017.10-2              ->  2017.10-2
   core/findutils                             4.6.0-2                ->  4.6.0-2
   core/gcc-libs                              7.3.0-1                ->  7.3.0-1
   core/gdbm                                  1.14.1-1               ->  1.14.1-1
   extra/git                                  2.16.2-1               ->  2.16.2-1
   core/glib2                                 2.54.3+2+g94b38beff-1  ->  2.54.3+2+g94b38beff-1
   core/glibc                                 2.26-11                ->  2.26-11
   core/gmp                                   6.1.2-1                ->  6.1.2-1
   core/gnupg                                 2.2.5-1                ->  2.2.5-1
   core/gnutls                                3.5.18-1               ->  3.5.18-1
   core/gpgme                                 1.10.0-2               ->  1.10.0-2
   core/grep                                  3.1-1                  ->  3.1-1
   core/iana-etc                              20180221-1             ->  20180221-1
   core/keyutils                              1.5.10-1               ->  1.5.10-1
   core/krb5                                  1.16-1                 ->  1.16-1
   core/libarchive                            3.3.2-1                ->  3.3.2-1
   core/libassuan                             2.5.1-1                ->  2.5.1-1
   core/libcap                                2.25-1                 ->  2.25-1
   core/libffi                                3.2.1-2                ->  3.2.1-2
   core/libgcrypt                             1.8.2-1                ->  1.8.2-1
   core/libgpg-error                          1.27-1                 ->  1.27-1
   core/libidn                                1.33-2                 ->  1.33-2
   core/libidn2                               2.0.4-2                ->  2.0.4-2
   core/libksba                               1.3.5-1                ->  1.3.5-1
   core/libldap                               2.4.45-4               ->  2.4.45-4
   core/libnghttp2                            1.30.0-1               ->  1.30.0-1
   core/libpsl                                0.19.1-1               ->  0.19.1-1
   core/libsasl                               2.1.26-12              ->  2.1.26-12
   core/libsecret                             0.18.5+14+g9980655-1   ->  0.18.5+14+g9980655-1
   core/libssh2                               1.8.0-2                ->  1.8.0-2
   core/libtasn1                              4.13-1                 ->  4.13-1
   core/libtirpc                              1.0.2-3                ->  1.0.2-3
   core/libunistring                          0.9.8-1                ->  0.9.8-1
   core/libutil-linux                         2.31.1-1               ->  2.31.1-1
   core/linux-api-headers                     4.14.8-1               ->  4.14.8-1
   core/lz4                                   1:1.8.1.2-1            ->  1:1.8.1.2-1
   core/ncurses                               6.1-3                  ->  6.1-3
   core/nettle                                3.4-1                  ->  3.4-1
   core/npth                                  1.5-1                  ->  1.5-1
   core/openssl                               1.1.0.g-1              ->  1.1.0.g-1
   core/p11-kit                               0.23.9-1               ->  0.23.9-1
   core/pacman-mirrorlist                     20180224-1             ->  20180224-1
   core/pam                                   1.3.0-1                ->  1.3.0-1
   core/pambase                               20171006-1             ->  20171006-1
   core/pcre                                  8.41-1                 ->  8.41-1
   core/pcre2                                 10.31-1                ->  10.31-1
   core/perl                                  5.26.1-2               ->  5.26.1-2
   extra/perl-error                           0.17025-2              ->  0.17025-2
   core/pinentry                              1.1.0-1                ->  1.1.0-1
   core/readline                              7.0.003-1              ->  7.0.003-1
   core/shadow                                4.5-4                  ->  4.5-4
   core/sqlite                                3.22.0-1               ->  3.22.0-1
   core/sudo                                  1.8.22-1               ->  1.8.22-1
   core/tzdata                                2018c-1                ->  2018c-1
   core/xz                                    5.2.3-1                ->  5.2.3-1
   extra/yajl                                 2.1.0-1                ->  2.1.0-1
   core/zlib                                  1:1.2.11-2             ->  1:1.2.11-2
:: You are using --deep_search, hence --needed is active.
:: These packages will not actually be reinstalled.
?? Do you want to continue? Y/n:
```

Maybe that list of "reinstalled but actually not reinstalled" packages shouldn't be printed, unless it is actually useful in some way to the user(?)

**Comment by polygamma** [comment]
Funny, this exact bug has been found by a friend of mine an hour ago. I'll let you know what the exact cause is, once I've found out.

**Comment by polygamma** [comment]
What is the provider for "ttf-font" on your system? It is a dependency of intellij

**Comment by polygamma** [comment]
Something easier:

Please install aurman with this PKGBUILD: https://pastebin.com/raw/3mDCisAT
run `aurman -S pacaur-git` again and post the output. This will show the unfulfilled dependency

**Comment by rmarquis** [comment]
Both `noto-fonts` and `ttf-dejavu` provide `ttf-font`.

With your PKGBUILD:

```
$ aurman -S pacaur

~~ analyzing installed packages...
~~ fetching upstream repo packages...
~~ fetching needed aur packages...
~~ fetching ignored packages...
~~ calculating solutions...
:: Dependency jre9-openjdk=9.0.4.u11-1 of package jdk9-openjdk-9.0.4.u11-1 is not fulfilled
:: Dependency java-environment of package intellij-idea-community-edition-2:2017.3.4-1 is not fulfilled
:: Dependency jre9-openjdk=9.0.4.u11-1 of package jdk9-openjdk-9.0.4.u11-1 is not fulfilled
:: Dependency java-environment of package intellij-idea-community-edition-2:2017.3.4-1 is not fulfilled

:: The following 1 package(s) are getting installed:
   aur/pacaur                                 /                     ->  4.7.10-1

:: The following 3 package(s) are getting removed:
   community/intellij-idea-community-edition  2:2017.3.4-1          ->  /
   extra/jdk9-openjdk                         9.0.4.u11-1           ->  /
   aur/pacaur-git                             4.7.10.47.ga0f232d-1  ->  /
?? Do you want to continue? Y/n: n
```

The `jre9-openjdk` package is effectively not installed on my system. I did some java-runtime install test last week end and I guess I forgot to reinstall the packages I removed. Oops.

After reinstalling `jre9-openjdk`, aurman behaves as expected.

I'd suggest to print the above warning by default, and not try to remove packages from the system if possible.

**Comment by polygamma** [comment]
How do you think about this: https://github.com/polygamma/aurman/commit/340d2785fe0e6c30a5e0ee85d0892140255c7e6d ?

![](https://user-images.githubusercontent.com/20651500/36946669-6f94e646-1fc0-11e8-9cb5-34c0c786a47d.png)

**Comment by rmarquis** [comment]
LGTM!

**Comment by polygamma** [comment]
Well, i had to google LGTM... :D 
I count this as resolved.

**Comment by polygamma** [comment]
Addition: https://github.com/polygamma/aurman/commit/15f2bd582847e06af42031f60ff21a2e6e3d5e72

**Comment by polygamma** [comment]
Another addition, since you also wrote:

> [...] and not try to remove packages from the system if possible.

![](https://user-images.githubusercontent.com/20651500/36970000-56d47fde-2067-11e8-8079-54a421a1cae2.png)

Specifying a package on the command line declares it so that the aurman solver accepts a solution only if the packge is in the solution, hence it does exactly what we want. if it is not possible, aurman will print the reason. so, everyone is happy, i guess?

**Comment by rmarquis** [comment]
Looking good!

I do however find the "Printing reasons for package being removed... If you want one of these ..." message pretty much unnecessary. It bloats the overall interface without adding anything that is already self explained by the warning right below (package will be removed... due to conflict).

**Comment by polygamma** [comment]
Any idea of where to put it then? I think it is not really intuitive to do that, since the package is already installed. Normally you specify packages which you want to install, not packages which are installed but should not be removed. Extra flag for that, maybe?

**Comment by rmarquis** [comment]
I'm not sure what you mean here by "really intuitive" here. Look at how pacman does it: it doesn't print such message, because they are simply not needed.

Note: using screenshots in github for console output is kinda annoying since we can't copy past its content in subsequent messages. That might be just me though.

**Comment by polygamma** [comment]
I mean the following: It is possible that you execute some aurman -S ... which wants to remove a package.
But at the same it is possible to find a solution for the same problem without the need to remove a package. May be due to reinstalling the package after it has been deleted for building another package or whatever. I think it is not clear that aurman is able to find such a solution if one puts the name of the package to try to not remove also on the command line. But I want to give that information to the user.

Regarding the screenshots: You are right, C&P should be enough.

**Comment by rmarquis** [comment]
I'm not exactly sure in which situation this would actually happen, but that is honestly something that should be put into a man page.

From a user point of view, having an interface that is clear and simple is very appreciable. Messages that are printed again and again will become old quite quickly. Also, half of the content of your first screenshot above is actually noise (the `~~ messages`) since aurman is already very fast.

**Comment by polygamma** [comment]
So: https://github.com/polygamma/aurman/commit/0042f5d0972d2b12e62491b53e3bcb2805efc6e1

Unneeded status message have been removed, but not all of them. When there are things to do which may actually last a few seconds, that is still being printed. Otherwise not.
The messages about reasons to be uninstalled and the hint for putting the packages names on the command line has been removed, too. There is now a new flag: --not_remove
You may specify packages you want to remain installed with that. Nice side effect: If that package you want to be not removed is installed as a dep, it remains installed as dep, since aurman is now able to differentiate between packages to installed and just packages not to uninstall.

**Comment by rmarquis** [comment]
Great! I'd also suggest to use "--holdpkg" to match the "HoldPkg" pacman directive here.

**Comment by polygamma** [comment]
Ah, did not know about this. Will change it and also include it from the pacman.conf if pyalpm supports that. Thanks!

**Comment by polygamma** [comment]
Implemented, but separated holdpkg from the pacman.conf
otherwise every time aurman would include e.g. pacman and glibc into the solution finding, which is probably not what one wants.
