### ISSUE TITLE
Quality of life improvements for non-gentoo users.

### ISSUE THREAD

**Issue by AaronBottegal** [polygamma/aurman#202]
It'd be nice to have some flow like the one shown by yaourt.

Yaourt works by installing normal updates, then in the AUR portion yaourt:

- Show updates, with Y/n/m options. M lets you edit a text file with each update on a line, allowing you to forgo updates by commenting the package out that you may not want. E.g. Linux Kernel updates late in a series, e.g. Ones you know currently won't build and don't want to edit them until they do. This is very common for me, and saves me plenty of time being a daily updater knowing certain packages will not compile.

- After selection of packages, it then just asks if you want to view the pkgbuild for editing. For me this is by far the most commonly edited file for myself, and probably others. This has general fields to change for linux-ck and many more packages, and for most users is all they need to/should edit. It also asks this every time. If I say no, it will behave the same on the next boot, allowing me to then edit it. Aurman currently does not re-ask, so you have to hunt for what to delete to disable this "feature" to build your package how you want. It also lists all the packages, and there's quite a lot to sift through in the list, making it gruesome to find what you want, which is the pkgbuild 99% of the time. **Possible solution:** I think another prompt after the pkg-build prompt might be a good medium for keeping this granularity, along with offering speed for people who just want to edit only the important files for most packages, and would make the workflow for "normal" users much faster and less obtuse.

I understand this takes time and I'm not bitching about make it work like this, I may look into doing it myself, but kinda just wanna know what you guys think about maybe adding these if they were done. Thanks guys.

**Comment by eli-schwartz** [comment]
It's completely madness to re-prompt the user for every file they've already explicitly viewed/edited. And for some pathological installations, you could end up having to manually skip through nearly 500 PKGBUILDs sequentially.

I'm genuinely surprised that anyone considers this a feature. I always considered it a bug that yaourt was incapable of recognizing when you'd already seen and edited a PKGBUILD.

Why don't you just modify it to suit your taste in the first place?

**Comment by eli-schwartz** [comment]
Regarding the listing of updates in an editable text file, I'm sort of ambiguous about this, I tend to feel like if you're that sure it won't work you should probably use IgnorePkg

**Comment by polygamma** [comment]
First things first: `aurman` is not `yaourt` and will never be. I know that many people like what `yaourt` did, but I think that many of those things people like are bad and should not be adopted, hence `aurman` did not adopt them.

> Show updates, with Y/n/m options. M lets you edit a text file with each update on a line, allowing you to forgo updates by commenting the package out that you may not want.

That is a **horrible** idea, because it means supporting partial upgrades by design. Use `--ignore` or the `pacman.conf`.

> If I say no, it will behave the same on the next boot, allowing me to then edit it. Aurman currently does not re-ask, so you have to hunt for what to delete to disable this "feature" to build your package how you want.

You should read the README, the `--always_edit` flag is exactly what you want.

> It also lists all the packages, and there's quite a lot to sift through in the list, making it gruesome to find what you want, which is the pkgbuild 99% of the time. Possible solution: I think another prompt after the pkg-build prompt might be a good medium for keeping this granularity, along with offering speed for people who just want to edit only the important files for most packages, and would make the workflow for "normal" users much faster and less obtuse.

That may be your state of mind, but from a technical point of view, **every** file is equally important, and `aurman` development is driven by technical facts.

All in all: I am not going to change anything about those things you mentioned, sorry.

**Comment by AaronBottegal** [comment]
If they already viewed/edited it, the reason to be redoing the install could be because of issues you may want to view the pkgbuild for. Why not ask again? It's more madness to change the flow of the program for ambiguous reasons and deny the ability to use features because you *believe* they got it right. If it's running again, you should assume it's not right, because that package is being reinstalled after it wasn't installed the first time.


There's also very few packages you edit, let alone edit something other than the pkgbuild. I fail to see the value in editing any files outside of the pkgbuild. I have had to do it myself, but have no had to do it so many times that not having a list would be a killer feature. I usually edit the source between unpacking, or wait for the AUR entry to update for next try.


And I don't edit a my ignored package list just to undo it the next boot in 23 hours when the pkgbuild is fixed for an AUR entry. I do have linux-ck in ignorepkg to make sure I don't update it and update linux-ck-headers only, but all other packages I do want updated ASAP and won't ignored. It's just a quality of life hindrance.


If you combine the selection of updates, along with the editing only offering pkgbuild, it also makes the updates easier. Update everything you don't need to edit the pkgbuild for (495 out of those 500 packages you installed), then run it again editing the pkgbuild on each. This makes it so you don't have to worry about saying the wrong thing to any entry. If I have 500 updates, I have to say yes to only editing linux-ck's, ckb-next, and xyz pkgbuild, I will not sit there and read each line pressing "N" for each until I hit the right ones. Editing the list of updates is bad, but not worse than the flow of aurman presently. If I answer it wrong in aurman, I'd probably just break my keyboard. Lucky me, I currently do this, and I just ctrl+c and use yaourt. I still use yaourt a lot. It's just better. Less features, more features, faster work for 99% of use cases.
