### ISSUE TITLE
Aurman system wide orientated

### ISSUE THREAD

**Issue by spudshack** [polygamma/aurman#203]
Hi there

Love aurman and good programming. Could become the standard for arch.

Please consider my suggestions.

The use of aur packages and their installation is system wide. It's only one aspect of the whole process (makepkg) that is user orientated. There is no intrinsic need for the downloading, build and store to be user specific. Could there be a system wide config file (/etc/aurman.config) for all users, overtaken by any user config if one exists. But not any un-needed empty config files here and there,  or duplications for each user.  Perhaps a user share doc file with examples if wanted. 
To bring it in more tune with makepkg, the config file to specify the download, build and store directories independently for system wide use. I know you can already specify a store location, but for just built compressed package files, like pacman does in /var/cache/pacman/pkg. I use same but with aur for pkg. Then delete all the rest option. For aurman clean, exactly as pacman but for file name. 
If I had my way aurman.config would contain a user name for aurmanto use to call makepkg with so that anyone could use aurman however they want as a system wide utility without worrying about pernissions. But I think a few people would have something to say about that......

Mine is arch linux. Minimal.

**Comment by polygamma** [comment]
Sorry, I am not interested in that.

**Comment by spudshack** [comment]
I am trying here to be a positive in ideas and support for the developer. Are you, however saying that aurman does not store aur source and build in the user directory? Are you also saying that  makepkg is vehemently enforced by it's nature to be only built the directory of the calling user and a configurable definition of work directories is something aurman has no control over?

**Comment by eli-schwartz** [comment]
I'm saying that the BUILDDIR, SRCDEST, PKGDEST are all part of makepkg itself, and makepkg enforces that this must belong to the calling user. aurman does not override this at all, it just clones the PKGBUILD and lets makepkg handle the *use of* the PKGBUILD.

If aurman did allow you to pointlessly duplicate the makepkg.conf settings, it still wouldn't allow you to do so in ways that violate Unix directory permissions enforced by makepkg running as a non-root user.

...

While aurman could add a global configuration for its own options, it's fundamentally a wrapper for makepkg, so I'm not sure I see the utility...

makepkg.conf is written in bash, this makes it possible to implement ad-hoc logic like utilizing $HOME or $USER in the configuration file.
It's also there for documentation, and to allow distributions to override packaging policies without changing the makepkg development sources. These packaging policies are also used in clean chroot builds...

aurman is an interactive tool, and any divergence from defaults is most likely not something that is supposed to be set by an administrator policy. Moreover, your initial suggestion was really focused on controlling makepkg use, not aurman use -- and again, makepkg configuration is independent of aurman.
