### ISSUE TITLE
Thank you for your work

### ISSUE THREAD

**Issue by stratus-ss** [polygamma/aurman#205]
I saw the person full of vitriol talking about how aurman sucks.

I would just like to say thank you for your hard work making a piece of software that allows me to use my computer the way I like. Your work is appreciated

Danke für deine Arbeit! Es gefällt mir! Ich bin sehr dankbar für dich und deine Arbeit. Ich hoffe, du lässt den Mann nicht von dir abschrecken!

Viel dank

**Comment by polygamma** [comment]
Thanks for the kind words, but please do not use issues for this, they are already bloated with many invalid things
