### ISSUE TITLE
unrecognized option: 'DisableDownloadTimeout'

### ISSUE THREAD

**Issue by tYYGH** [polygamma/aurman#207]
## Description
```
/usr/lib/python3.6/site-packages/pycman/config.py:133: InvalidSyntax: unable to parse /etc/pacman.conf, unrecognized option: 'DisableDownloadTimeout'
  warnings.warn(InvalidSyntax(f.name, 'unrecognized option', key))
```

## Expected Behavior
This option is valid, and should be accepted:
https://www.archlinux.org/pacman/pacman.conf.5.html

## Current Behavior
This is my first use. I cannot tell for sure. But it is only a warning, and indeed, so far it seems to be working.

## Possible Solution
Not a big deal. Probably a new keyword to teach to your conf parser, and safely ignore for aurman / pass through to pacman.

## Version of aurman you are using
:: 2.16.3-1

## Steps to Reproduce
With `DisableDownloadTimeout` in its own line of `pacman.conf`, run `aurman -V` for example.

## Read the README
`pacman -Ql aurman|grep README` does not show any README. GitHub’s README does not contain the word `unrecognized`.

## Running linux distribution
Archlinux.

**Comment by eli-schwartz** [comment]
This is coming from pyalpm and not aurman. aurman does not use this key anyway.

But pyalpm should probably have this added to the list of known config keys. Feel free to submit an upstream bug report to pyalpm for this to be added.

**Comment by polygamma** [comment]
which network get requests do you even mean?

**Comment by tYYGH** [comment]
Thinking further about this issue, I realize the requests I meant are not done by the tool, but rather by makepkg. So all should be fine :-)

I suppose, that the only requests aurman actually does on its own are: getting the metadata from AUR, and downloading the PKGBUILD files.

**Comment by polygamma** [comment]
downloading the PKGBUILDs is done via `git clone`, AUR RPC requests via `python-requests`

**Comment by tYYGH** [comment]
Good. No worry, then. Thank you polygamma!
