### ISSUE TITLE
Remove packages that are no longer in any repo or aur

### ISSUE THREAD

**Issue by shaygover** [polygamma/aurman#208]
## Description
When starting an upgrade with aurman it also show "the following packages are neither in known repos nor in the aur". However when I try to remove some of those packages I get "error: target not found"

## Expected Behavior
Either that package will be removed or it won't be shown

## Current Behavior
I can't remove it but it showed as installed.

## Possible Solution
Check how installed packages are detected vs what's required for a package to be removed.

## Version of aurman you are using
2.16.3-1

## Steps to Reproduce
That will be hard, highly system dependent

Perhaps a better solution will be to tell me what debug info u need. 
the only package I found so far is "js-24.2.0-4"
1.
2.
3.
4.

## Read the README
V

## Running linux distribution
Arch x64

**Comment by polygamma** [comment]
Fill out a proper issue with all needed information, e. g. the exact commands you run with the full output etc

**Comment by shaygover** [comment]
Ops. That was the problem. :(
