### ISSUE TITLE
`--noconfirm` does not bypass "have you read the news?"

### ISSUE THREAD

**Issue by ChrisKitching** [polygamma/aurman#211]
It used to be possible to run aurman from scripts using `--noconfirm --pgp_fetch --noedit`. Since the addition of the news feature, a non-skippable "Have you read the news?" question is asked.

I appreciate that this is an useful popup for people using `aurman` as a pacman replacement, but if you're using it as a script to install things from the aur in an unattended fashion, it's a problem.

Any chance we can have a flag for pre-answering this? `--skip-news` perhaps, or simply make `--noconfirm` skip past it?

For bonus points, you could consider something akin to pacman's `--ask`.

**Comment by ChrisKitching** [comment]
Note also: `yes | aurman -S --noconfirm whatever` fails as follows:

```
?? Have you read the news? N/y: 2018-07-14 15:52:26,752 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 890, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 522, in process
    show_unread_news()
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 363, in show_unread_news
    if ask_user("Have you read the news?", False, True):
  File "/usr/lib/python3.6/site-packages/aurman/utilities.py", line 239, in ask_user
    old_settings = termios.tcgetattr(fd)
termios.error: (25, 'Inappropriate ioctl for device')
```

**Comment by polygamma** [comment]
anyway: https://github.com/polygamma/aurman/commit/4c17470770c392ad57f946a27166a7660a13019c

**Comment by ChrisKitching** [comment]
> But does that matter?

People typically expect usual shell programming tools to work. It's definitely a surprise that `yes` doesn't work for a program that asks questions.

If something isn't supported, it's usually a good idea to provide a graceful failure mode and a helpful message instead of just exploding, too.

**Comment by ChrisKitching** [comment]
It's also not *that* ridiculous to expect someone might try to interact with your interactive program by piping a heredoc or something into stdin to reply to its questions - another situation this bug presumably covers.

**Comment by polygamma** [comment]
If you know how to allow reading user input without the need to press "enter" and still allowing the use of tools like `yes` feel free to implement it and open a PR. I am not aware of such solution
