### ISSUE TITLE
News feature breaks aurman when cache is missing.

### ISSUE THREAD

**Issue by ChrisKitching** [polygamma/aurman#212]
Aurman `2.16.5-1`.

## Steps to reproduce
`rm -Rf ~/.cache/aurman`
`aurman -S aurman`

## Output

```
2018-07-14 15:54:30,621 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 890, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 522, in process
    show_unread_news()
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 339, in show_unread_news
    open(seen_ids_file, 'a').close()
FileNotFoundError: [Errno 2] No such file or directory: '/home/chris/.cache/aurman/seen_news_ids'
```

## Expected behaviour

Aurman should function correctly when `~/.cache/aurman` is missing, as it did until this latest version.

**Comment by ChrisKitching** [comment]
Note: `aurman` does not crash if the `~/.cache/aurman` directory exists. It tolerates  `~/.cache/aurman/seen_news_ids` being absent, but crashes if the cache *directory* is missing.

Tiny bit miffed that this new feature was shipped when it completely breaks aurman in a fresh environment.

**Comment by polygamma** [comment]
https://github.com/polygamma/aurman/commit/6bd3422366572cc5424a6e5ce83f697dd903c774
