### ISSUE TITLE
<user> : a password is required ; TTY=pts/0 ; PWD=/home/<user> ; USER=root ; COMMAND=validate

### ISSUE THREAD

**Issue by francoism90** [polygamma/aurman#215]
## Description
If I'm updating an AUR package, the following is echo'd and logged to the journal on package build:
`<user> : a password is required ; TTY=pts/0 ; PWD=/home/<user> ; USER=root ; COMMAND=validate`

## Expected Behavior
Don't know to be honest, is this normal/expected?
Is this a bug?

## Current Behavior
I don't need to provide my password again after building packages.
It seems something goes wrong with the 'sudo keepalive' workaround.

## Possible Solution
Don't know to be honest, but an option would be to debug this a bit more.

## Version of aurman you are using
`2.16.9-1`

## Steps to Reproduce
1. `aurman -Syu`
2. Yes, to build package
3. In the build log and in journal this message is displayed.

## Read the README
Yep, but don' think `no_sudo_loop` is the answer here, because this will disable the sudo loop, and may be required to install a package.

## Running linux distribution
Arch Linux

> **Notice**: If you do not fill out one of the fields, without mentioning **why** you left it out, the issue will be closed without any comment.
You may also be banned from this repository without further warning.

**Comment by polygamma** [comment]
Sorry, I do npt understand your problem. "sudo -v" is being executed, so you may find that in the log

**Comment by polygamma** [comment]
Ah, I guess I know what your problem is. `sudo -v --non-interactive` fails to acquire the privileges. May it be, that you lowered the sudo timeout? If so, adjust the timer for the `aurman` sudo loop accordingly. Otherwise: What changes have you made to your sudoers file?

**Comment by francoism90** [comment]
@polygamma I have looked at my sudo config, seems I had a leftover from a software that required root.
After removing this line, it seems to solve the error/warnings about the sudo loop is gone. :)

I'll reopen this if needed. Thanks for the help and keep up the good work!
