### ISSUE TITLE
Warn in case a package moves from repos to aur

### ISSUE THREAD

**Issue by languitar** [polygamma/aurman#219]
A situation I am often facing is that I do not notice once a package is dropped from the main repos and instead a version is put on AUR. Usually, I would probably want to remove that package in such a situation, because it probably isn't needed by downstream projects anymore. For this reason I also requested an RSS feed with removed packages (https://bugs.archlinux.org/task/53863, https://www.archlinux.org/feeds/packages/removed/).

Would it be possible to include a warning in aurman, in case a package is still installed on a system, but was recently dropped from the main repos. A warning already exists in case the package also isn't covered on AUR anymore, but in case it was migrated there, the situation isn't covered. The aforementioned feed or an internal cache could be used to realize this feature.

**Comment by polygamma** [comment]
I see your point, but I think this is nothing I want to see as feature in `aurman`. Caching the list of installed repo packages, comparing with the currently installed packages to see whether things have changed... It also means: Not using `aurman` to install AUR packages leads to confusing `aurman` because well, there are new installed packages, unknown for `aurman`.

If you really want to have that as a feature, writing a small `bash` or `python` script could already be enough. `pacman -Q` lists all installed packages, `pacman -Qm` all installed packages not found in a repo, `pacman -Qn` all installed repo packages. Just evaluate that data from time to time or before running `aurman`, maybe via a bash alias, and you should be fine.

**Comment by polygamma** [comment]
Hm. After having looked at the feed, I guess that feed may not be used to solve this problem in a sensible way.

But I have an idea. In general I have no problem with coding that feature including the cache, I really see the usecase, and to be honest, I'd use that feature in `aurman` if it were there. I think a compromise I am fine with is to implement this in `aurman`, but with having it turned off by default. No caching at all happening unless enabling this feature. Hence it really comes down to: Read the README to even be aware of that feature existing. And if one enables that feature, he must not cry about `aurman` being [**even slower**](https://github.com/excalibur1234/pacui/issues/40#issuecomment-403196956)

**Comment by languitar** [comment]
An optional feature would of course be fine for me.

**Comment by polygamma** [comment]
Going to implement it, will let you know, when I have done so. You may test the feature in `aurman-git` then.

**Comment by Morganamilo** [comment]
Are you going to handle the opposite case as well?

**Comment by polygamma** [comment]
I plan to notify about **any** changes, means "AUR -> Repo", "Repo -> AUR" and "Repo -> Other Repo".

**Comment by eli-schwartz** [comment]
I would generally tend to think removed packages would be orphans the likes of which you should probably be cleaning up regardless (I will note that yaourt has always had a feature to warn you about packages which became orphaned as a result of the currently just-completed `yaourt -Syu` -- it's dead simple, just compare the results of `pacman -Qqdt` from the beginning and end of the program run to see if any new packages appeared on the list).

If you're still using an explicitly installed package that was moved to the AUR, your reasons for doing so will likely continue to be true, so IMHO people would **want** to keep it installed. `aurman` will already handle security concerns by having you review the PKGBUILD before building, so if you suddenly see an update from the AUR and decide "WTF is this package doing as an AUR package, I don't trust it"... then you now know and can uninstall it.

**Comment by polygamma** [comment]
Will be implementing the warning about new orphans, too, but as separate feature. Those are two different things in my opinion.

**Comment by polygamma** [comment]
What do you think about the following:

![screenshot from 2018-07-18 22-57-32](https://user-images.githubusercontent.com/20651500/42907427-05e675b4-8ade-11e8-8158-2192cb76be34.png)

Obviously what's written there is not true, I just filled out anything manually to have some output

**Comment by polygamma** [comment]
One may install `aurman-git` to see if it works as expected. I decided against making this non default

**Comment by polygamma** [comment]
for the changes see https://github.com/polygamma/aurman/compare/f597a22186b2e6238424a8890c9cf7cad3b663cd...d3afb508ece97c14e99824c8ce96fe4af11b98e7

**Comment by polygamma** [comment]
feature request of @eli-schwartz has also been implemented. https://github.com/polygamma/aurman/commit/96eabe3c3232de9dcf770024fc2142f98dba68e7

![screenshot from 2018-07-19 00-30-20](https://user-images.githubusercontent.com/20651500/42911351-ef0d35f0-8aea-11e8-9faa-1794c5f68816.png)

may also be tested with `aurman-git`

**Comment by languitar** [comment]
Screenshots look pretty nice. I will test this now.

**Comment by languitar** [comment]
Any good idea how to see the effect without having to move a package from the main repos? ;-)

**Comment by polygamma** [comment]
Manipulate the data in the aurman cache folder. The data is saved in the "known_package_places" file. Does not matter if you mess anything up, the file is recreated with every aurman launch. Or simply delete it.

**Comment by polygamma** [comment]
see: 
![screenshot from 2018-07-19 19-05-17](https://user-images.githubusercontent.com/20651500/42958833-f88cc798-8b86-11e8-9433-5cb90fce6a22.png)
![screenshot from 2018-07-19 19-07-14](https://user-images.githubusercontent.com/20651500/42958834-f8a5d602-8b86-11e8-986f-d93793060784.png)

all cases covered.

**Comment by polygamma** [comment]
I also tested the feature warning about orphans extensively, works fine. I pushed a new `aurman` release including both features.

**Comment by polygamma** [comment]
I guess the feature is implemented in a meaningful way, since nobody said something else. Closing this for now

**Comment by languitar** [comment]
Thanks!
