### ISSUE TITLE
AUR packages providings without specifying the versions

### ISSUE THREAD

**Issue by polygamma** [polygamma/aurman#22]
See: https://aur.archlinux.org/packages/ffmpeg-libfdk_aac

A couple of .so are being provided, but without specifying the versions.
If you compare with the ffmpeg package https://www.archlinux.org/packages/extra/x86_64/ffmpeg/
the versions are specified.

This is *really* annoying... Assume you want to install `dolphin-emu` and `ffmpeg-libfdk_aac`.
It is possible to install those packages, but aurman does not find a solution since `dolphin-emu` depends on e.g. `libavcodec.so=57-64` but that is not specified by `ffmpeg-libfdk_aac`, it is just `libavcodec.so` specified. So `aurman` dep solving assumes that it is not possible, which is correct from the standpoint of the solver. But `pacman` uses the .so versions which are known after building the package, e.g. after building `ffmpeg-libfdk_aac`. If you install this package, the `pacman -Qi ffmpeg-libfdk_aac` output yields:

```
Provides        : libavcodec.so=57-64  libavdevice.so=57-64
                  libavfilter.so=6-64  libavformat.so=57-64
                  libavresample.so=3-64  libavutil.so=55-64
                  libpostproc.so=54-64  libswresample.so=2-64
                  libswscale.so=4-64  ffmpeg=3.4.2
```

Manually one could do the following: Install `ffmpeg` and `dolphin-emu` with aurman, that is no problem.
Then install `ffmpeg-libfdk_aac` with aurman. aurman will say that `dolphin-emu` is going to be deleted because of unfulfilled deps, but since aurman is not deleting anything by itself, nothing will happen, because pacman knows the .so versions after installing `ffmpeg-libfdk_aac` and hence does not remove `dolphin-emu`. So, it is not a **real** problem, but I am really, really unhappy with that.

Any ideas for what to do? Or really just to do nothing since `ffmpeg-libfdk_aac` could just specify the versions?

**Comment by AladW** [comment]
Seems like an inconsistency in the PKGBUILD to me, which IMO should be fixed in the PKGBUILD rather than to come up with a workaround. If `aurman` can find out about this scenario it may be useful to warn the user about it, though. (or add something to the README/wiki)

**Comment by polygamma** [comment]
It's quite hard to really "discover" this problem programmatically. Think about it this way:
While dep solving aurman searches for a provider of "libavcodec.so=57-64", when it tries to fulfill the deps of `dolphin-emu`. There is always a known provider, namely `ffmpeg`, since it is a normal repo package. Hence aurman solver does not see a problem with fulfilling this dependency, which is fine. But now `ffmpeg-libfdk_aac` has to be installed, too. It is only possible to install `ffmpeg-libfdk_aac`, if `ffmpeg` gets removed, if it is already installed, or gets not installed at all, which is fine, too. But then aurman checks if the deps of the other packages are still fulfilled, and finds out, that "libavcodec.so=57-64" is not fulfilled anymore. Compare with:

```
[jonny@jonny-arch-pc ~]$ aurman -S dolphin-emu ffmpeg-libfdk_aac --deep_search 

~~ initializing aurman...
~~ the following packages are neither in known repos nor in the aur
:: nm-dispatcher-resolv.conf-git-r9.0a75701-1
~~ calculating solutions...

!! While searching for solutions the following errors occurred:
:: Conflicts between: ffmpeg-libfdk_aac-1:3.4.2-2, ffmpeg-1:3.4.2-1
The package ffmpeg-libfdk_aac had to remain installed, but has been removed.
The package which lead to the removal is ffmpeg
Way to package ffmpeg-libfdk_aac-1:3.4.2-2: ffmpeg-libfdk_aac-1:3.4.2-2
Way to package ffmpeg-1:3.4.2-1: dolphin-emu-1:5.0.r6362.c08f6f0c53-1 -> ffmpeg-1:3.4.2-1

!! we could not find a solution
!! if you think that there should be one, rerun aurman with the --deep_search flag
```

If you have in mind what I described, obviously aurman solved `ffmpeg-libfdk_aac` first, then wanted to solve `dolphin-emu` and hence decides that `ffmpeg` needs to be installed in order to fulfill the dep. But that leads to uninstalling `ffmpeg-libfdk_aac` which must not be, since we want to install that package, too.

**Comment by AladW** [comment]
I think this is one of the main benefits of local repos, in that you just build each package separately, dump it in the local repo and let `pacman` figure out any possible dependencies. Not sure on what procedure to follow when using the current approach.

**Comment by polygamma** [comment]
Well, that is true, but nevertheless would any solver that would try to decide whether what you are trying to do is possible or not, tell you that it is not possible. So even if aurman would throw the packages into a local repo for the final installation, the solver would still tell you "nope, not possible". You had to basically do the same as now, install one package first, then the other and ignore that the solver tells you: "Package xy is going to be deleted". I guess this is really a special case where the user has to use his brain and do it step by step on his own

**Comment by rmarquis** [comment]
Shouldn't you simply assume the non versioned `libavformat.so` fullfills any versioned requirement `libavcodec.so=57-64`?
If it doesn't, then it should be fixed in the PKGBUILD.

**Comment by polygamma** [comment]
Should one? I am really not sure of that. My thoughts, when I coded the "providings detection" was: If one needs no specific version, you just need to have the thing provided at all. But if one specifies a version, you need to fulfill that exact requirement.

**Comment by polygamma** [comment]
Hmm... I think one must not assume that.
Think of the following: `ffmpeg` gets updated and provides newer .so versions.
Now `ffmpeg-libfdk_aac` most likely has to be updated first, to provide the versions for the .so as the `ffmpeg` package does. If one would assume with "libavcodec.so" is everything fine, this would definitely lead to problems, since `dolphin-emu` may require the new .so versions, too, which are really not provided by `ffmpeg-libfdk_aac`

**Comment by rmarquis** [comment]
> Think of the following: ffmpeg gets updated and provides newer .so versions.

Since this is a rolling release, you should always assume the user update AUR packages against the newest repo packages, otherwise this is no different from doing a partial update - which are not supported.

In the above case, `ffmepg` (in repo) would be updated, with maybe `dolphin-emu` (in repo) also rebuilt. When installing `ffmpeg-libfdk_aac` from the AUR (assuming version is same as `ffmpeg`), you can assume it provides an equivalent `libavcodec.so`. If `ffmpeg-libfdk_aac` is an older version, chance are that it will be flagged in the AUR, or that your interface will be intuitive enough so the user is aware of installing an older version.

There _could_ be issues, but all of them involve fixing the PKGBUILDs by the maintainer afaik.

**Comment by polygamma** [comment]
I think I am going to let it be as it is. At least for now. It is a very, very special case anyway. If there are actual problems in the future, one can see what can be done.

**Comment by AladW** [comment]
I'm still not sure why this required such complex changes. You can by all means "exclude" packages from `pacman -Syu` by (temporary) removing the relevant repo/s from the pacman configuration.

**Comment by polygamma** [comment]
Huh, wrong issue, @AladW ?

**Comment by AladW** [comment]
That's a first....
