### ISSUE TITLE
Aurman try to replace the origials packages with the specials build (*-mkl), using "do_everything"

### ISSUE THREAD

**Issue by XavierCLL** [polygamma/aurman#221]
## Description
Updating the system using "do_everything" Aurman try to automatic replace numpy and scipy compiling with mkl, but these special build packages are optional:

![screenshot_20180718_110703](https://user-images.githubusercontent.com/11801453/42894602-e5a16af4-8a7c-11e8-9556-386728a08e9e.png)

## Expected Behavior
Aurman not should replace the original packages with special builds if the user not specify it

## Version of aurman you are using
2.16.9-1

## Steps to Reproduce
1.  install official numpy or/and scipy packages
2. add `arch4edu` repo at end of the file /etc/pacman.conf
```
[arch4edu]
SigLevel = Never
Server = https://mirrors.tuna.tsinghua.edu.cn/arch4edu/$arch
```
3. run system update with aurman with "do_everything"

**Comment by polygamma** [comment]
@eli-schwartz - I am not sure, if this really is invalid. He ran `pacman -Su` and `pacman` did not do anything.

**Comment by XavierCLL** [comment]
Hi @eli-schwartz but not, the repo `arch4edu` is at the end of the file `/etc/pacman.conf`, then it is the opposite

**Comment by polygamma** [comment]
Anyway,  I am not able to reproduce the problem with the steps you mentioned. Please provide a better set of steps to reproduce

**Comment by polygamma** [comment]
Also post your `pacman.conf` and the output of the command `pacman-conf`, please

**Comment by polygamma** [comment]
Also the contents of your `aurman config`

**Comment by eli-schwartz** [comment]
pacman will correctly honor replaces, no matter what order the repositories are in. It's completely different from packages with the same name overriding the package in a later repository; in this case, the actual package that is being installed is "python2-numpy-mkl", which is the only package of its name and cannot be overridden.

They are **different packages**. Your repository configuration lists a package **exclusively** available from [arch4edu], which replaces a package **exclusively** available from [extra].

**Comment by XavierCLL** [comment]
fixed the steps for reproduce.
pacman.conf: https://pastebin.com/zGVLXCQP
pacman-conf: https://pastebin.com/TeSjK7Tt
$ cat .config/aurman/aurman_config                                                                                                                    
[miscellaneous]
show_changes
solution_way
do_everything

**Comment by polygamma** [comment]
I can reproduce it, but I am currently not sure, why `pacman` actually does not try to replace those packages.

**Comment by polygamma** [comment]
Really have to look into it, probably in the `pacman` sourcecode. The thing is:

If you run `pacman -Si python-scipy-mkl` the output is:
```
Repository      : arch4edu
Name            : python-scipy-mkl
Version         : 1.1.0-1
Description     : SciPy is open-source software for mathematics, science, and
                  engineering.
Architecture    : x86_64
URL             : http://www.scipy.org/
Licenses        : BSD
Groups          : None
Provides        : python3-scipy=${pkgver}  python-scipy=${pkgver}
                  scipy=${pkgver}
Depends On      : intel-compiler-base  intel-fortran-compiler  intel-mkl
                  python-numpy  qhull  python-nose
Optional Deps   : python-pillow: for image saving module
Conflicts With  : python-scipy
Replaces        : python-scipy
Download Size   : 11.37 MiB
Installed Size  : 54.65 MiB
Packager        : calil (on behalf of Jingbei Li) <i@jingbei.li>
Build Date      : Sun 08 Jul 2018 06:30:22 AM CEST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

it lists `python-scipy` as to be replaced, so `pacman` *should* try to replace it? But maybe not because of the weird `provides`?

**Comment by Morganamilo** [comment]
Unrelated but some one for sure accidentally wrote those provides in strong quotes. Go an upstream for me to report it to?

**Comment by eli-schwartz** [comment]
Hmm, on second check, replaces will actually take effect on other packages in the **same repo** or below, and for packages which are not in a repo, but not for packages which are in a higher repo.

I was wrong and I remembered wrong. Sorry.

**Comment by polygamma** [comment]
Yeah, actually moving the repo to the top yields to the exact same thing for `pacman -Su`. Will have to implement the proper `replaces` logic in `aurman`, too. Thank you very much for the bug report, interesting edge case

**Comment by eli-schwartz** [comment]
See https://git.archlinux.org/pacman.git/tree/lib/libalpm/sync.c?h=v5.1.0#n244

When pacman calculates replacements, it loops through each repo, checks and if it finds the actual package itself in the repo it then breaks and continues with the next package.

**Comment by polygamma** [comment]
fixed: https://github.com/polygamma/aurman/commit/fa6bd72e113b704884811771d8b4bea863d85d9d
@XavierCLL please check with `aurman-git` if everything works as expected

**Comment by XavierCLL** [comment]
@polygamma yeah, works as expected in the git version, thanks a lot!

**Comment by polygamma** [comment]
You may switch back to `aurman`, the latest version includes the fix.

**Comment by XavierCLL** [comment]
Ok, thanks for the advice!
