### ISSUE TITLE
Arch news reset after reboot

### ISSUE THREAD

**Issue by shaygover** [polygamma/aurman#222]
## Description
After each system reboot I have to retell aurman I've read arch news.

## Expected Behavior
Arch news will show only if there are new items on the news. 

## Current Behavior
aurman forgets I've read the news after a reboot.

## Version of aurman you are using
2.16.9-1

## Steps to Reproduce
1. Run aurman and confirm u read the news
2. Reboot
3. See the old news again...

## Read the README
V

## Running linux distribution
Arch

**Comment by eli-schwartz** [comment]
Is your $XDG_CACHE_HOME getting purged after every boot?

**Comment by polygamma** [comment]
The **rofl** is incoming.

**Comment by shaygover** [comment]
@polygamma:
`[miscellaneous]
cache_dir=/tmp/aurman
use_ask`

Which means yes, the cache will be deleted as it resides on the RAM.

**Comment by polygamma** [comment]
What's the point of opening an issue, then?

**Comment by shaygover** [comment]
@polygamma  Why is it in the cache and not in the config? Cache is supposed to be deleted from time to time.

**Comment by eli-schwartz** [comment]
Because it is not something to be "configured", it is something which can be used to optimize what gets shown to you but has no real effect whatsoever, and if it gets deleted then no harm is done.

Presumably when one puts their cache on a temporary disk, they don't mind this.
