### ISSUE TITLE
Why is not enable install package from specific repo?

### ISSUE THREAD

**Issue by XavierCLL** [polygamma/aurman#226]
## Question

Intall a package from specific repo not works in aurman as:
`aurman -S repo/package`

In pacman works:
`sudo pacman -S repo/package`

It is useful when a package is in multiple repo like `testing` or is more updated in specific repo without change the order in pacman.conf

**Comment by polygamma** [comment]
I suggest you do not ever open an issue again without having read the entire README. I am just not banning you, because your last bug report was actually useful.

**Comment by XavierCLL** [comment]
does the readme explain that? sorry, I did not realize. do you consider my question as spam or like that? this feature is implemented in the most of the aur helpers...

**Comment by polygamma** [comment]
The feature is implemented in `aurman`. And I'd say it also got the best implementation of all AUR helpers available. I quote:

> #### Choose between multiple package sources
> By default `aurman` assumes the following priorities in a case where multiple packages with the same names are available (high to low):
> - Repository package as listed in the pacman.conf - see https://www.archlinux.org/pacman/pacman.conf.5.html#_repository_sections
> > The order of repositories in the configuration file matters; repositories listed first will take precedence over those listed later in the file when packages in two repositories have identical names, regardless of version number.
> - AUR packages
> 
> Overriding this priority has to be done via the aurman config.
> 
> For AUR packages create a section  `[aur_packages]` and list the names of the AUR packages.
> 
> For repo packages create a section `[repo_packages]` and list the names of the repo packages followed by `=` and the name of the repo.
> 
> > **Notice**: These packages will be excluded from the `pacman --sysupgrade` by `--ignore`.
> > Otherwise `pacman` would replace these packages.
> 
> Example:
> ```ini
> [aur_packages]
> aur_package_name
> other_aur_package_name
> 
> [repo_packages]
> repo_package_name=repo_one
> other_repo_package_name=repo_two
> ```

**Comment by polygamma** [comment]
Addition: The relevant discussion: https://github.com/polygamma/aurman/issues/23

**Comment by polygamma** [comment]
For the next time: Writing explicitly, that you read the Readme, but have not found anything regarding such feature, changes a lot. Since you simply wrote a feature request for an existing feature, I assumed you did not read it. Sorry for that, but if you look at recent issues, you'll understand why I am kind of allergic against "not reading the readme"

**Comment by XavierCLL** [comment]
You are right and I understand you, I know about that, for the next occasions I will be more explicit.
