### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by Israellh2001** [polygamma/aurman#227]
I was trying to install something but I got this error

`Traceback (most recent call last):
  File "/usr/bin/aurman", line 11, in <module>
    load_entry_point('aurman==2.16.10', 'console_scripts', 'aurman')()
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 1164, in main
    setlocale(LC_ALL, '')  # initialize locales because python doesn't
  File "/usr/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting`

**Comment by Morganamilo** [comment]
There was an issue template. Fair enough when people don't know about things but the template has to be consciously deleted. Out of curiosity why did you delete it?

**Comment by Israellh2001** [comment]
I'm sorry, this is my first 'issue' that I write and I don't know how to do it

**Comment by eli-schwartz** [comment]
Your locale is broken, and there is nothing aurman has to do with this and there is nothing aurman can do to fix it either.

https://wiki.archlinux.org/index.php/Locale

**Comment by languitar** [comment]
This happens to me as well after upgrading python to 3.7.

**Comment by polygamma** [comment]
Does not happen for me

**Comment by languitar** [comment]
Sorry, found the issue. The update also made a different misconfiguration visible.
