### ISSUE TITLE
aurman keep installing from repo ?

### ISSUE THREAD

**Issue by ringo32** [polygamma/aurman#230]
## Description
have chromium-widevine in repo , but cannot install from aur
## Expected Behavior

i do aurman -S --aur chromium-widevine    , before i did only with -S

but keeps the version install from repo

## Current Behavior

aurman -S --aur chromium-widevine , gives some aur options as normal but, keeps installing stuf from repo

## Possible Solution
with --aur option should not install that package from repo

## Version of aurman you are using

2.16.11.r1.g4ecbc9e-1

## Steps to Reproduce

1. i did as above
2.
3.
4.

## Running linux distribution
antergos

yeah antergos use a siderepo, stil, in aur self is enough side-repo's  in some aur helpers gives options if its sees multiple if its get not figured out.

**Comment by polygamma** [comment]
banned
