### ISSUE TITLE
Is there an environment variable to sky_news?

### ISSUE THREAD

**Issue by oblitum** [polygamma/aurman#231]
Hi, first thanks for this helper.

I've been an ArchLinux user for some years already, and never had to read ArchLinux News to help me out with any issue. Maybe it's because I'm a conscious user and always read install log and follow directions properly. So, I've migrated to aurman recently and ArchLinux News showing up by default on system upgrade it really unexpected, and kind of annoying. I've been using the `--skip_news` flag but wanted to ask whether I can have it permanently? Is there a environment variable for that? If not, I'd like to leave it as a suggestion.

**Comment by polygamma** [comment]
Have you even read the README?

**Comment by oblitum** [comment]
No I didn't read the entire README. I just took an overall look, and search about `skip_news` in it, but to no avail regarding having it as default.

**Comment by oblitum** [comment]
OK, I've found it now, thanks :-)

By the way, nice issue flags.

**Comment by oblitum** [comment]
(gonna steal that thing ...)

**Comment by AladW** [comment]
Now all it needs is a pink soviet flip tag.
