### ISSUE TITLE
Do not warn if package changes from `*-testing` repos or similar (cf. #219)

### ISSUE THREAD

**Issue by LeonardKoenig** [polygamma/aurman#232]
## Description
For users of the testing-repos, aurman always "warns" that the respective packages moved from core to testing.  While the actual feature is meaningful, this behavior harms the usage.  The only workaround would be to deactivate that option completely.

## Possible Solution
Perhaps one could hardcode a check for "testing", this'd be not really flexible. Perhaps one could `blacklist` some repo combinations in the config file? I'd personally be also more than happy if I'd be only warned for AUR<->Repo changes, not changes within repos.  So we could add an option `--skip_new_repo_locations` and be fine.

**Comment by polygamma** [comment]
The need to press one key harms the usage? Why?

**Comment by LeonardKoenig** [comment]
Simply because it happens daily on every upgrade, which makes you either not care about the warning anymore and habitually ignore it or just deactivate the whole feature.
