### ISSUE TITLE
Allow to continue upgrade when build/installation fails

### ISSUE THREAD

**Issue by ngdio** [polygamma/aurman#234]
I have this kind of situation relatively often where I can't upgrade properly because some AUR packages are broken and cannot be build (mostly wrong checksums or build errors). That causes aurman to cancel the entire upgrade and I can't continue with the other packages. It would be great if aurman would just give me the option to edit the source files & retry to continue with the remainder of the upgrade.

**Comment by polygamma** [comment]
Nope, that's not going to happen. If building fails, it's not guaranteed, that further installations etc. are possible, hence no continuation. Regarding the editing: Just rerun `aurman` with `--always_edit` to edit the files.

**Comment by ngdio** [comment]
I have a package which I can't fix because I don't know how and is not needed by any other package. This happens rather often and it surely isn't impossible to check programatically whether the failed package is needed by any others which are getting upgraded. I cannot really upgrade at all if I have a lot of packages and a single one which fails all the time.

**Comment by Morganamilo** [comment]
`--ignore`?

**Comment by polygamma** [comment]
Use `--ignore` or the `pacman.conf`. For me it's not worth the effort, to implement checking for partial solutions after failed building.

**Comment by eli-schwartz** [comment]
Or even delete the broken package from your system.

**Comment by ngdio** [comment]
The package source isn't broken. The PKGBUILD is. The older version works flawlessly. Can use `--ignore` but that still requires manual intervention every time I'm upgrading. I'd highly prefer to have this in a helper which is supposed to take over tasks for me, so agree to disagree I guess.

**Comment by polygamma** [comment]
Why would it require manual intervention everytime you want to upgrade? Use the `pacman.conf`.

**Comment by ngdio** [comment]
I want to receive further upgrades though, but not right at this point. Like I said, I think since this surely isn't impossible to code a helper should have it, but there's no point discussing this any further because it seems like I'm the only one with that opinion.

**Comment by polygamma** [comment]
Honestly the best thing for you to do right now is to ask the maintainer of the AUR package to fix the PKGBUILD.

**Comment by eli-schwartz** [comment]
I think using --ignore every time, in order to remember to stop doing so when the PKGBUILD is fixed, is a reasonable thing to do.
