### ISSUE TITLE
Separate the cache folder and the seen news file

### ISSUE THREAD

**Issue by Akrai** [polygamma/aurman#235]
So i mount the cache folder in tmp so after every reboot aurman asks if i have read the news.
I think the usefulness of specifying the cache folder in tmp is just for saving space, so would be very nice to have two separate configs of specifying folders, one for the cache of packages and the other one for cache of aurman "config" files
What do you think?

**Comment by polygamma** [comment]
`aurman` is not meant to be mounted to `/tmp`, if it's about the disk space, configure `makepkg` in a way you want `makepkg` to work.

**Comment by Akrai** [comment]
how can aurman not be mean to have its cache folder in /tmp if you state it in your help?
https://github.com/polygamma/aurman#specify-a-non-default-folder-to-save-aurman-cache-files

**Comment by polygamma** [comment]
It's an example, not default. The default is not `/tmp`, obviously. Anyway: I am not going to separate the folders of `aurman` even more.

**Comment by eli-schwartz** [comment]
Duplicate of #222

**Comment by AladW** [comment]
>marked this as a duplicate of

Wait what? o_O I guess github thought `duplicate` as a label wasn't enough...
