### ISSUE TITLE
View changes by default

### ISSUE THREAD

**Issue by Alveel** [polygamma/aurman#238]
## Description
I believe aurman should have the default behaviour of showing repo changes, instead of "nah we cool". From the README:
>aurman is targeted at advanced users

It's not like it's a lot of added work, and it can potentially remove a lot of pain if something goes awry. Of course users can disable it with a parameter or line in the config file (how I have enabled it now by default).

## Current Behavior
AUR package changes are not viewed by default

## Possible Solution
Default to view changes on updating AUR package

## Version of aurman you are using
2.17-1

## Steps to Reproduce
1. with default settings install/update any new package using Aurman from the AUR
2. notice it defaults to "no, I don't want to see the changes"
3. suddenly `rm -rf --no-preserve-root /`

## Read the README
I have read the README.

## Running linux distribution
ArchLinux

**Comment by polygamma** [comment]
I don't see the need, because the user is already able to change the behavior and I expect from every user to read the entire README. If they do not, that's not my problem

**Comment by polygamma** [comment]
Addition: For anyone reading this issue, the default is not "do not show changes" but the preselected answer for the question "Do you want to see the changes" is "no", not "yes" as requested by @Alveel.
It is possible to change the preselected answer to "yes", it is also possible to use `--show_changes` via commandline or config, to not get asked at all, but being shown the changes instantly. Using `--noedit` to not being shown the changes, also without being asked is possible, too.
