### ISSUE TITLE
Reinstalling AUR-packages that conflicts repo-packages leads installing the repo-package first, later installing AUR packages again

### ISSUE THREAD

**Issue by steven-omaha** [polygamma/aurman#240]
## Description
In the course of today's python-3.7 upgrade, I needed to reinstall some AUR packages, e.g. `python-matplotlib`, `python-scipy-openblas`, `python-numpy-openblas`. Here, `AUR/python-numpy-openblas` conflicts `extra/python-numpy`. When asking aurman to reinstall those three AUR-packages, `--solution_way` showed that it would want to install `python-numpy` in between the upgrade. This should not be necessary.

The `--deep_search` switch does not help.

## Expected Behavior
When having `python-matplotlib python-scipy-openblas python-numpy-openblas` installed, `aurman -S [those three packages]` should just reinstall them, if necessary in correct in order.

## Current Behavior
When having `python-matplotlib python-scipy-openblas python-numpy-openblas` installed,  `aurman -S [those three packages]` installs repo packages that aren't actually needed in the end, then removes them again later.

## Possible Solution
No idea.

## Version of aurman you are using
`:: 2.17.1-1`

## Steps to Reproduce
EDIT: I forgot to mention, my config uses `do_everything, use_ask, show_changes`. 
1. Have these three packages installed: `python-matplotlib python-scipy-openblas python-numpy-openblas`
2. `aurman -S python-matplotlib python-scipy-openblas python-numpy-openblas --solution_way`
```
~ $ aurman -S python-matplotlib python-numpy-openblas python-scipy-openblas --solution_way 
~~ initializing aurman...
:: Ignoring installed package texlive-bibtexextra
~~ calculating solutions...

:: The following 3 package(s) are getting reinstalled:
   community/python-matplotlib  2.2.2-3   ->  2.2.2-3
   aur/python-numpy-openblas    1.14.5-1  ->  1.14.5-1
   aur/python-scipy-openblas    1.1.0-1   ->  1.1.0-1

~~ The following will be done:
   Reinstall : python-matplotlib
   Remove    : python-numpy-openblas
   Install   : python-numpy
   Remove    : python-scipy-openblas - because of dependency breakage, needs manual intervention
   Remove    : python-numpy
   Install   : python-numpy-openblas
   Install   : python-scipy-openblas

?? Do you want to continue? Y/n: 
```
3. `aurman -S  python-numpy-openblas python-scipy-openblas --solution_way`   # no python-matplotlib here
```
$ aurman -S python-numpy-openblas python-scipy-openblas --solution_way
~~ initializing aurman...
:: Ignoring installed package texlive-bibtexextra
~~ calculating solutions...

:: The following 2 package(s) are getting reinstalled:
   aur/python-numpy-openblas  1.14.5-1  ->  1.14.5-1
   aur/python-scipy-openblas  1.1.0-1   ->  1.1.0-1

~~ The following will be done:
   Reinstall : python-numpy-openblas
   Reinstall : python-scipy-openblas

?? Do you want to continue? Y/n: 
```

## Read the README
I did.

## Running linux distribution
Arch.

Sorry for the many edits in this issue.

**Comment by polygamma** [comment]
interesting... going to look into this, will let you know, when i have done so

**Comment by polygamma** [comment]
You may install `aurman-git`, it should be working again, now. However: I just reverted a commit which introduced the bug, but I still want to have the feature I initially intended, just without the bug, hence I'll not close this issue for now.

**Comment by steven-omaha** [comment]
Thanks for the response. Unfortunately, it's not working yet.
```
~ $ aurman -Qi aurman-git
Name                     : aurman-git
Version                  : 2.17.1.r4.gff71a24-1
Beschreibung             : AUR helper with almost pacman syntax
Architektur              : any
URL                      : https://github.com/polygamma/aurman
Lizenzen                 : MIT
Gruppen                  : Nichts
Stellt bereit            : aurman
Hängt ab von             : python  expac  python-requests  git  python-regex  python-dateutil  pyalpm  python-feedparser
Optionale Abhängigkeiten : Nichts
Benötigt von             : aurman-zsh-completion
Optional für             : Nichts
In Konflikt mit          : aurman
Ersetzt                  : Nichts
Installationsgröße       : 527,00 KiB
Packer                   : Unknown Packager
Erstellt am              : Mo 06 Aug 2018 21:52:11 CEST
Installiert am           : Mo 06 Aug 2018 21:52:14 CEST
Installationsgrund       : Ausdrücklich installiert
Installations-Skript     : Nein
Verifiziert durch        : Nichts

~ $ aurman -S --rebuild python-{matplotlib,numpy-openblas} --solution_way
~~ initializing aurman...
~~ calculating solutions...

:: The following 2 package(s) are getting reinstalled:
   community/python-matplotlib  2.2.2-3   ->  2.2.2-3
   aur/python-numpy-openblas    1.14.5-1  ->  1.14.5-1

~~ The following will be done:
   Reinstall : python-matplotlib
   Remove    : python-numpy-openblas
   Install   : python-numpy
   Remove    : python-numpy
   Install   : python-numpy-openblas

?? Do you want to continue? Y/n:
```

**Comment by polygamma** [comment]
Without `--rebuild` it is working. That's exactly the part I yet have to fix

**Comment by steven-omaha** [comment]
No, not for me.
```
~ [1]$ aurman -S python-{matplotlib,numpy-openblas} --solution_way          
~~ initializing aurman...
~~ calculating solutions...

:: The following 2 package(s) are getting reinstalled:
   community/python-matplotlib  2.2.2-3   ->  2.2.2-3
   aur/python-numpy-openblas    1.14.5-1  ->  1.14.5-1

~~ The following will be done:
   Reinstall : python-matplotlib
   Remove    : python-numpy-openblas
   Install   : python-numpy
   Remove    : python-numpy
   Install   : python-numpy-openblas

?? Do you want to continue? Y/n: 
```

**Comment by polygamma** [comment]
Okay, I am not able to reproduce that.

```
[jonny@jonny-arch-pc ~]$ aurman -S python-{matplotlib,numpy-openblas} --solution_way 
~~ initializing aurman...
~~ the following packages are neither in known repos nor in the aur
:: nm-dispatcher-resolv.conf-git-r9.0a75701-1
~~ calculating solutions...

:: The following 2 package(s) are getting reinstalled:
   community/python-matplotlib  2.2.2-3   ->  2.2.2-3
   aur/python-numpy-openblas    1.14.5-1  ->  1.14.5-1

~~ The following will be done:
   Reinstall : python-matplotlib
   Reinstall : python-numpy-openblas

?? Do you want to continue? Y/n:
```

**Comment by steven-omaha** [comment]
That is surely awkward. Any ideas how to continue from here?

**Comment by steven-omaha** [comment]
To clarify: I have the same behavior on multiple machines, installed in different years.

**Comment by steven-omaha** [comment]
Ah shit, discard the last part. It works for me without `--rebuild`.

**Comment by polygamma** [comment]
Great, then I definitely know the cause. My intention behind this whole buggy feature was to ensure the correct order in which to build/install packages when rebuilding. I guess you remember that, since it's your issue ;D I thought it would be fine to enable this in general, even if not using `--rebuild`, I just enabled it always, not only when using `--rebuild`, that's why it's working as of now, when not using `--rebuild`, because I reverted the commit. What's happening in the dependency solver is the following:

You yield python-{matplotlib,numpy-openblas} on the commandline, which leads when using `--rebuild` to "forgetting" `aurman`, that you've already installed those packages. Unfortunately, python-matplotlib requires python-numpy, which is being provided by python-numpy-openblas, but since `aurman` forcefully forgot about the package, the solver assumes that one needs to install python-numpy in order to install python-matplotlib. I really have to think about this problem, not sure how to solve it, yet

**Comment by steven-omaha** [comment]
Yeah, from the last commit I figured it could be related to that. I'm always happy to break things when it leads to some kind of improvement! :-)

**Comment by polygamma** [comment]
Really a nice edge case :) Will let you know, when I've found a proper solution for the problem

**Comment by steven-omaha** [comment]
No need to hurry with a bugfix. The workaround is easy.

**Comment by polygamma** [comment]
But I hate to have bugs in my software, of which I am aware ;D Sleepless night incoming

**Comment by polygamma** [comment]
Okay, I know how to solve this properly. Sorting the packages before yielding them to the dependency solver, so that dependencies come first. Normally that does not make a difference, but since we forcefully delete installed packages for the solver, we may fix what we are breaking via sorting.

**Comment by polygamma** [comment]
Goddamnit GitHub auto closing of the issues... May you check with `aurman-git` if everything works as expected? see: https://github.com/polygamma/aurman/commit/a84aad3331ef9870dd54b3be2968345752a72612

**Comment by steven-omaha** [comment]
I can confirm: It works. Thanks!

**Comment by polygamma** [comment]
Great :) You may switch back to `aurman`, I pushed a new release for the bugfix.
