### ISSUE TITLE
Feature request: compress packages using more than 1 thread

### ISSUE THREAD

**Issue by navarroaxel** [polygamma/aurman#241]
Hi @polygamma. Thanks for your awesome `aurman` and your dedication 

## Description
Could `aurman` compress the package, before install it, using more than 1 thread? Or is this manage for another program like `makepkg`?

## Expected Behavior
The compress package step should use at least the half of cores of the current CPU. Or make this configurable in some way.

## Current Behavior
The followin step:
```bash
==> Creating package "intellij-idea-ce"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
```
is using just one thread to compress the package using `xz --threads=4 ...` or something like that?

## Possible Solution
I don't know, send some argument to the `makepkg`? or directly to the `xz` program.

## Version of aurman you are using
2.17.2-1

## Steps to Reproduce

1. aurman -S android-studio

Then the package is downloaded, compressed using just 1 thread, and then installed.

## Running linux distribution
Arch Linux
Kernel: 4.17.13-arch1-1-ARCH

**Comment by polygamma** [comment]
`makepkg`

**Comment by polygamma** [comment]
see https://www.archlinux.org/pacman/makepkg.8.html and https://www.archlinux.org/pacman/makepkg.conf.5.html and https://wiki.archlinux.org/index.php/makepkg#Tips_and_tricks

**Comment by navarroaxel** [comment]
Thanks for the reference.
