### ISSUE TITLE
Impossible to edit PKGBUILD to change dependencies if one of them cannot be satisfied before edit

### ISSUE THREAD

**Issue by frealgagu** [polygamma/aurman#243]
## Description
I want to edit a PKGBUILD in order to change a dependency, but it fails because one of its dependencies cannot be satisfied before edit.

## Expected Behavior
aurman should provide a way to edit the PGKBUILD before fail because one of its dependencies insatisfied.

## Current Behavior
aurman shows that "we could not find a solution" even if I pass the flag --always_edit

## Possible Solution
Give the possibility to edit the PKGBUILD before try to resolve dependencies.

## Version of aurman you are using
2.17.2-1

## Steps to Reproduce
1. Keep the system updated (the package glibc should be in 2.28).
2. Try to install rocketchat-desktop via # aurman --sync --always_edit rocketchat-desktop
3. The installations fails with the message "Not provided: glibc<=2.27 but needed by rocketchat-desktop-2.12.0-4"

## Read the README
I've read the Readme and there are no parts which declared it's not possible. Even one of its features said that let me edit the PKGBUILDs before build.

## Running linux distribution
ArchLinux with kernel 4.17.13-arch1-1-ARCH

Thanks in advance, and forgive me if I've missed something.

**Comment by polygamma** [comment]
Sorry, aurman dependency solver relies on the AUR RPC, changes in PKGBUILDs never matter.

**Comment by frealgagu** [comment]
I had heared that, but I thought that I could do something to bypass it. Even if I installed it manually, the future upgrades will fail until the package maintainer fix the dependency.

**Comment by eli-schwartz** [comment]
Duplicate of #163
