### ISSUE TITLE
Aurman Forum

### ISSUE THREAD

**Issue by frealgagu** [polygamma/aurman#244]
Are you thought in create a forum to resolve questions or open discussions about topics related to aurman?
It could be nice to help newbies people and discuss about the aurman implementation. It's not nice to see Issues (and possible banned people) for common questions we could help to solve.

**Comment by eli-schwartz** [comment]
Why do we need an official forum for banned people to go to and get help?

**Comment by frealgagu** [comment]
To avoid open new issues for common questions (I'm not talking about of create a forum for banned people, I'm talking about create a forum to avoid get people banned for common questions).

And not just that, if I want to know something about the implementation of aurman I would open a new issue which is not nice.

**Comment by eli-schwartz** [comment]
> To avoid open new issues for common questions

That is what READMEs are for, except no one reads them. :(

So your solution is what, to pay money to host a forum for these users? 

> if I want to know something about the implementation of aurman I would open a new issue which is not nice

What do you want to know about the implementation?

- "implementation" implies from a developer perspective, are you interested in writing your own AUR helper and comparing it to how aurman does it?
- Do you want end-user *usage* documentation? That implies the README is lacking, or alternatively, that #145
 
If this is a common goal people have, to know about the implementation, then it would be... logical... to develop documentation for it, which would typically be done via a feature request, which is a type of issue.
