### ISSUE TITLE
--always_edit is ignored when solution cannot be found

### ISSUE THREAD

**Issue by ngdio** [polygamma/aurman#249]
## Description
When I'm trying to fix a package conflict by editing the source files, --always_edit is ignored because aurman quits after failing to find a solution.

## Expected Behavior
aurman should allow editing files of the given package before calculating the dependencies.

## Current Behavior
aurman quits before allowing to edit files because no solution could be found.

## Possible Solution
It should be possible to edit the source files of the first package before dependencies are calculated.

## Version of `aurman` you are using
2.17.7-1

## Content of `aurman` config
/

## Steps to Reproduce
1. Install ffmpeg
2. Try to install ffmpeg-libfdk_aac

## Read the README
Yes.

## Running linux distribution
Yes.

> **Notice**: If you do not fill out one of the fields, without mentioning **why** you left it out, the issue will be closed without any comment.
You may also be banned from this repository without further warning.

That's kinda childish.

**Comment by polygamma** [comment]
Not really possible, because the packages from the solution are being shown to the user. There are no packages to show, when not finding a solution. Btw: If it is about a dependency problem, changing them in the PKGBUILD does not work, aurman uses the AUR RPC for dependency resolution.
