### ISSUE TITLE
Can you add edit option to "Do you want to see the changes of <package>? N/y:"?

### ISSUE THREAD

**Issue by shaygover** [polygamma/aurman#251]
Feature request.

Instead of first having to see changes and then asking to edit, let me just edit it.

Thanks

**Comment by polygamma** [comment]
Why?

**Comment by shaygover** [comment]
There is package I need to edit and it's annoying.

**Comment by AladW** [comment]
You really have the most classy user-base @polygamma ^^

**Comment by polygamma** [comment]
Pressing "q" to exit `git diff` really is too much? The need to press one single button? Nope. Just nope.

**Comment by eli-schwartz** [comment]
I'm very much in support of adding a 13-key option to save on the need to press one single key a minute later...

**Comment by polygamma** [comment]
Maybe he is going to edit more than 13 packages, @eli-schwartz ?
