### ISSUE TITLE
'feedparser' and 'regex' distributions missing

### ISSUE THREAD

**Issue by cluxter** [polygamma/aurman#256]
## Description
After successfully installing the `aurman` package in ArchLinux from the AUR, `aurman` won't run.

## Expected Behavior
`aurman` should be able to run because it's useless otherwise.
I think (hope!) there is no need to prove it here...

## Current Behavior
Here are the two messages the execution of `aurman` will return:
```
pkg_resources.DistributionNotFound: The 'feedparser' distribution was not found and is required by aurman
```

```
pkg_resources.DistributionNotFound: The 'regex' distribution was not found and is required by aurman
```

## Possible Solution
I solved this issue by running:
```
$ sudo pip install feedparser
$ sudo pip install regex
```

## Version of `aurman` you are using
v2.18

## Content of `aurman` config
I assume it should be located in `/etc/aurman`. I didn't have anything in here.

## Steps to Reproduce

1. Make sure that the `feedparser` and the `regex` distributions are not installed on your system:
```
$ sudo pip uninstall feedparser
$ sudo pip uninstall regex
```
2. Compile and install `aurman` v2.18 for example like this:
```
$ wget https://aur.archlinux.org/cgit/aur.git/snapshot/aurman.tar.gz
$ tar -xvzf aurman.tar.gz
$ cd aurman
$ makepkg -sci
```
3. Run `aurman`:
```
$ aurman
```
4. See the error.

## Read the README
I do confirm that I've read the README.

## Running linux distribution
```
$ lsb_release -a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
$ uname -a
Linux laptop 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux
```

**Comment by polygamma** [comment]
you broke your packages with your pip usage. reinstall all dependencies again via pacman. do not use sudo pip ever again

**Comment by polygamma** [comment]
Take a look at e.g. https://www.reddit.com/r/archlinux/comments/6vv5ty/guide_how_to_quit_using_pip_to_install_stuff/ or https://www.reddit.com/r/archlinux/comments/8tfvp8/is_the_pacman_repo_software_pythonpip_not/
