### ISSUE TITLE
Setting PKGEXT (disabling compression)

### ISSUE THREAD

**Issue by dbrgn** [polygamma/aurman#257]
In yaourt, you can set `PKGEXT=.pkg.tar` in your `.yaourtrc` to disable compression of packets during the makepkg phase.

Is there something similar for aurman?

**Comment by polygamma** [comment]
Learn how to use the tools provided by Arch.

**Comment by dbrgn** [comment]
I am well aware that I can set this variable in `/etc/makepkg.conf`. But when I build a package directly with makepkg (e.g. for distribution independently from AUR) I do want the compression as a default.

Or am I missing something? :slightly_smiling_face:

**Comment by polygamma** [comment]
You can also use environment variables, create e. g. an alias for your makepkg command, to let this command use another makepkg.conf.

**Comment by dbrgn** [comment]
Ah, an alias is a good workaround! Thanks.

**Comment by dbrgn** [comment]
(As a sidenote, it probably never makes any sense to compress a package when building it with aurman, since it will immediately be decompressed again when installing. For example with android studio, compressing takes several minutes.)

**Comment by polygamma** [comment]
That is definitely true, but I think an AUR helper should not decide such things for the user. Another reason why aurman is targeted at advanced users. Users should be able to configure their makepkg in a meaningful way, that's not the job of the AUR helper

**Comment by eli-schwartz** [comment]
Note that this should only be used for building the package, but not for things like --packagelist or -oc (used when checking for new versions), since the latter are not cases where the user is trying to to configure how to build packages -- they're low-level functions used to scrape for information and aurman needs to control this exactly.

...

Supporting a custom makepkg command could be an easy way to support clean chroot builds, e.g. `MAKEPKG="extra-x86_64-build -- --"`

**Comment by polygamma** [comment]
I have no intention to let the user define custom makepkg commands tbh, only to specify another makepkg.conf. I also think that no harm is done when using that config for e. g. -oc, or can you think of a concrete problem which may arise?

**Comment by eli-schwartz** [comment]
I cannot think of a use it would have, given that makepkg.conf options don't, or shouldn't, affect them at all.

On the other hand, an option to set the makepkg.conf seems like some highly specific overkill, whereas specifying the makepkg command to use would allow, for example:

- setting `--log` (in combination with LOGDEST in makepkg.conf), which cannot be set as default in makepkg.conf
- setting `--nocolor`, `--nocheck`, or `--sign`, although those **could** be specified in makepkg.conf
- using `$HOME/git/pacman/scripts/makepkg-wrapper` to test a dev copy of makepkg from my pacman working tree
- supporting custom --config files
- gets you extra-x86_64-build in an officially deniable way on the side (which is IMHO neat)

**Comment by polygamma** [comment]
going to implement support for --config, everything else is too much in my opinion

**Comment by polygamma** [comment]
Will anyway write it down for the aurman rewrite

**Comment by AladW** [comment]
>whereas specifying the makepkg command to use would allow, for example:

I wonder how this would be necessary when you can simply set PATH for aurman, cf. https://github.com/polygamma/aurman/issues/37#issuecomment-374737645
