### ISSUE TITLE
aurman breaks after partial upgrade

### ISSUE THREAD

**Issue by yarons** [polygamma/aurman#258]
## Description
I ran `aurman -Syyu` and updated my system.
I accidentally hit Enter instead of y at the following prompt:
```
:: mhwd-nvidia-304xx moved from core repo to not known
?? Do you acknowledge the new locations of the mentioned packages? N/y: 
```
aurman broke on the next launch:
```
$ aurman -Syyu
Traceback (most recent call last):
  File "/usr/bin/aurman", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aurman==2.17.8' distribution was not found and is required by the application
```

## Expected Behavior
Keep acting normally and update packages

## Current Behavior
Error message

## Possible Solution
Rebuild the package
I know this is a solution but it shouldn't happen in the first place, is there any scheduled fix?
Although I'm aware that I can and I did rebuild the package it shouldn't happen due to an upgrade (Either `aurman` or `python` version).

## Version of `aurman` you are using
2.17.8

## Content of `aurman` config
Empty

## Steps to Reproduce

1. Any `aurman` command fails, even -V

## Read the README
Yes

## Running linux distribution
Manjaro 17.1.12

**Comment by polygamma** [comment]
no.

**Comment by yarons** [comment]
Upgrading your product should not break it, regardless of how proficient the user is.

I know how to rebuild everything I need and your package is already up and running, yet it shouldn't happen, fix it.

**Comment by polygamma** [comment]
Typical Manjaro user. This is simply how python works and affects all python programs, there is literally nothing I can do about this

**Comment by polygamma** [comment]
banned @yarons, since I am not interested in any further discussion
