### ISSUE TITLE
Cannot resolve dependencies for "makedepends" when updating VCS packages

### ISSUE THREAD

**Issue by K5HV** [polygamma/aurman#260]
## Description
Aurman cannot resolve dependencies for "makedepends" when updating VCS packages

## Expected Behavior
It should install all packages in PKGBUILD's makedepends.
It will be nice to ask to remove them afterwards

## Current Behavior
$ aurman -Su --devel                                                                                                                                                                    
:: Starting full system upgrade...
 there is nothing to do
~~ initializing aurman...
!! There are unfulfilled dependencies of development packages.
   Please fulfill them first
   or use --devel_skip_deps
   or use --optimistic_versioning or --ignore_versioning
   or do not use --devel
   or use --ignore to ignore respective packages
:: aur/dislocker-git misses cmake
:: aur/xorg-server1.19-common-git misses xtrans, xorg-util-macros, libdmx
:: aur/xorg-server1.19-git misses xtrans, xorg-util-macros, libdmx
:: aur/xorg-server1.19-xwayland-git misses xtrans, xorg-util-macros, libdmx

"--devel_skip_deps" switch will fail building because of missing dependencies.
Rest switches (--optimistic_versioning, --ignore_versioning) is not working.

## Possible Solution
Install missing packages

## Version of `aurman` you are using
:: 2.18.r6.g85d854a-1

## Steps to Reproduce
1. Install VCS with makedepends
2. Remove that makedepends
3. Try to update all VCS packages (aurman -Su --devel --needed)
4. It will fail with "There are unfulfilled dependencies of development packages."

## Running linux distribution
Arch Linux

**Comment by polygamma** [comment]
banned @K5HV
