### ISSUE TITLE
Failure with pyalpm 0.8.5.*

### ISSUE THREAD

**Issue by nstickney** [polygamma/aurman#266]
## Description
Nothing works after updating `pyalpm`. I'm seeing the same behavior with `powerpill` due to recent changes in `pyalpm`. The `pyalpm/config.py` file changed as noted [here](https://bbs.archlinux.org/viewtopic.php?pid=1827479#p1827479).

## Expected Behavior
aurman works.

## Current Behavior
```
[bash 5.0.0] $ aurman -Syu
2019-01-20 21:05:49,683 - wrappers - pacman - ERROR - pacman query ['pacman', '-Sg'] failed
2019-01-20 21:05:49,684 - main - main - ERROR -
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/aurman/main.py", line 1312, in main
    process(argv[1:])
  File "/usr/lib/python3.7/site-packages/aurman/main.py", line 816, in process
    groups_chosen = get_groups_to_install(packages_of_user_names)
  File "/usr/lib/python3.7/site-packages/aurman/main.py", line 292, in get_groups_to_install
    groups = pacman(["-Sg"], True, sudo=False)
  File "/usr/lib/python3.7/site-packages/aurman/wrappers.py", line 109, in pacman
    raise InvalidInput("pacman query {} failed".format(pacman_query))
aurman.own_exceptions.InvalidInput: pacman query ['pacman', '-Sg'] failed
```

## Possible Solution
I believe the interface to `pyalpm` needs to be updated.

## Version of `aurman` you are using
```
[bash 5.0.0] $ aurman -V
:: 2.18-1
```

## Content of `aurman` config
Empty

## Steps to Reproduce
1. Update `pyalpm` to `0.8.5.*`
1. `aurman -Syu`

## Read the README
Confirmed.

## Running linux distribution
Arch Linux

> **Notice**: If you do not fill out one of the fields, without mentioning **why** you left it out, the issue will be closed without any comment.
You may also be banned from this repository without further warning.

**Comment by eli-schwartz** [comment]
That's completely unrelated (aurman, unlike powerpill, does not use the changed pyalpm code at all) and the error message is actually claiming that it cannot successfully run `pacman -Sg`.

Please show the output of running `pacman -Sg`.

**Comment by nstickney** [comment]
I'm an idiot and I apologize. I had `pacman` aliased to `powerpill` and I completely forgot. `aurman` completes fine; the issue is `powerpill` only. Sorry to waste your time.
