### ISSUE TITLE
Weird utf-8 error when upgrading aur packages

### ISSUE THREAD

**Issue by sbskas** [polygamma/aurman#267]
## Description
Since a few months, aurman -Suy started to output a stacktrace when upgrading aur packages.

## Expected Behavior
On all my other machines upgrade aur package without any problems.

## Current Behavior
`aurman -Suy
:: Synchronisation des bases de données de paquets…
 core est à jour
 extra est à jour
 community est à jour
 multilib est à jour
:: Début de la mise à jour complète du système…
avertissement : linux : ignore la mise à jour du paquet (4.18.16.arch1-1 => 4.20.11.arch2-1)
avertissement : linux-headers : ignore la mise à jour du paquet (4.18.16.arch1-1 => 4.20.11.arch2-1)
 il n’y a rien à faire

~~ initializing aurman...
~~ the following packages are neither in known repos nor in the aur
:: libnm-gtk-1.8.19dev+21+geebf7f95-1
:: python2-path-10.4-1
:: python-path-10.4-1
:: python2-cssutils-1.0.2-2
:: cower-18-1
2019-02-23 16:12:09,998 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/aurman/main.py", line 1312, in main
    process(argv[1:])
  File "/usr/lib/python3.7/site-packages/aurman/main.py", line 865, in process
    upstream_system = System(System.get_repo_packages())
  File "/usr/lib/python3.7/site-packages/aurman/classes.py", line 1335, in get_repo_packages
    return Package.get_packages_from_expac("-S", [], PossibleTypes.REPO_PACKAGE)
  File "/usr/lib/python3.7/site-packages/aurman/classes.py", line 319, in get_packages_from_expac
    repos = Package.get_known_repos()
  File "/usr/lib/python3.7/site-packages/aurman/classes.py", line 297, in get_known_repos
    return [db.name for db in PacmanConfig(conf="/etc/pacman.conf").initialize_alpm().get_syncdbs()]
  File "/usr/lib/python3.7/site-packages/aurman/classes.py", line 297, in <listcomp>
    return [db.name for db in PacmanConfig(conf="/etc/pacman.conf").initialize_alpm().get_syncdbs()]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte
`
## Possible Solution

Breaking the call fix the problem:
    def get_known_repos() -> List[str]:
        """
        Returns the known repos from the pacman.conf

        :return:    a list containing the known repos (ordered by occurrence in pacman.conf)
        """
        temp =  PacmanConfig(conf="/etc/pacman.conf").initialize_alpm()
        temp2 = temp.get_syncdbs()
        return [db.name for db in temp2]

## Version of `aurman` you are using

aurman -V
:: 2.18-1

## Content of `aurman` config

My aurman config is empty.

## Steps to Reproduce

1.aurman -Suy

Not happening on all my machine. Only one and I don't know why.
It may be unrelated to aurman.

## Read the README

yes I did.

## Running linux distribution

Archlinux.

> **Notice**: If you do not fill out one of the fields, without mentioning **why** you left it out, the issue will be closed without any comment.
You may also be banned from this repository without further warning.

**Comment by Aniket-Pradhan** [comment]
Hi!

Just to improve the readability of the code and the error messages, can you put the code in the "Possible solution" tab in the code blocks?

[Here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) is a Markdown cheat-sheet to help you with the formatting.

Also, as per the end quote:
>**Notice**: If you do not fill out one of the fields, without mentioning **why** you left it out, the issue will be closed without any comment.
You may also be banned from this repository without further warning.

I guess you should fill out the other fields as well.

**Comment by sbskas** [comment]
I patched my comment.
Is that bettre now ?

**Comment by Aniket-Pradhan** [comment]
Yep. Seems good now.

Looking at the error message, I guess the issue is related to your `pacman.conf` file. Maybe, it's corrupted somehow (I don't really know). Can you look up the file yourself, and see if it looks fine or not. A sample pacman.conf looks like [this](https://www.archlinux.org/pacman/pacman.conf.5.html#_example).

Here is an example of my own [pacman.conf](https://pastebin.com/Sf6Q4d6G)

The reason your solution works is because you are skipping the step to open and read the `pacman.conf` file.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/issues/265

Try updating `pyalpm` via `pacman`.
