### ISSUE TITLE
Error message when local search give zero matches

### ISSUE THREAD

**Issue by yaboroda** [polygamma/aurman#27]
[gkulin@vw22 ~]$ aurman -Qs vk  
local/vk-messenger 3.1.0-1  
    VK Messenger for Linux  
[gkulin@vw22 ~]$ aurman -Qs vkmes  
2018-03-13 14:11:16,292 - wrappers - pacman - ERROR - pacman query pacman -Qs vkmes failed

**Comment by polygamma** [comment]
Thanks! Fixed in: https://github.com/polygamma/aurman/commit/eb2d6de3cd93109a812f49abba6d1693fdb8d5a7
