### ISSUE TITLE
pkg_resources.DistributionNotFound workaround

### ISSUE THREAD

**Issue by yawpitch** [polygamma/aurman#271]
Not a bug report, just in case anyone runs into the same issue. Recent large Arch update (this morning) switched the standard Python install to 3.8, leading to this warning:

```
>> aurman --help
[... a lot of Python traceback ...]
pkg_resources.DistributionNotFound: The 'aurman==2.19.1' distribution was not found and is required by the application
```

Solution was quite simple; find the aurman-git source and rebuild the package (ie `makepkg -si` ... though I had to add `-f` because a cached local build was being used instead of a fresh one).

Everything back to working fine.

**Comment by polygamma** [comment]
I want to add one more thing.
With `pacman -Qqo /usr/lib/python3.7/` you can find all packages which need to be rebuilt due to the Python 3.8 push to the Arch repos.

**Comment by chipaltman** [comment]
Thanks guys.

**Comment by MonsterMannen** [comment]
`cd ~/.cache/aurman/aurman/
makepkg -srif`

time saving
