### ISSUE TITLE
Can't update Aurman with new PGP key

### ISSUE THREAD

**Issue by robsears** [polygamma/aurman#274]
## Description
I recently tried to update to 2.20.2, and ran into a PGP issue. It looks like the key was updated [a couple weeks ago](https://github.com/polygamma/aurman/commit/783815e690dea22f827de2537c4a6825a6bb78b4), but there's no indication where one would find that key.

## Expected Behavior
Generally PGP keys are published somewhere, usually on a key server, but it could even be as a file on a personal website. This is how others can validate that some piece of information is coming from a certain source. When using Aurman, PGP keys are usually fetched and added to my keyring automatically, but in some cases, a keyserver needs to be specified.

I usually use something like `gpg --keyserver hkp://host:port --recv-keys KEY` to pull in keys when needed, but that isn't working for the latest PGP key. I've tried numerous keyservers and looked around online, and I can't find this key anywhere. I even tried using the keyserver mentioned in the README.md, to no avail.

## Current Behavior

```
aurman -S --pgp_fetch aurman
~~ initializing aurman...
~~ calculating solutions...

:: The following 1 package(s) are getting updated:
   aur/aurman  2.20.1-2            ->  2.22-1

?? Do you want to continue? Y/n: 
~~ looking for new pkgbuilds and fetching them...
?? Do you want to see the changes of aurman? N/y: 
gpg: keyserver receive failed: No data
2023-05-30 13:22:12,830 - classes - search_and_fetch_pgp_keys - ERROR - Import PGP key F3FAE51DB14A292C5C0A5535910B8C499BED531B failed. This is an error in your GnuPG installation.
2023-05-30 13:22:12,830 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aurman/main.py", line 1312, in main
    process(argv[1:])
  File "/usr/lib/python3.11/site-packages/aurman/main.py", line 1194, in process
    package.show_pkgbuild(noedit, show_changes, pgp_fetch, keyserver, always_edit, default_show_changes)
  File "/usr/lib/python3.11/site-packages/aurman/classes.py", line 1109, in show_pkgbuild
    self.search_and_fetch_pgp_keys(fetch_always, keyserver)
  File "/usr/lib/python3.11/site-packages/aurman/classes.py", line 980, in search_and_fetch_pgp_keys
    raise ConnectionProblem(
aurman.own_exceptions.ConnectionProblem: Import PGP key F3FAE51DB14A292C5C0A5535910B8C499BED531B failed. This is an error in your GnuPG installation.

# Manually install key
gpg --recv-keys F3FAE51DB14A292C5C0A5535910B8C499BED531B           
gpg: keyserver receive failed: No data

# Manually install key from any of several keyservers:
gpg --recv-keys --keyserver <literally any keyserver I can find> F3FAE51DB14A292C5C0A5535910B8C499BED531B
gpg: keyserver receive failed: No data

# Manually install key from keyserver mentioned in README:
gpg --keyserver hkp://ipv4.pool.sks-keyservers.net:11371 --recv-keys F3FAE51DB14A292C5C0A5535910B8C499BED531B
gpg: keyserver receive failed: Server indicated a failure
```

## Possible Solution
Update the README with some information about where we can get the latest PGP key.

## Version of `aurman` you are using
```
aurman -V  
:: 2.20.1-2
```

## Content of `aurman` config
(mine is empty)

## Steps to Reproduce

1. Attempt to fetch the PGP key from a keyserver: `gpg --keyserver hkp://ipv4.pool.sks-keyservers.net:11371 --recv-keys F3FAE51DB14A292C5C0A5535910B8C499BED531B`

## Read the README

I have read the README. The only bit that mentions a default keyserver is [here](https://github.com/polygamma/aurman#config-options), and this does not work for me.

## Running linux distribution

Arch Linux:

```
uname -a
Linux localhost 6.2.13-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 26 Apr 2023 20:50:14 +0000 x86_64 GNU/Linux
```

**Comment by polygamma** [comment]
Hey :)

I'll try to find out what the problem is, but for now, to get it working:

```
curl -O https://github.com/polygamma.gpg && gpg --import polygamma.gpg && rm polygamma.gpg
```

That should do it.

**Comment by polygamma** [comment]
```
[jonny@jonny-arch-pc ~]$ gpg --keyserver keys.openpgp.org --search-key F3FAE51DB14A292C5C0A5535910B8C499BED531B
gpg: data source: http://keys.openpgp.org:11371
(1)	Jonni Westphalen <jonny.westphalen@googlemail.com>
	  3072 bit RSA key 910B8C499BED531B, created: 2023-05-14
```
```
[jonny@jonny-arch-pc ~]$ gpg --keyserver pgp.mit.edu --search-key F3FAE51DB14A292C5C0A5535910B8C499BED531B
gpg: data source: http://pgp.mit.edu:11371
(1)	Jonni Westphalen <jonny.westphalen@googlemail.com>
	  3072 bit RSA key 910B8C499BED531B, created: 2023-05-14
```
```
[jonny@jonny-arch-pc ~]$ gpg --keyserver keyserver.ubuntu.com --search-key F3FAE51DB14A292C5C0A5535910B8C499BED531B
gpg: data source: http://162.213.33.9:11371
(1)	Jonni Westphalen <jonny.westphalen@googlemail.com>
	  3072 bit RSA key 910B8C499BED531B, created: 2023-05-14
```
```
[jonny@jonny-arch-pc ~]$ gpg --keyserver pgp.surf.nl --search-key F3FAE51DB14A292C5C0A5535910B8C499BED531B
gpg: data source: http://pgp.surf.nl:11371
(1)	Jonni Westphalen <jonny.westphalen@googlemail.com>
	  3072 bit RSA key 910B8C499BED531B, created: 2023-05-14
```

Could it e.g. be a firewall on your side, which prevents fetching the key?

**Comment by robsears** [comment]
I think you're right. I have DNS-level ad blocking set up. I disabled it temporarily and re-ran, and was able to import the key just fine. That's a new one!

Thank you for checking :D
