### ISSUE TITLE
Confusing help information

### ISSUE THREAD

**Issue by ChuckDaniels87** [polygamma/aurman#30]
There are three commands with confusing information from `aurman --help`.
`--domain name`
`--keyserver name`
`--holdpkg name`
There are other options that also could use `name`, but this is confusing in any case. I would recommend removing `name` from all options.

In addition, I would capitalize the first letter of _aurman exclusive options_ description to match _native_ ones.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/4a8f64f30fad4c3be92beb0f6ce19ab19d5846cb

**Comment by ChuckDaniels87** [comment]
It looks fine for me now.
