### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by Mauladen** [polygamma/aurman#31]
It would be great if you added support for other languages

**Comment by polygamma** [comment]
Sorry, I do not plan to support other languages. It's not like there is much being printed anyways, and what's being printed is simple english. Sure, it's nice to have, but for me it is not worth the effort. If anyone else really wants to have that as a feature: Feel free to implement it, and open a pull request. If it actually is well written and easy to maintain, I would definitely add it, but I am not going to implement that by myself.

**Comment by Mauladen** [comment]
I agree with you, it is not so important, but for me as a person for whom the native language is not English will be pleased if this functionality is added by anyone

**Comment by btd1337** [comment]
@polygamma Is It possible to organize the project of way to be possible have internalization? The community will create and submit the translations in pull requests.

I put myself at the disposal to translate for Portuguese.

https://docs.python.org/3/library/i18n.html

**Comment by polygamma** [comment]
@btd1337, as I have written before: it is, if someone else does it

**Comment by ognarb** [comment]
If someone want zsh completion, a hacky way would be to install pacaur and with `compdef aurman=pacaur` uses the pacaur completion for aurman. I can try this weekend to adapt the zsh completion from pacaur to aurman

**Comment by polygamma** [comment]
I have decided, that I actually do not want this. The most important part is the README, which is under constant change, it is never possible to also update the translations accordingly. Only changing the `aurman` output leads to people using `aurman` without being able to read the README, which I do not want to support.
