### ISSUE TITLE
aurman output formatting affects all later printed text in bash for windows

### ISSUE THREAD

**Issue by nkbolg** [polygamma/aurman#32]
Described behaviour looks like this:
![image](https://user-images.githubusercontent.com/20271471/37510881-bbda7b5a-290d-11e8-8d77-e774d4a2dff8.png)

Could you fix it or maybe add an option to disable such formatting in output?

Upd:
The thing is you are using "\033[1m" and "\033[21m" for switching bold on and off respectively, and git-bash treats them as increased intensity and double underline. So adding a command line parameter to disable text formatting would be best.

Upd2:
Actually in my case it can be fixed with replacing "\033[21m" in coloring.py:40 with "\033[0m" which stands for reset attributes.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/issues/26

**Comment by polygamma** [comment]
You could just create an alias for aurman, so that an aurman execution is followed by an echo to reset all attributes.

In general I do not feel like supporting edge cases because of using niche software, but a flag to completely turn colors off, should be fine

**Comment by polygamma** [comment]
I have done something else. https://github.com/polygamma/aurman/commit/9512cb40d66e64ed828612119cd50cb82720b334

**Comment by nkbolg** [comment]
Cool, thanks, that works.
