### ISSUE TITLE
Cannot install packages from AUR

### ISSUE THREAD

**Issue by paxet** [polygamma/aurman#33]
I'm trying to use aurman to manage my AUR packages, but can't install nothing from it.
Always gives this error:
> sudo aurman -S package
> ...
> 2018-03-16 11:49:48,920 - wrappers - makepkg - ERROR - makepkg query makepkg --prints

Tried to install tt-ms-fonts, insomnia and others. All have been later correctly installed through:
> makepgk -si

Maybe is a problem in my Arch install and I'm missing some deps.

**Comment by paxet** [comment]
Here it is:
> sudo aurman -S insomnia
> [sudo] password for paxet: 
> 
> ~~ initializing aurman...
> ~~ calculating solutions...
> 
> :: The following 2 package(s) are getting installed:
>    aur/insomnia              /  ->  5.14.9-1
>    community/libcurl-compat  /  ->  7.58.0-2
> ?? Do you want to continue? Y/n: 
> ~~ looking for new pkgbuilds and fetch them...
> ?? Do you want to see the changes of insomnia? N/y: 
> 2018-03-16 12:20:43,129 - wrappers - makepkg - ERROR - makepkg query makepkg --printsrcinfo failed

When asked, I've selected the default option, Yes for the first question and No for the second.

**Comment by polygamma** [comment]
You have to install the `base-devel` group. See: https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started

**Comment by paxet** [comment]
Base devel was installed, no problem with it. Remember I can install AUR packages through manual (and recommended) process.

Thinking about running aurman without installing it. I've cloned this repo in my home folder and launched it by:

> python3 main.py -S insomnia           329ms
> 
> ~~ initializing aurman...
> ~~ calculating solutions...
> 
> :: The following 2 package(s) are getting installed:
>    aur/insomnia              /  ->  5.14.9-1
>    community/libcurl-compat  /  ->  7.58.0-2
> ?? Do you want to continue? Y/n: 
> ~~ looking for new pkgbuilds and fetch them...
> Clonando en 'insomnia'...
> remote: Counting objects: 396, done.
> remote: Compressing objects: 100% (300/300), done.
> remote: Total 396 (delta 178), reused 234 (delta 95)
> Recibiendo objetos: 100% (396/396), 48.99 KiB | 1.17 MiB/s, listo.
> Resolviendo deltas: 100% (178/178), listo.
> ?? Do you want to see the changes of insomnia? N/y: 
> resolviendo dependencias...
> buscando conflictos entre paquetes...
> 
> Paquetes (1) libcurl-compat-7.58.0-2
> 
> Tamaño total de la descarga:    0,20 MiB
> Tamaño total de la instalación:  0,51 MiB
> 
> :: ¿Continuar con la instalación? [S/n] 
> :: Obteniendo los paquetes...
>  libcurl-compat-7.58....   201,9 KiB  2,17M/s 00:00 [##########################] 100%
> (1/1) comprobando las claves del depósito           [##########################] 100%
> (1/1) verificando la integridad de los paquetes     [##########################] 100%
> (1/1) cargando los archivos de los paquetes         [##########################] 100%
> (1/1) comprobando conflictos entre archivos         [##########################] 100%
> (1/1) comprobando el espacio disponible en el d...  [##########################] 100%
> :: Procesando los cambios de los paquetes...
> (1/1) instalando libcurl-compat                     [##########################] 100%
> :: Ejecutando los «hooks» de posinstalación...
> (1/1) Arming ConditionNeedsUpdate...
> ==> Creando el paquete: insomnia 5.14.9-1 (vie mar 16 12:27:41 CET 2018)
> ==> Comprobando dependencias mientras se ejecuta...
> ==> Comprobando dependencias mientras se compila...
> ==> Recibiendo las fuentes...
>   -> Descargando insomnia_5.14.9_amd64.deb...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   615    0   615    0     0   1016      0 --:--:-- --:--:-- --:--:--  1014
> 100 40.5M  100 40.5M    0     0  1715k      0  0:00:24  0:00:24 --:--:-- 2397k
>   -> insomnia.sh ha sido encontrado 
> ==> Validando los archivos source con md5sums...
>     insomnia_5.14.9_amd64.deb ... Aprobado
>     insomnia.sh ... Aprobado
> ==> Extrayendo las fuentes...
>   -> Extrayendo insomnia_5.14.9_amd64.deb con bsdtar
> ==> Entrando en entorno fakeroot...
> ==> Iniciando package()...
> ==> Depurando la instalación...
>   -> Quitando los archivos libtool...
>   -> Purgando los archivos innecesarios...
>   -> Quitando los archivos de las bibliotecas estáticas...
>   -> Comprimiendo las páginas del manual e información...
> ==> Buscando problemas de empaquetado...
> ==> Creando el paquete «insomnia»...
>   -> Generando el archivo .PKGINFO...
>   -> Generando el archivo .BUILDINFO...
>   -> Generando el archivo .MTREE...
>   -> Comprimiendo el paquete...
> ==> Abandonando el entorno fakeroot.
> ==> Compilación terminada: insomnia 5.14.9-1 (vie mar 16 12:29:36 CET 2018)
> ==> Limpiando...
> cargando los paquetes...
> resolviendo dependencias...
> buscando conflictos entre paquetes...
> 
> Paquetes (1) insomnia-5.14.9-1
> 
> Tamaño total de la instalación:  178,23 MiB
> 
> :: ¿Continuar con la instalación? [S/n] 
> (1/1) comprobando las claves del depósito           [##########################] 100%
> (1/1) verificando la integridad de los paquetes     [##########################] 100%
> (1/1) cargando los archivos de los paquetes         [##########################] 100%
> (1/1) comprobando conflictos entre archivos         [##########################] 100%
> (1/1) comprobando el espacio disponible en el d...  [##########################] 100%
> :: Procesando los cambios de los paquetes...
> (1/1) instalando insomnia                           [##########################] 100%
> :: Ejecutando los «hooks» de posinstalación...
> (1/3) Updating icon theme caches...
> (2/3) Arming ConditionNeedsUpdate...
> (3/3) Updating the desktop file MIME type cache...

Install went fine. So there is a problem with aurman installed as system package.
Uninstalling a package runs well:

> sudo aurman -R insomnia                   210ms
> [sudo] password for jcl: 
> comprobando dependencias...
> 
> Paquetes (1) insomnia-5.14.9-1
> 
> Tamaño total quitado:  178,23 MiB
> 
> :: ¿Desea quitar estos paquetes? [S/n] 
> :: Procesando los cambios de los paquetes...
> (1/1) quitando insomnia                             [##########################] 100%
> :: Ejecutando los «hooks» de posinstalación...
> (1/3) Updating icon theme caches...
> (2/3) Arming ConditionNeedsUpdate...
> (3/3) Updating the desktop file MIME type cache...

Ok, maybe is only that launching it whit "sudo" (I'm used to use  "sudo pacman -S package" to install something) causes it to fail.

> aurman -S insomnia                       4381ms
> 
> ~~ initializing aurman...
> ~~ calculating solutions...
> 
> :: The following 1 package(s) are getting installed:
>    aur/insomnia  /  ->  5.14.9-1
> ?? Do you want to continue? Y/n: 
> ~~ looking for new pkgbuilds and fetch them...
> cargando los paquetes...
> resolviendo dependencias...
> buscando conflictos entre paquetes...
> 
> Paquetes (1) insomnia-5.14.9-1
> 
> Tamaño total de la instalación:  178,23 MiB
> 
> :: ¿Continuar con la instalación? [S/n] 
> (1/1) comprobando las claves del depósito           [##########################] 100%
> (1/1) verificando la integridad de los paquetes     [##########################] 100%
> (1/1) cargando los archivos de los paquetes         [##########################] 100%
> (1/1) comprobando conflictos entre archivos         [##########################] 100%
> (1/1) comprobando el espacio disponible en el d...  [##########################] 100%
> :: Procesando los cambios de los paquetes...
> (1/1) instalando insomnia                           [##########################] 100%
> :: Ejecutando los «hooks» de posinstalación...
> (1/3) Updating icon theme caches...
> (2/3) Arming ConditionNeedsUpdate...
> (3/3) Updating the desktop file MIME type cache...

Yes, it was the problem. If running with "sudo" it fails but without it, will ask for sudo password like makepgk and works as espected.
Maybe we can code something to give a warning.

**Comment by polygamma** [comment]
https://github.com/polygamma/aurman/commit/17459142ac8df15a771386402e326b807f0f2e36

**Comment by paxet** [comment]
**Thanks!**

**Comment by polygamma** [comment]
You are welcome :)
