### ISSUE TITLE
Suppressing not_repo_not_aur_packages_list warning in config

### ISSUE THREAD

**Issue by Libbum** [polygamma/aurman#34]
I was wondering if there's any way to suppress the `not_repo_not_aur_packages_list` info for selected packages. I have a few `-dummy` packages installed for tools I manage outside of pacman, but provide targets for pacman to use. Telling me that these packages don't exist inside the usual repos each time aurman is run isn't helpful in this instance (although I do see the reason to provide this for other packages that have been dropped for whatever reason).

I attempted to use the `pacman.conf` `IgnorePkg` variable; both that and sending the packages directly to the `--ignore` flag didn't remove the warning.

**Comment by polygamma** [comment]
Will append a config option for that later today or tomorrow

**Comment by polygamma** [comment]
Done. see: https://github.com/polygamma/aurman/commit/ebb2683553b3c773150f0c98376dddea5fd151d5

**Comment by Libbum** [comment]
Amazing turn around. Thanks so much!

**Comment by polygamma** [comment]
Ah, for selected packages... Will change that later

**Comment by Libbum** [comment]
Sure, no problems.

**Comment by polygamma** [comment]
Done. see: https://github.com/polygamma/aurman/commit/8aaa83930f33a73cfd901f80b3f2a0301bd089e8

**Comment by Libbum** [comment]
Confirmed that this is working perfectly. Thanks again.

**Comment by polygamma** [comment]
You're welcome :)
