### ISSUE TITLE
Support pacman wrappers

### ISSUE THREAD

**Issue by Gustorn** [polygamma/aurman#37]
First of all, thanks for the great AUR helper! It would be really nice if `aurman` could support pacman wrappers: as it is right now, the call to `pacman` is hard-coded into `wrappers.py` (as far as I could tell).

Making this configurable by either an environmental variable (the pacaur way) or a config file (trizen/yay/etc. way) would allow the use of `powerpill` for example.

Edit: I'd also be happy to send a PR if you think it's a feature worth having but don't want to implement it yourself.

**Comment by polygamma** [comment]
Sorry, aurman is definitely only going to use pacman, nothing else.

**Comment by AladW** [comment]
Since `aurman` doesn't seem to hardcode the path to pacman, the usual trick should work:
```
mkdir ~/overrides
ln -s /usr/bin/powerpill overrides/pacman
PATH=~/overrides:$PATH aurman <args>
```

**Comment by Gustorn** [comment]
I do this for a few other binaries, I don't know why it never occured to me to do it with pacman. It works like a charm, thanks.
