### ISSUE TITLE
Enhancement request: Use $VISUAL for editing (if set) instead of $EDITOR

### ISSUE THREAD

**Issue by Taijian** [polygamma/aurman#39]
First of: Thank you for creating aurman, I think it is really a nifty tool and so far I enjoy using it very much!

One small idea that I had would be to allow usage of $VISUAL for editing PKGBUILDs instead of just $EDITOR, because I personally find a GUI editor to be much more comfortable than nano.

Thank you for considering this!

**Comment by polygamma** [comment]
Hey!

So: if $VISUAL use that, else if $EDITOR use that, else use nano?

**Comment by Taijian** [comment]
Yes, that's what I was thinking - if that can be implemented without too much trouble, that is.

**Comment by polygamma** [comment]
It's fine, going to implement it.

**Comment by Taijian** [comment]
Thank you!

**Comment by polygamma** [comment]
Done. see: https://github.com/polygamma/aurman/commit/feacfc6aab3281023df670be8a8c20f9eca21ad8

Let me know if it works as expected!
