### ISSUE TITLE
Streamline --devel source checkout and prompts

### ISSUE THREAD

**Issue by rmarquis** [polygamma/aurman#4]
Not a bug, but a possible improvement.
When updating with `$ python main.py -Su --devel --needed`, the checkout of the sources is done between the prompts. This could be streamlined by asking all prompt first, then doing the checkout of the sources.

The drawback is that it is not easily possible to retrieve the exact new version of the packages in case you want to display it to the user, but this is a minor annoyance especially when `--needed` is used.

**Comment by polygamma** [comment]
Yes, you are right. I am not happy with the behavior as well. Going to think about a nice order for the next rewrite.

**Comment by polygamma** [comment]
Done.
