### ISSUE TITLE
Support -Si to retrieve package information

### ISSUE THREAD

**Issue by Kxuan** [polygamma/aurman#40]
`-i` option is really useful to retrieve basic information of aur packages. 

Description in `pacman -S --help`
```
  -i, --info           view package information (-ii for extended information)
```

**Comment by polygamma** [comment]
You are right, nice to have, but currently I do not have the time for implementing that. Will be done, but no ETA.

**Comment by martynjy** [comment]
Yes, that will be a welcome addition when implemented.

**Comment by polygamma** [comment]
update: i'd implement this after the term of university is over, which would be around the beginning of july.
if one wants to have it earlier: feel free to implement it and open a pr. if one is unsure about where to put things, just ask, i'd answer those questions, but for implementing features i don't really have time

**Comment by polygamma** [comment]
has been implemented: https://github.com/polygamma/aurman/commit/c684b220ab9fe293d2d3b366287deb55fd8dd7bb

**Comment by seafox** [comment]
Great news, the only nitpick unix timestamps - would look best when converted to something more readable )

**Comment by polygamma** [comment]
You are right, going to implement that

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/1876973b446de7573ddf887d75e446ca03172d95 @seafox 

may you install `aurman-git` and check if it works as expected?

**Comment by seafox** [comment]
I think so, the only thing that perhaps can be added is the time zone notice (UTC or GMT), but official Arch page provides no mention, so I guess it's perfectly okay to skip any specifications as it defaults to UTC. Another completely optional thing is day of week that some helpers like pacaur and pikaur have. But I think it would invalidate ISO date format in that case, not sure about it though.

**Comment by Kxuan** [comment]
Thanks ploygamma~~

## About the timedate formating:
How about using `time.ctime`?
This format is setting by the user. And the user do know what is the best format for himself.

**Comment by seafox** [comment]
> EDIT: thinking further, day of week wouldn't bring much value as it would add it only when timestamp displayed in local time.

I wasn't thinking clearly. As far the consistency goes, the display of timestamp format within a single program should remain the same. So the AUR submitted and modified timestamps should match the official repo packages Build Date timestamps. Currently AUR package has ISO date format, official repos - different (aurman-git).

**Comment by polygamma** [comment]
@seafox - you may open a PR to change it properly, I am not interested in using `-Si` to be honest, hence I do not really care about those timestamps.

**Comment by polygamma** [comment]
@seafox, do you want to do that? I am currently preparing for a new release, and would wait for you to change the formatting

**Comment by seafox** [comment]
@polygamma 

Just replace main.py **line 273**:
```
-                value = datetime.utcfromtimestamp(value).strftime('%Y-%m-%d %H:%M:%S')
+                value = datetime.fromtimestamp(value).strftime('%a %d %b %Y %H:%M:%S')
```

Please do this for aurman non-git version too

**Comment by polygamma** [comment]
@seafox, that's not quite it, it differs still by e.g. not using am/pm, but as I wrote, I am not interested in getting this right. One should look into the sourcecode of `pacman` for that. So, if you want it, open a PR with references why what you did is actually correct, I am going to merge it then.

**Comment by seafox** [comment]
AFAIK there is no correct way to do that. As pacman does not take into account user's location and just shows AM/PM and TZ whether he used to those or not (
If you check other AUR helpers, except maybe pacaur, their timestamps aren't consistent.
No idea why pacman forces 12H AM/PM output with local timezone everywhere (useless info, especially when reiterated) for the rest of the world. Anyway, the suggested line replacement is IMHO better suited for local use than the current strictly UTC ISO format, but... you are the master.

**Comment by eli-schwartz** [comment]
> As pacman does not take into account user's location and just shows AM/PM and TZ whether he used to those or not

What? Programs in general don't include GPS for detecting your location... they have the user specify their own timezone...

**Comment by eli-schwartz** [comment]
It very specifically uses what the `strftime(3)` manpage refers to as:

>        %c     The preferred date and time representation for the current locale.

So you go right ahead and state the same falsehood I just explained in depth is untrue.

**Comment by seafox** [comment]
to be near en_US just like pacman shows the line 273 should have this:
`datetime.fromtimestamp(value).astimezone().strftime('%a %d %b %Y %I:%M:%S %p %Z')`

but if pacman locale uses LC_CTYPE setting, what python does?

**Comment by eli-schwartz** [comment]
It herps the derp and goes off to eat paste, because `%c` isn't what you'd expect from `strftime(3)`, the /usr/bin/date command, and general qualities of C programming. (Instead, of `%a %d %b %Y %I:%M:%S %p %Z` it uses `%a %b %e %H:%M:%S %Y`.)

But that has absolutely zero to do with pacman which is very much locale aware.

**Comment by seafox** [comment]
> So you go right ahead and state the same falsehood I just explained in depth is untrue.

Your "in-depth explanation" unfortunately didn't enlightened the general *nix issues with limited locale choices, language and country specific formatting, languages and translations, timezones and general inconsistency in console vs GUI/DM, practically everywhere (

**Comment by eli-schwartz** [comment]
I fail to see why any of that is aurman's responsibility...

**Comment by seafox** [comment]
> Instead, of %a %d %b %Y %I:%M:%S %p %Z it uses %a %b %e %H:%M:%S %Y .

Nope, pacman -Si doesn't use it. Here is the output sample for en_US:
Wed 06 Dec 2017 11:36:40 PM EST,
as you see, the date is before month, nether %e used (06 not " 6"), am/pm + tzinfo added. Where you got that?

**Comment by seafox** [comment]
@eli-schwartz 
`datetime.fromtimestamp(value).replace(tzinfo=tzlocal()).strftime('%c'))`
This is brilliant and works great, kudos!

**Comment by eli-schwartz** [comment]
But polygamma doesn't want additional dependencies not in the stdlib, so he asked me to implement https://github.com/eli-schwartz/aurman/commit/c22ddaa5a1e782f220a876f32c8af991e8fd77a9 instead.

**Comment by seafox** [comment]
> But polygamma doesn't want additional dependencies not in the stdlib, so he asked me to implement eli-schwartz/aurman@c22ddaa instead.
dirty hack indeed (

**Comment by polygamma** [comment]
the relevant commit has been cherrypicked

**Comment by seafox** [comment]
> the relevant commit has been cherrypicked

What benefits you are talking about?
Hope you'll reconsider implementing this hack as the professional programmers after reading this.

```
UTC ISO     s = datetime.utcfromtimestamp(value).strftime('%Y-%m-%d %H:%M:%S')
en_US       s = datetime.fromtimestamp(value).strftime('%a %d %b %Y %I:%M:%S %p')
Timezone    s = datetime.fromtimestamp(value).astimezone().strftime('%a %d %b %Y %H:%M:%S %p %Z')
Dateutil    s = datetime.fromtimestamp(value).replace(tzinfo=tzlocal()).strftime('%c')
Pipe hack   s = run(['date', '--date', '@%s' % value, '+%c'],  universal_newlines=True, stdout=PIPE).stdout.strip()


Python 3.6.6 (default, Jun 27 2018, 13:11:40) 
[GCC 8.1.1 20180531] on tp, Standard
>>> *nix   1528549820.776
UTC ISO      2018-06-09 13:10:20
UTC          Sat 09 Jun 2018 13:10:20
Local        Sat 09 Jun 2018 16:10:20

UTC ISO       100000  runs in (0:00:00.664845s) 2018-06-09 13:10:20
en_US         100000  runs in (0:00:00.709339s) Sat 09 Jun 2018 04:10:20 PM
Timezone      100000  runs in (0:00:01.489172s) Sat 09 Jun 2018 16:10:20 PM EEST
Dateutil      100000  runs in (0:00:04.477121s) Sat 09 Jun 2018 04:10:20 PM EEST
Pipe hack     100000  runs in (0:05:10.615276s) Sat 09 Jun 2018 04:10:20 PM EEST

for       loop  10000000  runs in (0:00:00.612731s)
while     loop  10000000  runs in (0:00:01.748878s)
```


Thus, **this dirty hack is 70 times (!) slower** than using dateutil extra package.
[__init__.py.txt](https://github.com/polygamma/aurman/files/2171408/__init__.py.txt)

**Comment by polygamma** [comment]
I do not want another dependency for -Si, that's it. Also: Who cares about it being 70x times slower? Does not matter, it's -Si. If you are not happy with that, feel free to fork aurman, maintain and use it afterwards

**Comment by polygamma** [comment]
I also never even wrote the word "benefits", maybe you should learn how to read?

**Comment by polygamma** [comment]
Anyway: I made my call, I chose the solution, that's it. I am not going to comment on this topic again, unless it's about a solution not needing a new dependency

**Comment by seafox** [comment]
> I also never even wrote the word "benefits", maybe you should learn how to read?

cherrypicked – definitions:
verb
selectively choose (the most beneficial items) from what is available.
_the company should buy the whole airline and not just cherry-pick its best assets_

**Comment by polygamma** [comment]
https://git-scm.com/docs/git-cherry-pick

**Comment by eli-schwartz** [comment]
@seafox, learn to git(hub).

Yeah, I'm out of this thread. There's nothing productive to get out of this anymore.

**Comment by seafox** [comment]
that translation was from big G. YMMV )
> I do not want another dependency just for -Si, that's it. Also: Who cares about it being 70x times slower? Does not matter, it's -Si. If you are not happy with that, feel free to fork aurman, maintain it in a way you want it to be and use it afterwards
Well, it's your call, your sanity. BTW nobody said you'll never need to replace such dirty hacks with a quality date processing code in the future.

**Comment by polygamma** [comment]
I banned @seafox from this repository

**Comment by AladW** [comment]
>invoking a standard UNIX utility with a [46 year](https://en.wikipedia.org/wiki/List_of_Unix_commands#List) (!) track-record is a dirty hack

Note how "professional programmers" are familiar with the concept of [premature optimization](http://wiki.c2.com/?PrematureOptimization). When you're going to run `date` 1 or 2 times, pulling in yet another python lib that might break is exactly that.
