### ISSUE TITLE
Make it available for other architectures 

### ISSUE THREAD

**Issue by balliegojr** [polygamma/aurman#41]
Change PKGBUILD to allow building in other architectures, like armv6h

**Comment by polygamma** [comment]
Going to change it to `any`.

**Comment by Taijian** [comment]
Was just going to request that you add armv7h... But any should be good, I don't think there is anything architecture-specific in aurman...

**Comment by polygamma** [comment]
Done.

**Comment by balliegojr** [comment]
Thank you!
