### ISSUE TITLE
Add a newline before the 'Y/n user prompt'

### ISSUE THREAD

**Issue by khoacao96** [polygamma/aurman#43]
I PM'd you on Reddit before but I'll just do it here again in case you didn't see it (sorry for bugging you with minor stuff...)

As you can see in [this image of pacman](https://i.imgur.com/V6rGjcu.png), there's an empty line separation between the whole 'package' part and the 'Y/n user prompt' line. Whereas for [aurman in this image](https://i.imgur.com/pK9pBfE.png), the 'package' parts are separated pretty nicely, but the 'Y/n user prompt' line is not separated from the 'package' parts at all. An empty line before the user prompt line would make the output look much better.

**Comment by polygamma** [comment]
Will be changed with one of the coming updates

**Comment by polygamma** [comment]
Done.
