### ISSUE TITLE
unable to run as user without prompting for sudo password

### ISSUE THREAD

**Issue by CNG** [polygamma/aurman#45]
Hello,

I am unable to get `aurman` to run as my special `aur_builder` user without prompting for sudo password. 

```
$ sudo -i -u aur_builder
[sudo] password for cgorichanaz: 
[aur_builder@CharlieDesktop18 ~]$ aurman -S --noconfirm --noedit --needed bash-completion
~~ initializing aurman...
~~ calculating solutions...

:: The following 1 package(s) are getting installed:
   extra/bash-completion  /  ->  2.8-1
~~ looking for new pkgbuilds and fetch them...
[sudo] password for aur_builder: 
```

`yaourt` works as expected:

```
[aur_builder@CharlieDesktop18 ~]$ yaourt -S --noconfirm --needed bash-completion
resolving dependencies...
looking for conflicting packages...

Packages (1) bash-completion-2.8-1

Total Installed Size:  0.78 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) installing bash-completion                   [######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[aur_builder@CharlieDesktop18 ~]$ 
```

**`/etc/sudoers`**: 

```
## Ansible managed
##
## User privilege specification
##
root ALL=(ALL) ALL

%wheel ALL=(ALL) ALL
%wheel ALL=(ALL) NOPASSWD:/usr/bin/openvpn*

Defaults timestamp_timeout=1440

#includedir /etc/sudoers.d
```

**`/etc/sudoers.d/11-install-aur_builder`**:

```
aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman
```

Note this issue still occurs with that last line set instead to `aur_builder ALL=(ALL) NOPASSWD: ALL`. I am not sure if I am missing something, as I would not expect to be prompted for the password at all with that setting.

If I go ahead and create a password for the user and then type the password at the prompt, the last few lines of output of `sudo journalctl _COMM=sudo | grep aur_builder | tail` are:

```
Mar 25 18:24:40 CharlieDesktop18 sudo[26064]: aur_builder : TTY=pts/0 ; PWD=/home/aur_builder ; USER=root ; COMMAND=validate
Mar 25 18:24:40 CharlieDesktop18 sudo[30424]: aur_builder : TTY=pts/0 ; PWD=/home/aur_builder ; USER=root ; COMMAND=/usr/bin/pacman --sync bash-completion --noconfirm --needed --asdeps
Mar 25 18:24:40 CharlieDesktop18 sudo[30452]: aur_builder : TTY=pts/0 ; PWD=/home/aur_builder ; USER=root ; COMMAND=/usr/bin/pacman -D --asexplicit bash-completion
```

I hoped to find it was calling some other program I needed to allow in the sudoers file, though that would not explain the `NOPASSWD: ALL` not working. I am not sure what `COMMAND=validate` is.

**Comment by polygamma** [comment]
Hey!

`aurman` is running `sudo -v` to aquire sudo privileges, which should be the `validate` command.
`aurman` does not check for specific privileges, hence your "first" attempt cannot work currently.

But setting `aur_builder ALL=(ALL) NOPASSWD: ALL` should work, since I am doing exactly that in my docker tests.
see: https://github.com/polygamma/aurman/blob/master/Dockerfile#L6

**Comment by AladW** [comment]
Surely a builder account that only whitelists pacman is more suitable than one which must blindly whitelist all commands...

**Comment by polygamma** [comment]
@AladW You are right, but I know no way of determining if sudo privs for `pacman` are available without `sudo -l` which requires a password. Hence it would lead to a password prompt again, and thus would not change anything relevant.

**Comment by polygamma** [comment]
Added a config option to not use the sudo loop. see: https://github.com/polygamma/aurman/commit/e6a77324f7562193d97c6aa0c21e22d4c4e12ffa

**Comment by CNG** [comment]
Thanks for looking at this. Based on a quick test, I think the issue is resolved when I run `aurman` as above. Strangely I am still seeing the same behavior when triggering via Ansible using the https://github.com/kewlfft/ansible-aur plugin (but modified to use `aurman`). I will need to investigate more, but have worked around for now by commenting out `acquire_sudo()` in `main.py`.
