### ISSUE TITLE
No option to bypass 'multiple providers' prompt

### ISSUE THREAD

**Issue by CNG** [polygamma/aurman#46]
I am able to install `vim` by script using `pacman -S --noconfirm --noedit --needed vim` but cannot do something similar with `aurman`:

```
$ aurman -S --noconfirm --noedit --needed vim
~~ initializing aurman...
:: We found multiple providers for vim
Choose one by entering the corresponding number.
Number 1: extra/vim
Number 2: extra/gvim
?? Enter the number: 
```

Is there a way I can instruct `aurman` to automatically select the package with the exact name given?

**Comment by polygamma** [comment]
Not yet, but I am going to think of a nice solution and will implement it during the next days.

I will let you know in this issue, when I have done so.

**Comment by polygamma** [comment]
Done. see: https://github.com/polygamma/aurman/commit/0bbe28f9bfd26a1231e4ed8235e21ffc57ab21c0

**Comment by CNG** [comment]
This works now, thank you!
