### ISSUE TITLE
Support aur/ prefix

### ISSUE THREAD

**Issue by ypnos** [polygamma/aurman#48]
Currently, I cannot do this:

    aurman -S aur/ttf-impallari-cabin-font

This is unexpected and unconvenient, aurman provides lists of packages in this format:

    …
       aur/ttf-impallari-cabin-font        1.5-1                   ->  2.2-1
    …

Being able to specify AUR explicitely as a package source is sometimes necessary. For example, when using a third-party repository that contains AUR packages. In some cases, it is desired to not use the packaged version but compile the package on the target machine.

**Comment by polygamma** [comment]
Read the README, please.

**Comment by ypnos** [comment]
After reading the README _again_ I realized I can use --aur option. It is still inconvenient that I cannot use (c&p) the very same notation that aurman is using, and all other AUR helpers that I know support.

I kindly suggest this as a feature request.

**Comment by polygamma** [comment]
It has nothing to do with `--aur`. Read the section about the aurman config.

**Comment by polygamma** [comment]
Relevant discussion: https://github.com/polygamma/aurman/issues/23
