### ISSUE TITLE
`noedit` in config file

### ISSUE THREAD

**Issue by AlexWayfer** [polygamma/aurman#49]
Hello!

Thank you for `aurman`.

I don't want to edit some AUR-files, but I have to use option `--noedit` almost for every command: `-Syu`, `-S`, `-S --needed`, etc.

It would be nice to have `noedit` in config file (`[miscellaneous]` section), once and for all.

Thank you.

**Comment by polygamma** [comment]
Not going to implement that, because noedit is something one should almost never use. if you want to have something like that, just create an alias

**Comment by AlexWayfer** [comment]
> because noedit is something one should almost never use.

For you? Maybe. For other people? Arguably. You can just not use this config option, and set `false` (`no`) as default.

> if you want to have something like that, just create an alias

Many aliases (3 at least) instead of 1 word in one place. :weary:

**Comment by polygamma** [comment]
I am putting options into the config, which are useful as persistent options in my opinion. noedit is not, hence I won't put that into the config.

**Comment by AlexWayfer** [comment]
> which are useful as persistent options in my opinion

It's sad that you're thinking only about yourself… Okay.

**Comment by polygamma** [comment]
aurman is open source and under the MIT license. feel free to fork it and add that to the config by yourself and use the fork.

**Comment by AlexWayfer** [comment]
> aurman is open source and under the MIT license. feel free to fork it and add that to the config by yourself and use the fork.

I know, thank you. But:
1. I don't know Python and `pacman` very well. I can learn it, OK.
2. It's less comfortable: update fork, publish package, etc. …

But I understood you, yes. Your attitude upsets me, but it's your right.

Anyway, thank you for open source, MIT license and feedback.

**Comment by n4nn31355** [comment]
> I know, thank you. But:
    I don't know Python and pacman very well. I can learn it, OK.
    It's less comfortable: update fork, publish package, etc. …


I have the perfect solution for you - use ubuntu.

**Comment by AlexWayfer** [comment]
> I have the perfect solution for you - use ubuntu.

I used it for a long time. I don't like stale versions of software and PPA system.

I like Arch and AUR, and I'm looking for a new AUR-helper after `pacaur` ceased to be supported.

**Comment by polygamma** [comment]
https://github.com/actionless/pikaur may be something for you. The dev seems to implement almost every wish of the users.

**Comment by AlexWayfer** [comment]
> https://github.com/actionless/pikaur may be something for you. The dev seems to implement almost every wish of the users.

Yes. But `pikaur` is "partially" `pacman`-wrapper, and, I think, it has some fundamental problems caused by this.

**Comment by polygamma** [comment]
as far as i know, the dev is working on that. so you should definitely have an eye on his helper.

**Comment by AlexWayfer** [comment]
> as far as i know, the dev is working on that. so you should definitely have an eye on his helper.

Yes, I have, thank you. I used it before `aurman` and I've reported some issues.
