### ISSUE TITLE
Case and duplicate issues with no_notification_unknown_packages

### ISSUE THREAD

**Issue by MarcRdC** [polygamma/aurman#50]
I tried to disable the notifications for a package that contains mixed case in its name: however I type the name (with or without the uppercase characters), it has no effect and the notifications are still shown. Moreover, `aurman` throws an error when a package is listed several times; maybe it should just ignore the duplicates.

**Comment by polygamma** [comment]
May you give a concrete example, please?

**Comment by MarcRdC** [comment]
Here is a dummy PKGBUILD file for a package named `Test`:
```
pkgname=TesT
pkgver=1
pkgrel=1
pkgdesc="Just a test"
url=""
depends=()
optdepends=()
license=('GPL3')
arch=('any')
source=()
sha256sums=()

package() {
  cd "$pkgdir"
  mkdir -p opt/TesT
  cd "$pkgdir/opt/TesT"
  echo "Just a test!" > test
}
```

Whatever — `TesT` or `test` — I type in the `[no_notification_unknown_packages]` section of the `aurman_config` file, the notification is shown. Moreover, if `TesT` and `test` are present, the following error is thrown:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 517, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 27, in process
    read_config()  # read config - available via AurmanConfig.aurman_config
  File "/usr/lib/python3.6/site-packages/aurman/parsing_config.py", line 38, in read_config
    config.read(config_file)
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1092, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/home/XXX/.config/aurman/aurman_config' [line 11]: option 'test' in section 'no_notification_unknown_packages' already exists
```

**Comment by polygamma** [comment]
May you check if the problem persists with the new aurman version?

**Comment by MarcRdC** [comment]
No more error. The notification is not shown anymore for `TesT` but is still displayed for `TEst`.

**Comment by polygamma** [comment]
Well, in that case the error is perfectly fine.
