### ISSUE TITLE
Hide aurman's own tracebacks

### ISSUE THREAD

**Issue by anntzer** [polygamma/aurman#55]
It would be nice if aurman's own tracebacks (corresponding to error situations known to aurman) were hidden (e.g. be making own_exception's exceptions subclass a base AurmanException, and wrapping the main() entry point in a try... except AurmanException).  The idea here is that the end user should not see these tracebacks (but just the error message), as they are after all due to situations that aurman actually knows about.

On the other hand it is up to you whether to display tracebacks associated with "unknown" exceptions (they may help end users report more meaningful bugs to you), which ideally should not occur :)

**Comment by polygamma** [comment]
I want to see those tracebacks, they are useful
