### ISSUE TITLE
Invalid upgrade path(?)

### ISSUE THREAD

**Issue by anntzer** [polygamma/aurman#57]
I am getting the following upgrade path (found only by deep_search):
```
~~ calculating solutions...

:: The following 1 package(s) are getting installed:
   aur/isl                 /                 ->  0.19-1

:: The following 2 package(s) are getting updated:
   aur/cloog               0.18.5-5          ->  0.19.0-1
   aur/osl                 0.9.2-1           ->  0.9.2-2

:: The following 1 package(s) are getting removed:
   aur/gcc47               4.7.4-2           ->  /
:: Dependency cloog of package gcc47 is not fulfilled

~~ The following will be done:
:: You are using --deep_search, hence --needed is active.
:: That means packages to be reinstalled will not actually be reinstalled.
   Reinstall : bash, filesystem, gcc-libs, glibc, gmp, iana-etc, linux-api-headers, ncurses, readline, tzdata
   Upgrade   : osl
   Remove    : cloog
   Install   : isl
   Remove    : gcc47
   Install   : cloog
```
(aurman 2.9.20-1).

Right now I have gcc47 explicitly installed, cloog and osl installed as deps of gcc47, and isl not installed.  So the proposed solution completely defeats my purpose of, well having gcc47 installed :-)

Also, manual inspection of the PKGBUILDs does not explain to me why the proper solution (install isl & upgrade osl & cloog?) is not found:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gcc47&id=36678c6c82cd55450f6b96c9ce7cdcb38976d89b
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cloog&id=b4b7e9983996fd7d1c7cabea3979db7b91e0b3e6
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=osl&id=c964012b5498adea554eca3887b4fb6fe8df50e2
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=isl&id=fb371e6184b6fd5c5aae7079de5c693a5ba6413e

**Comment by polygamma** [comment]
--holdpkg is for cases like that

**Comment by anntzer** [comment]
I... don't actually understand why aurman even wants to remove gcc47, to be honest.  (In other words, I don't understand what was the actual point I was supposed to be "aware of".)

The bug is not with dependency solving (well perhaps it is, but as a user what I care about is the syndrome, not the root).  The bug is that I had an explicitly installed package (--asexplicit) and there is a perfectly valid upgrade route for its dependencies (i.e. there exists a valid state where that package and all its dependencies are at their latest version, with no conflicts), and aurman does not apply that route but instead suggests removing the only package I care about in order to upgrade dependencies that I don't actually care about.

**Comment by polygamma** [comment]
aurman does not try to remove anything, but that is what happens when aurman would use that solution, since for a "short moment" the needed dep is unfulfilled, hence the package gets uninstalled. caring about all installed packages for every solution finding is unneeded overhead, since situations like this almost never arise. and for these rare cases there is --holdpkg, so i really do not see the need to change anything. all in all this is a helper, the user still needs to check the solutions etc. and that is fine. for these situations exist --solution_way, --deep_search, --holdpkg

**Comment by polygamma** [comment]
by the way: your proposed solution is not valid, since the installed cloog package conflicts with isl, hence you may not install isl first, you really need to remove cloog first

**Comment by anntzer** [comment]
So let's try, as you suggest,
```
aurman -Syu --deep_search --solution_way --holdpkg gcc47
```
I get
```
~~ The following will be done:
:: You are using --deep_search, hence --needed is active.
:: That means packages to be reinstalled will not actually be reinstalled.
   Reinstall : bash, filesystem, gcc-libs, glibc, gmp, iana-etc, linux-api-headers, ncurses, ppl, readline, tcl, tzdata, zlib
   Install   : dejagnu, expect
   Remove    : cloog
   Install   : isl
   Remove    : gcc47
   Upgrade   : osl
   Install   : cloog
   Reinstall : binutils, libmpc, mpfr
   Install   : gcc47
```
... so I'm supposed to rebuild gcc47 (well, it's not in my build cache since that was built years ago, and I had no plans to uninstall/reinstall it)? Do you know how much time this takes? :-)

> dep solving finds a perfectly valid solution for the assumptions aurman has

Let's just agree to disagree as to what "perfectly valid solution" means (when the task of a package manager is (AFAICT) actually to manage a list of packages desired ("--asexplicit") by the user).  I don't think any of the packages here did anything weird, cloog used to vendor its own isl (due to version mismatches) and therefore conflicted with AUR's isl; now it doesn't and depends on AUR's isl, it's not as if this was a ridiculous edge case.

In any case it's your project and thus your call, we're all just trying to get the best AUR helper out there.

**Comment by polygamma** [comment]
Well, what solution would you suggest which does not require removing and reinstalling gcc47? do not forget that your installed cloog conflicts with isl.

**Comment by anntzer** [comment]
I see, you are trying very hard to avoid pacman -Ud/-Rd (which is reasonable).  But note that *even pacman itself* will sometimes temporarily put the package list in an invalid state (specifically, a missing dependency -- that's the infamous "dependency cycle detected: FOO will be installed before its BAR dependency"; of course conflicts are still a no-no).
IMO (but you may obviously disagree) it is for the same reason OK for an AUR helper to generate a temporarily invalid state, as long as it is resolved before the process ends (what if the AUR helper crashes? well pacman can crash too).
So I would do what everyone would do in this situation, i.e. remove cloog (ignoring gcc47's complaints), install {isl,osl}, install cloog.

**Comment by polygamma** [comment]
Exactly, aurman is not doing anything like that, and I am really, really not touching those things. the computer crashes, a package cannot be built, or whatever, could lead to staying in such state, which is not acceptable for me. hence aurman will never find such solutions.

**Comment by anntzer** [comment]
You realize that nothing in pacman (or most common package managers, in fact) is truly atomic anyways?  If your laptop battery dies in the middle of pacman -U glibc (while half of the files have been updated and the other half hasn't), then you're just as dead (if not more) than if it dies in the middle of aurman doing its stuff.  Some relevant links:
https://bbs.archlinux.org/viewtopic.php?pid=1320100#p1320100
https://unix.stackexchange.com/questions/130815/how-is-yum-atomicity-ensured

**Comment by polygamma** [comment]
sure, but i do not want to add more points which could possibly fail. i think the user needs to handle those cases manually, or use a helper which supports those, but aurman will not be one of them

**Comment by anntzer** [comment]
Sure.  In any case, thanks for entertaining the discussion.

**Comment by anntzer** [comment]
Actually, I guess I have to take back what I said: there actually exists a valid upgrade path.  This can be achieved by
1) download isl, build it
2) download cloog, build it
3) install both packages in a single invocation of pacman:
```
$ sudo pacman -U --asdeps cloog/cloog-0.19.0-1-x86_64.pkg.tar.xz isl/isl-0.13-1-x86_64.pkg.tar.xz
loading packages...
resolving dependencies...
looking for conflicting packages...

Package (2)  Old Version  New Version  Net Change

cloog        0.18.5-5     0.19.0-1      -1,63 MiB
isl                       0.13-1         1,51 MiB

Total Installed Size:   2,04 MiB
Net Upgrade Size:      -0,12 MiB

:: Proceed with installation? [Y/n] 
(2/2) checking keys in keyring                            [###############################] 100%
(2/2) checking package integrity                          [###############################] 100%
(2/2) loading package files                               [###############################] 100%
(2/2) checking for file conflicts                         [###############################] 100%
(2/2) checking available disk space                       [###############################] 100%
:: Processing package changes...
(1/2) installing isl                                      [###############################] 100%
(2/2) upgrading cloog                                     [###############################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```
This doesn't trigger *any* warning from pacman, which treats this as a completely normal install.

**Comment by polygamma** [comment]
another thing which is not supported, hence aurman will never find such solutions. and it is intended, too. much overhead, makes solution finding more complicated for rare useful cases, so not going to be supported
