### ISSUE TITLE
Option to sort AUR package search results

### ISSUE THREAD

**Issue by btd1337** [polygamma/aurman#58]
This is a feature request. 

```
sort_by    => "name",      # valid values: "name", "votes", "popularity" and "date"
sort_order => "ascending", # valid values: "ascending" or "descending"
```

When I search a package, the results listed could be sorted by popularity. The same could be configured to be sorted by number of votes, package name, date the package was last updated, and so on.

**Comment by polygamma** [comment]
will be implemented, but no ETA

**Comment by btd1337** [comment]
Is currently possible sort searches via aurman_config?

**Comment by polygamma** [comment]
no

**Comment by polygamma** [comment]
update: i'd implement this after the term of university is over, which would be around the beginning of july.
if one wants to have it earlier: feel free to implement it and open a pr. if one is unsure about where to put things, just ask, i'd answer those questions, but for implementing features i don't really have time

**Comment by polygamma** [comment]
Has been implemented: https://github.com/polygamma/aurman/commit/2e86d2b3af9f23d57c215d1b2433930b3221148f
