### ISSUE TITLE
aurman clean ( -Sc ) with --noconfirm option should skip clones and untracked git questions

### ISSUE THREAD

**Issue by frealgagu** [polygamma/aurman#60]
Executing aurman with sync clean and noconfirm options should skip the following questions:

# aurman --sync --clean --noconfirm
?? Do you want to remove all uninstalled clones from cache? N/y:
?? Do you want to remove all untracked git files from cache? (even from installed packages) N/y:

The last question should no be done, pacman -Sc cleans the cache for non installed packages and -Scc cleans the entire cache regardless it has installed packages or not

**Comment by polygamma** [comment]
Will be implemented

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/0883a0ddab4dda8c427c3975d21bee18424cd363

**Comment by frealgagu** [comment]
Excellent, thanks a lot.
