### ISSUE TITLE
Files are not sourced in upgrading

### ISSUE THREAD

**Issue by frealgagu** [polygamma/aurman#61]
I'm upgrading using 
`aurman --sync --refresh --refresh --sysupgrade --verbose --show_changes --aur`
but the package aur/oracle-sqldeveloper which is upgrading from version 17.4.1.054.0712-1 to version 18.1.0.095.1630-1 has no option to neither show changes of files nor edit the PKGBUILD. That is a security issue there is a change I don't want or a malintentioned script is there.

Using 
`aurman --sync --refresh --refresh --sysupgrade --verbose --aur` 
behaves exactly the same.

**Comment by polygamma** [comment]
sorry, i cannot help you with that less Information. never heard of that before, i guess the error is on your side, not on the side of aurman. please post the full output of aurman and which sha hash is being saved for the package you mentioned. you find the hash here: aurmancachedir/yourpackagename/.git/aurman/.last_commit

**Comment by frealgagu** [comment]
It was my misunderstanding of how aurman worked, I thought that passing the show_changes it allow me to show/edit the files, but once it was confirmed that I didn't want to edit them I couldn't edit them anymore. Thanks to the recently added flag - - always-edit I'm able to edit them even if I had accepted the changes. Thanks for your continuous effort improving this application.
