### ISSUE TITLE
Feature Request: Customizepkg

### ISSUE THREAD

**Issue by stefanhusmann** [polygamma/aurman#62]
What about supporting customizepkg?

It is a nice tool to let you automtize changing PKGBUILDs on the fly. It is usefull for some circumstance, e.g. if you want another download mirror as the AUR default provides ore change default configure options.

In fact there are several flavours of customizepkg in the AUR, but they all use the same interface to the user or to aur helpers.

**Comment by polygamma** [comment]
sorry, that's something which is going to be used by almost nobody, hence i won't support that.
