### ISSUE TITLE
It should be an option to always show/edit files (even if previously it has been accepted)

### ISSUE THREAD

**Issue by frealgagu** [polygamma/aurman#64]
If I've download a package for installation/upgrade and accepted the changes but because an error (invalid hash or any other) or because I've chosen not to install and later I want to install it again, it should be a way to look the files and modifying them.

Currently there is a file in .git/aurman which contain the last accepted commit hash, but once that file exists, there are no option to look the files again. I need to manually remove it or use aurman -Sc, but if an upgrade is required (having the package already installed), that file is not removed with -Sc and I can't edit those files.

Thanks in advance.

**Comment by frealgagu** [comment]
Maybe put the option of show changes in the menu and add a parameter like --always_edit ?

**Comment by polygamma** [comment]
I do not see why this should be an aurman thing. If those files exist, and you want to edit them - just edit them?

**Comment by frealgagu** [comment]
It's because at the beginning, it's no clear where those files are. Currently there is  parameter - - show_changes, but only works the first time, once I've seen the changes I can't see them anymore.

If an error occurs because an invalid sha in the sources or packages which need be download by hand (like oracle-sqldeveloper), I have no option to edit the files if I've accepted don't edit them the first time.

**Comment by frealgagu** [comment]
It's like don't to have a cancel button because I don't code for cowards XD.

But, that option would be particularly useful for cvs packages using the - - devel option, because the files doesn't change but the tracked git does.

**Comment by polygamma** [comment]
You may just manually edit them in the file system. they are in the aurman cache folder

**Comment by frealgagu** [comment]
I could donwload them and install the by hand, but the idea of an AUR helper it to avoid I have to do this manually. I like this AUR helper, and I could do a pull request with the changes, but I need your approval first to avoid waste time doing it.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/fd312647fc7236e62f22983ce58fbfb63253c9f8

**Comment by frealgagu** [comment]
You're wonderful, thanks a lot.

**Comment by polygamma** [comment]
You're welcome :)
