### ISSUE TITLE
Allow changing the default for view changes prompt

### ISSUE THREAD

**Issue by jplatte** [polygamma/aurman#72]
I'd like to always look at package diffs, and I'm used just pressing Enter with `pacaur` (because it defaults to view changes => yes). It would be nice if aurman could adopt `pacaur`s default, or make it configurable (either a config option for always viewing the diff or for making it `Y/n` instead of `y/N`). Thank you for aurman! :)

**Comment by polygamma** [comment]
Have you read the readme of aurman?

**Comment by jplatte** [comment]
Yes, I have. Are you saying that I should always supply the `--show_changes` argument, or is there a way of setting the same thing in the config that I've missed?

**Comment by polygamma** [comment]
bash alias, maybe?

**Comment by jplatte** [comment]
Yeah, I guess that should work.
