### ISSUE TITLE
Getting sometimes TypeError when using regex for searching

### ISSUE THREAD

**Issue by hubitor** [polygamma/aurman#75]
## Description
Sometimes I see a **TypeError** if use caret (^) and/or dollar ($) for searching.

## Expected Behavior
Output no error - inform user if he did something wrong.

## Current Behavior
Outputs error:
`TypeError: expected string or buffer`

## Possible Solution
No idea...

## Steps to Reproduce
Run:
$ aurman -Ss top$
or
$ aurman -Ss ^vim$

> **Notice**: If you do not fill out one of the fields, without mentioning **why** you left it out, the issue will be closed without any comment.

**Comment by polygamma** [comment]
You have to use quotes, e. g. aurman -Ss "^vim$". does that fix the problem?

**Comment by hubitor** [comment]
No. I have tried already single and double quotes. The error remains.

**Comment by polygamma** [comment]
I am going to investigate tomorrow, I am currently not at home. thanks for reporting!

**Comment by polygamma** [comment]
i know what the problem is, will be fixed

**Comment by polygamma** [comment]
may you try it out with the new aurman version?

**Comment by hubitor** [comment]
thanks for the quick fix! Just tried it out with the new version and I don't see any error!
