### ISSUE TITLE
Pass update/install to root when sudo's unavailable

### ISSUE THREAD

**Issue by KorvinSilver** [polygamma/aurman#78]
I noticed that if I'm running aurman as a user who doesn't have sudo access, it throws this exception when it needs root privileges: `aurman.own_exceptions.InvalidInput: acquire sudo failed`

Would it be possible if in this case it just asked for the root password instead of crashing, or at least add a non-default option that can do that?

**Comment by polygamma** [comment]
You may disable the sudo loop via the config, does that fix the problem?

**Comment by polygamma** [comment]
Addition: If that's not what you want, be more concrete about what **exactly** you want, please.
I don't know why `aurman` should ever ask for the root password, I'd never, ever implement that.
Why don't you run `aurman` under a user with the needed permissions in the first place?

**Comment by KorvinSilver** [comment]
What's a sudo loop?  
Anyhow, what I mean is that when aurman performs an action that requires sudo, it tries to call it and if it fails, it fails. But I often set up virtual systems and I don't have sudo. I know it might be a marginal case since most people prefer sudo over a root user, but I've seen AUR helpers that when they can't call sudo, they ask for the root password and perform whatever they needed sudo for as root instead. Yaourt does that for example.

**Comment by polygamma** [comment]
I wont support that, sorry. the sudo loop runs in a separate thread and calls "sudo -v" in that thread so you only have to enter your password once. you may disable that in the aurman config

**Comment by KorvinSilver** [comment]
Ok.

**Comment by frealgagu** [comment]
makepkg as root is disallowed and no longer supported

http://allanmcrae.com/2015/01/replacing-makepkg-asroot/

It could be done via nobody user, but it still continues being a problem. In general you shouldn't run scripts as root. If you need it for running in virtual systems with automated scripts you should to either avoid use AUR helpers or configure properly users to that scripts.

**Comment by shiba89** [comment]
Makepkg itself supports this:
```
[shiba@Inspiron-910 aurman]$ LANG=en_US.UTF-8 makepkg -i
==> WARNING: Cannot find the sudo binary. Will use su to acquire root privileges.
==> WARNING: A package has already been built, installing existing package...
==> Installing package aurman with pacman -U...
Password: 
```

**Comment by eli-schwartz** [comment]
That's not even the same thing at all.

If the sudo program is installed but your user does not have sudo permissions, makepkg won't offer to use su instead.

**Comment by shiba89** [comment]
Well it's actually more in topic with this issue title (sudo unavailable) rather than what's been written up to now. Should I open another issue?

**Comment by shiba89** [comment]
Ok thanks, I'll look for something else.

**Comment by eli-schwartz** [comment]
makepkg in general has workarounds for su instead of sudo.

makepkg on Arch Linux, has a mandatory requirement on base-devel, and that includes sudo.

aurman requires makepkg requires base-devel requires sudo.

...

This issue does not have a misleading title. You cannot just read a title and listen to two words and draw random conclusions -- therefore this issue is correctly discussing the case where sudo permissions is not available to the calling user, and this use case has been rejected.
