### ISSUE TITLE
aurman command not found after install

### ISSUE THREAD

**Issue by Starkiller4011** [polygamma/aurman#79]
## Description
After installing, trying to use command aurman results in command not found error

## Expected Behavior
should run aurman commands

## Steps to Reproduce
1. cd ~/Downloads
2. git clone https://aur.archlinux.org/aurman.git
3. cd aurman
4. makepkg -Acs
5. aurman -Syu
6. bash: aurman : command not found

**Comment by Starkiller4011** [comment]
Please disregard, me bing an idiot, forgot to actually install the package after building.... For anyone new to Arch that stumbles across this, the following steps get you a working installed aurman:
1) git clone https://aur.archlinux.org/aurman.git
2) cd aurman
3) makepkg -Acsi
4) cd .. && rm -Rvf aurman

**Comment by frealgagu** [comment]
You've forgotten to install the tar.xz
sudo pacman -U aurman-*.pkg.tar.xz

Or you can achieve it with makepkg as follow

makepkg -Acsi
