### ISSUE TITLE
Don't remove packages if I don't ask for it

### ISSUE THREAD

**Issue by davispuh** [polygamma/aurman#80]
## Description

It shouldn't remove packages when installing or updating.

## Expected Behavior

Not to remove a package

## Current Behavior

It wants to remove a package

## Possible Solution

Just don't remove package if I didn't asked it to.

## Steps to Reproduce

1. Install package with broken dependencies.
2. Try to install new unrelated package

```bash
$ aurman -S aurman
~~ initializing aurman...
~~ calculating solutions...

:: The following 1 package(s) are getting reinstalled:
   aur/aurman         2.9.24-1  ->  2.9.24-1

:: The following 1 package(s) are getting removed:
   aur/electrum-dash  2.6.4-2   ->  /
:: Dependency python2-jsonrpclib of package electrum-dash is not fulfilled
```

**Comment by polygamma** [comment]
Read the readme

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/86c2b7a0c0a69f4877338c670a2d4285f9dee284

**Comment by davispuh** [comment]
I still don't understand. Why it says that package will be removed if I'm installing totally different unrelated package which has nothing to do with that other package.

**Comment by polygamma** [comment]
The reason is being printed.

**Comment by polygamma** [comment]
If you need more details: Read the wiki article about the dependency solving of aurman https://github.com/polygamma/aurman/wiki/Description-of-the-aurman-dependency-solving
