### ISSUE TITLE
Auto-clear cache after every successful build and install

### ISSUE THREAD

**Issue by KorvinSilver** [polygamma/aurman#81]
Currently the cache at `~/.cache/aurman` can be cleared only manually by the native pacman option `--clear` _(or manually by removing each unneeded directory, but if I do that while aurman's running, it breaks the next process even though it has nothing to do with the directories I removed)_, which is not the best thing if you have limited space and you also have multiple packages from AUR that each needs that space to build.

Aurman should automatically delete, or have an option to automatically delete, every file from its cache after it's not needed anymore, i.e. after the AUR package needing those files is successfully built and installed, so it won't make the next big build process fail due to running out of free space.

**Comment by polygamma** [comment]
Nope sorry, you may just install the packages one by one and clear the cache after each installation

**Comment by polygamma** [comment]
Addition: This is really a rare case, hence I do not want to support that natively via aurman
