### ISSUE TITLE
Does not correctly detect package version.

### ISSUE THREAD

**Issue by Edu4rdSHL** [polygamma/aurman#82]
## Description
If you modify a PKGBUILD (including the $version variable) aurman always show only the latest package version as installed and don't recognize your changes.

## Expected Behavior
Aurman detect the correct new package version.

## Current Behavior
Aurman tell the latest package version in AUR as installed.

## Possible Solution
I dont know.

## Steps to Reproduce

1. Edit the PKGBUILD of any AUR package bumping to a newer version and finish the install.
2. Do: aurman -Ss $AUR-PACKAGE-INSTALLED 
3. Do: pacman -Qi $AUR-PACKAGE-INSTALLED
4. Compare the results, aurman doesnt show the correct AUR package version.

**Comment by polygamma** [comment]
-Ss only shows, if a package is installed or not. It does never list any version, hence I am not sure what you mean

**Comment by Edu4rdSHL** [comment]
-Ss normally search in the package database and provide info how what's the latest version of a package and what's the function of that package. That isn't good that an AUR helper say that X package is installed with a version that is not.

**Comment by polygamma** [comment]
Sorry, I still do not know what exactly you want

**Comment by polygamma** [comment]
Closing this for now, please be more concrete about what exactly you want, if this really is an issue for you

**Comment by leomao** [comment]
I think @Edu4rdSHL means that if the installed version is not the same as the version in the database,
`pacman -Ss` will also show the the installed version. For example, since I modified the PKGBUILD of mosh and installed it, `pacman -Ss mosh` shows
```
community/mosh 1.3.2-3 [installed: 1.3.2.r58.gd4ce0d4-1]
    Mobile shell, surviving disconnects with local echo and line editing
```

**Comment by polygamma** [comment]
That seems sensible, thanks! Going to change that

**Comment by polygamma** [comment]
done. see: https://github.com/polygamma/aurman/commit/49d776542744c3e09345df92f9c9b5fad7f37d7d
