### ISSUE TITLE
Check for updates and list them

### ISSUE THREAD

**Issue by Brottweiler** [polygamma/aurman#83]
This isn't a feature request or a bug report really, but I found no other place to ask.

## Description
Cannot find a way to only list aur updates without installing them, similar to `cower -u`.

## Expected Behavior
I should be able to get a list of what packages has updates, like `checkupdates` does for non-aur packages.

## Current Behavior
There is either no way of showing updates, unless like [RaphaelRochet/arch-update/wiki](https://github.com/RaphaelRochet/arch-update/wiki) suggests using `aurman -Qqu` but it just shows empty.

## Possible Solution
A way to show updates, like `aurman -u`

## Steps to Reproduce
If this feature doesn't exist, there's no way to reproduce, unless there is a way and it isn't working like I think it does. Running `aurman -Qqu` shows nothing.

**Comment by Brottweiler** [comment]
Thanks, I see how it works, but I am not sure if I can use it the same way as `cower -u` since that simply just list what packages has updates on one line for each package. I am trying to use aurman as an alternative to cower because cower is bad https://lists.archlinux.org/pipermail/aur-dev/2018-January/004416.html

**Comment by polygamma** [comment]
You have to parse the output of `aurmansolver` in a way you want the output to be, I am not going to add additional output, since `aurmansolver` yields all needed information.

**Comment by Brottweiler** [comment]
Thanks!

**Comment by BurhanDanger** [comment]
Sorry I'm not sure how can I achieve that (cower -u like output) . Any help?

**Comment by polygamma** [comment]
You need to write e. g. a bash script or a python script for parsing. aurmansolver is meant for developers

**Comment by BurhanDanger** [comment]
Ok. This explains. Thanks for letting us use you helper. It's really good.
