### ISSUE TITLE
aurman does not respect "--color never "

### ISSUE THREAD

**Issue by nolifeorname** [polygamma/aurman#84]
## Description
When you execute aurman with the flag --color never, it will only disable colors in the pacman bit, the moment it prints "initialising aurman..." colors are enabled again

## Expected Behavior
when you use the flag "--color never" there should never be color in aurman

## Current Behavior
the flag is respected for the pacman part of the program, but not for the actual aurman part

## Steps to Reproduce
execute aurman with flag "--color never"
(for example: "aurman --color never -Syu")

**Comment by polygamma** [comment]
Sorry, color is only passed to pacman, aurman will always be in color, I have no intention to change that.
