### ISSUE TITLE
Unnecessary error when install is aborted

### ISSUE THREAD

**Issue by dschrempf** [polygamma/aurman#86]
## Description
When install of a package is aborted, aurman reports an error.

## Expected Behavior
Aurman should be quiet :).

## Current Behavior
E.g., when installing `ghc-static` and aborting the install, the following error is reported:

    2018-05-07 15:31:34,981 - wrappers - pacman - ERROR - pacman query sudo pacman --sync ghc-static --asdeps failed

## Possible Solution
Do not output anything.

## Steps to Reproduce

Aurman version :: 2.9.25-1

1. `aurman -S ghc-static`
2. When asked: Do you want to continue, type y and enter.
3. When asked: Proceed with installation, type n and enter.
4. The error is reported.

Complete log:

    [Mon May 07 15:31:11 dominik@schwarzbaer: ~]$ aurman -S ghc-static
    ~~ initializing aurman...
    ~~ calculating solutions...

    :: The following 1 package(s) are getting installed:
       community/ghc-static  /  ->  8.2.2-1

    ?? Do you want to continue? Y/n: y
    ~~ looking for new pkgbuilds and fetch them...
    [sudo] password for dominik: 
    resolving dependencies...
    looking for conflicting packages...

    Packages (1) ghc-static-8.2.2-1

    Total Download Size:     86.03 MiB
    Total Installed Size:  1080.80 MiB

    :: Proceed with installation? [Y/n] n
    2018-05-07 15:31:34,981 - wrappers - pacman - ERROR - pacman query sudo pacman --sync ghc-static --asdeps failed

**Comment by polygamma** [comment]
`pacman` returns `1` in that case, which is not distinguishable from "serious errors", hence `aurman` prints the error message. I do not want to loose the query in case of "serious errors"

**Comment by dschrempf** [comment]
Oh, i didn't know that. Does it make sense to ask for a separation of exit values upstream? Otherwise I just close this issue.

Thanks, Dominik

**Comment by polygamma** [comment]
I am not sure, if that makes sense, honestly. I guess people like @AladW could say more about the issue?

**Comment by AladW** [comment]
It was done for `makepkg` which has now 16 different exit codes to fail (see https://git.archlinux.org/pacman.git/commit/?id=ab2be5794de8a57426ec3fc0f631cc766a0b8227). Until then the only alternative is parse stdout/stderr which is not sensible since pacman output is localized.

**Comment by polygamma** [comment]
Thank you very much @AladW - I won't change the current aurman behavior then
