### ISSUE TITLE
Add Polkit support (pkexec instead of sudo)

### ISSUE THREAD

**Issue by Scrumplex** [polygamma/aurman#87]
As sudo is not necessarily installed on all systems, aurman should add support for `pkexec` from polkit.
`pkexec` may be used then in favor of `sudo` when trying to install.

**Comment by frealgagu** [comment]
but using pkexec you need to provide the password in a GUI, is there any way to use pkexec in the console  even if I'm using it in a graphic environment?

**Comment by Scrumplex** [comment]
As of https://wiki.archlinux.org/index.php/Polkit#Authentication_agents most desktop environments have own packages for polkit agents. If no additional polkit agent is installed, `pkexec` (and other polkit actions) fallback to interactive console authentication. I can't seem to find a parameter or environment variable to force the `pkttyagent` agent.

**Comment by polygamma** [comment]
sudo is part of base-devel, hence that's fine. i won't add support for anything else, sorry

**Comment by Scrumplex** [comment]
That's a pretty good reason not to. Agreed
