### ISSUE TITLE
Installing RuneLite package incorrectly fails SHA512sum validation

### ISSUE THREAD

**Issue by ThaChillera** [polygamma/aurman#89]
THIS TEMPLATE IS FOR BUG REPORTS,
YOU DO NOT HAVE TO USE IT FOR FEATURE REQUESTS

## Description
When trying to install the RuneLite package from the AUR, it fails when validating RuneLite.jar with sha512sum. When manually comparing the sha512sum to the sum in the PKGBUILD, it passes with no problems.

I am not entirely sure where the issue lies exactly, but my guess is with aurman since the hash in the PKGBUILD is correct.

## Expected Behavior
It should succeed installation.

## Current Behavior
_Tell what happens instead of the expected behavior_
It fails the installation.

## Possible Solution
_Not obligatory, but suggest a fix/reason for the bug_
No idea, which is why I'm here :)

## Steps to Reproduce
_Provide an unambiguous set of steps to reproduce this bug._

1. run 'aurman -S runelite', it fails
2. download Runelite.jar from https://github.com/runelite/launcher/releases/download/1.5.1/RuneLite.jar
3. run 'echo "0f27d33ac67c181b357b65b31020f4f7b7509aa2b45235e283b53f2267e8fe0222e129a8d9fe15c6d88eafc5347c897671608691f764b87c608b7e14c2bd3e5a RuneLite.jar" | sha512sum -c'

the above sha512sum is extracted from the RuneLite PKGBUILD, found at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=runelite

> **Notice**: If you do not fill out one of the fields, without mentioning **why** you left it out, the issue will be closed without any comment.

**Comment by polygamma** [comment]
the command does not fail on my pc. may you try it again, after deleting the runelite folder in the aurman cache folder? default is `~/.cache/aurman/runelite`

**Comment by ThaChillera** [comment]
This did solve the issue! My bad, I did install runelite on a different OS, with the same home folder, with aurman. thanks for the advice!
