### ISSUE TITLE
"Do you want to see the changes of {}?" Configurable Default

### ISSUE THREAD

**Issue by portaloffreedom** [polygamma/aurman#90]
At the question "Do you want to see the changes of {}?" I would love to see Yes as default instead of no. I already made the mistake of pressing Enter several times, and it becomes very hard to see the diff without doing a complicated git log and finding the folder.
Is it possible to change this default into the configuration file?

For now, I'll try to remember to change the code again every time there is an update.

What I propose would mean to change this line
https://github.com/polygamma/aurman/blob/efeec073fbb100db7c16f1627f4e108e08481aa2/src/aurman/classes.py#L955
From a hardcoded `False` to a value read from the configuration file.

**Comment by polygamma** [comment]
If you want to see the changes by default, just use `--show_changes`, does that fit your needs?

**Comment by portaloffreedom** [comment]
Not really, I would still want to choose on a per package base when updating. And typing every time `--show_changes` is not very user-friendly for me.
The only possible solution that I can see is to create an alias `aurman='aurman --show_changes'` but I don't really like it.

Also just came to my mind: I like the question even if I always chose "yes" because I can read all the text before in case of a diff flooding my terminal.

I'm open to creating a PR myself in case you are willing to add this.

**Comment by polygamma** [comment]
I see your point, going to add a config option for that. No need for you to open a PR

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/6ccddf0a2e6a11d23b1d8ceac6321db387caed24

will fix a docker test and release a new version with the feature afterwards

**Comment by polygamma** [comment]
New version has been released, does the config option work as expected?

**Comment by portaloffreedom** [comment]
Yes! It works!

Thanks, man! Really appreciated it!

**Comment by polygamma** [comment]
You're welcome :)
