### ISSUE TITLE
AUR updates prompt (again) during post-build install

### ISSUE THREAD

**Issue by glen3b** [polygamma/aurman#91]
_Feature request to make batch updates friendlier._

## Description
Since prompting for AUR sanity checking is done entirely at the beginning of the update process (`Do you want to see the changes of ___?`), once those prompts are done, the install should be completed in batch afterwards; that is, the actual package install command passed to pacman should not further prompt for confirmation.

## Expected Behavior
Installation should occur in batch. No further blocking user prompts should be needed after the initial sequence of prompts.
The snippet below should not block waiting for user input where it does.

## Current Behavior
For instance, when updating "discord-canary" (relevant exerpt from command line output):
```
==> Creating package "discord-canary"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: discord-canary 0.0.49-1 (Sat May 12 11:42:07 PDT 2018)
==> Cleaning up...
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) discord-canary-0.0.49-1

Total Installed Size:  145.69 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] 
```
It blocks waiting for user input, even though I've already completed all confirmation prompts before the AUR updating began.

## Possible Solution
I don't know where this is in your code, but probably just pass a `--noconfirm` to the underlying pacman call for AUR package updates/installations. Not sure if this could cause issues in potentially dangerous edge cases but it would probably work here. Assuming no edge cases we're worried about, should be a fairly straightforward fix.

## Steps to Reproduce

1. `aurman -Syu` (and wait for repository phase to finish)
2. Answer all prompts at the beginning of the AUR update process
3. Wait for one package build to complete, and then wait for it to prompt for installation

**Comment by polygamma** [comment]
nope, not possible, --noconfirm is not behaving well in case of e. g. conflicts

**Comment by glen3b** [comment]
Doesn't aurman do dependency resolution itself anyway? So if there is e.g. a conflict it will be presented to the user, who will confirm their desired behavior, earlier (i.e. before pacman is called)?

**Comment by glen3b** [comment]
This is potentially a dupe of/related to #73

**Comment by polygamma** [comment]
you cannot pass the desired behavior for e.g. conflicts to pacman without hacky stuff. normal --noconfirm defaults to "no"

**Comment by AladW** [comment]
You could use `pacinstall --remove` - no hacks involved and explicitly created for scenarios such as this. `aurman` should already have all required information available.

Note: requires `pacutils` (which is in the repos anyway)

**Comment by AladW** [comment]
Yes, that forum post is up-to-date. The flag however is not documented as it is only used in the `pacman` test suite, apart from this commit: https://git.archlinux.org/pacman.git/commit/?id=90e3e026d1236ad89c142b427d7eeb842bbb7ff4

I mentioned `pacinstall` because it's a tool with this use case in mind, rather than abusing an undocumented flag that could be removed at any time anyway. See also https://github.com/andrewgregory/pacutils/issues/15#issuecomment-260215224

**Comment by polygamma** [comment]
i did not choose to use `pacinstall`, since i do not want to use another tool as pacman wrapper. i fiddled around with `--ask` and it actually does exactly what i want, hence that's fine. if `--ask` actually gets deleted, it's easy to revert in the aurman sourcecode. see: https://github.com/polygamma/aurman/commit/9f4cf1388e558f50e8ed435ad2487147bcb088be

**Comment by AladW** [comment]
If it's part of a release probably. 

Note there's some ongoing discussion on the difference between "compute all dependencies yourself and feed what you found to pacman with --ask during the build process" or "find out on all conflicts and prompt the user, save the answers and feed them to pacman during the build process".

https://wiki.archlinux.org/index.php/Talk:AUR_helpers#pikaur.27s_interactive_control_flow

**Comment by polygamma** [comment]
It is part of the 2.9.27 release.

I am however not quite sure what you mean by 

> "compute all dependencies yourself and feed what you found to pacman with --ask during the build process" or "find out on all conflicts and prompt the user, save the answers and feed them to pacman during the build process"

`aurman` does both? `makepkg -s` is not used, all conflicts are also shown to the user before any building starts.

**Comment by polygamma** [comment]
see:

![screenshot from 2018-05-21 21-41-25](https://user-images.githubusercontent.com/20651500/40326508-c5ef5532-5d3f-11e8-8f0c-e1b9ef8b1d0d.png)

**Comment by AladW** [comment]
Yes, I'm trying to figure out myself what the supposed pain point is. In my view having all remove/installed packages in a single view to which the user can agree to or not with Y/N is much better than getting 20 prompts on whether a package should be replaced or not.

I'm hoping @actionless will clarify this a bit in his github wiki or README.

**Comment by AladW** [comment]
PS Feel free to update the wiki + link to commit.

**Comment by polygamma** [comment]
Thanks @AladW - closing this issue for now, since what @glen3b wanted is implemented

**Comment by actionless** [comment]
i just tried now `aurman -Syu <some_aur_pkg_name>` and instead of batch interaction which is claimed in arch wiki, i see what it first did pacman -Syu, and asked user to confirm repo packages, next it took some time to first download, next install the packages, run all hooks on them, and only after that it started one more prompt about aur packages, that doesn't looks like a batch interaction at all

**Comment by polygamma** [comment]
use `--do_everything` if you want 100% batch interaction, since `aurman` handles the `-Syu` in that case, too.

**Comment by actionless** [comment]
@polygamma not from you, i want more clear info in the arch wiki table

**Comment by AladW** [comment]
FWIW, I don't think `pacaur` had any of this fancy "let's break up `pacman -Syu` for fancy stuff" either and it was the originator of the term *batch interaction*.

**Comment by actionless** [comment]
could i then claim a separate feature in the right column "really batch interaction"?

**Comment by polygamma** [comment]
@actionless - are you being serious?

**Comment by AladW** [comment]
I'm not even sure what the argument is. If it is "aurman has more prompts" then I could equally claim aurutils has the "realliest batch interaction" since it has a single file manager window and nothing after that. If it is "pacman -Syu is left as is which causes some additional AUR prompts after it completes" I refer to comments above.

**Comment by actionless** [comment]
but you yourself claimed what batch interaction is not complete without additional flag and that's my whole point, what "not serious" do you see?

**Comment by actionless** [comment]
@AladW and you have a mention for that in the rightmost column, `vifm`

**Comment by AladW** [comment]
Things would really be much simpler if you started writing up a *detailed* wiki article in the `pikaur` project page that describes what you think other helpers are missing and `pikaur` does not.

**Comment by polygamma** [comment]
@actionless do you really want to split all columns into "is achieved with flag xy, not achieved with setting yz" etc.? this really is just stupid, some things are behind flags, others are not, users should be able to read a readme. sorry, you are behaving like a small child right now. you could also just create your own arch wiki with your own table only mentioning pikaur if that makes you happy

**Comment by actionless** [comment]
@AladW I did that 2-3 days ago, more detailed will be only mentioning expect but that will say nothing as a difference except for other people who working a lot with aur helpers/pacman

**Comment by actionless** [comment]
@polygamma "Partial" state in the table with a link to which flag to use to enable full batch interaction will be fine

**Comment by polygamma** [comment]
by your definition things are only partial if not enable by default? the fuck mate?

**Comment by AladW** [comment]
And for the record: I don't want any definitions in the wiki table (like `build and install`) that encourage questionable behavior like splitting up pacman -Syu.

**Comment by AladW** [comment]
And yes, whenever a column says "ability" it means you get a green entry even if something is not enabled by default (which it arguably is, but there it is)

**Comment by actionless** [comment]
@AladW you still haven't really explained why splitting `-Syu` to `-Sy` and `-Su` somehow more questionable than a user doing `-Syu`, hitting `N` and doing `-Syu` again

**Comment by AladW** [comment]
Oh god, not this again. Well, I'm out.

**Comment by actionless** [comment]
i wasn't the one who started it

**Comment by polygamma** [comment]
I am out, too. Have fun with whatever you are trying to achieve with your helper @actionless.

**Comment by actionless** [comment]
lol, you casted me yourself here and started bitching :smile_cat: :gun:

**Comment by polygamma** [comment]
relevant: https://github.com/polygamma/aurman/commit/088c09f0b57633db65973b396fc482d0d590c030
