### ISSUE TITLE
can i Install from packages list?

### ISSUE THREAD

**Issue by yaboroda** [polygamma/aurman#92]
Not sure if it bug or missing feature, but i can't install packages with txt list.
with pacman it works like that:
(https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#List_of_installed_packages)
pacman -S - < pkglist.txt

but aurman give me error 
parse_args - parse_pacman_args - ERROR -  is too short

version of aurman 2.9.26-1

**Comment by polygamma** [comment]
not implemented and i dont see a need for that. u may simply use something like:

`aurman -S $(cat ~/test.txt | xargs)`

**Comment by polygamma** [comment]
done. see: https://github.com/polygamma/aurman/commit/1755866414f7c8ccf79dfc6a78a0b5151d1e9021

any questions left?

**Comment by yaboroda** [comment]
Nope, thanks!

**Comment by polygamma** [comment]
Great :)

**Comment by AladW** [comment]
I'm going to bikeshed and suggest the more elegant `xargs -a ~/test.txt aurman -S`...
