### ISSUE TITLE
-y without -u is not allowed

### ISSUE THREAD

**Issue by vinnom** [polygamma/aurman#93]
## Description
I tried to run "aurman -Syy" which I found out is not allowed to do

## Expected Behavior
when running "pacman -Syy" it just updates databases, so as a pacman wrapper I thought aurman would do the same. Sometimes I just want to sync database to install another package without needing to care about upgrading other packages

## Current Behavior
it just fails

## Possible Solution
at least sync up pacman sources (the ones that are set in /etc/pacman.conf). It would be nice if it sync AUR too, as yaourt 

## Steps to Reproduce
1. run aurman -Syy

**Comment by AladW** [comment]
Preventing you from doing stupid/unsupported things is one of the few places where a `pacman` wrapper actually makes sense.

**Comment by batGnat** [comment]
@polygamma That is all fine and good, but I use 'pacman -Sy; pacman -Qu' to see if any updates are available (actually I was using 'yaourt -Sya; yaourt -Qua'). 
I can not do 'aurman -Sy; pacman -Qu' because of this. It even says to use this method on the man page (under the Query -u section)

**Comment by AladW** [comment]
Apparently you haven't heard of `checkupdates`. It's part of `pacman-contrib` now.

**Comment by batGnat** [comment]
does it also check AUR?

**Comment by AladW** [comment]
Why would it? If you want some checkupdates for AUR you can already use `aurmansolver` as has been outlined several times before in other issues.

**Comment by polygamma** [comment]
@batGnat why do you even need aurman for running `pacman -Sy`?

**Comment by batGnat** [comment]
why would it? because aurman is supposed to be an AUR helper. If you want to stop parial upgrades, you could block it if a package is passed e.g. 'aurman -Sy package'

**Comment by polygamma** [comment]
`aurman -Sy` itself can lead to problems.

**Comment by XavierCLL** [comment]
@polygamma for example what happen with `aurman -Sys package` I expected that aurman first synchronize the database and after search the package, this is so useful, what is the problem with that?

**Comment by polygamma** [comment]
Have you read the responses in this issue?

**Comment by XavierCLL** [comment]
then, is required two steps for search `-Syu` and `-Ss`...

**Comment by polygamma** [comment]
fucking hell
