### ISSUE TITLE
Ignoring updates

### ISSUE THREAD

**Issue by nstetter** [polygamma/aurman#94]
I would like to request a feature:
An ignore list for packages I don't want to be updated.
Possibly with the same syntax that pacman has

**Comment by polygamma** [comment]
rtfm

**Comment by nstetter** [comment]
Edit: Just looked in the code and noticed this feature is already present by importing the ignore list from pacman. Sorry, can be closed

**Comment by polygamma** [comment]
just curious: why didn't you even try once if the feature exists before opening an issue on github?

**Comment by AladW** [comment]
I guess he did, just too late. :wink:
