### ISSUE TITLE
Feature request: call makepkg with -A for arm[x] architecture

### ISSUE THREAD

**Issue by moonman** [polygamma/aurman#96]
Hi,
Many packages in the AUR work just fine on the arm, armv6h, armv7h, aarch64 architectures, however because these architectures aren't always available in the arch array in PKGBUILD, makepkg fails.

It would be nice to have an option to bypass this so aurman could be useful with archlinuxarm as well.

Thank you

**Comment by polygamma** [comment]
Why dont u edit the pkgbuild? aurman lets you do that

**Comment by AladW** [comment]
I guess it gets annoying if you have to edit possibly hundreds of PKGBUILDs...

**Comment by polygamma** [comment]
@moonman - see: https://github.com/polygamma/aurman/commit/2f9565c06dbdb2d7dcf641de66a2cedef818f304

**Comment by moonman** [comment]
That's perfect! Thank you @polygamma

**Comment by polygamma** [comment]
the feature is part of the 2.9.27 release
