### ISSUE TITLE
While running with --deep-search: "...rerun aurman with the --deep_search flag"

### ISSUE THREAD

**Issue by HaleTom** [polygamma/aurman#97]
## Description
I run `aurman` with `--deep_search`:

```
$ aurman -Su --deep_search                                                                                                                                                  22.3s | 23 May 17:50
:: Starting full system upgrade...
 there is nothing to do

~~ initializing aurman...
~~ calculating solutions...

!! While searching for solutions the following errors occurred:
:: Conflicts between: freetype2-2.9.1-1, freetype2-cleartype-2.9.1-1
While trying to install freetype2, the needed dependency libass.so=9-64 has been removed.
Way to package freetype2-2.9.1-1: zoom-2.1.103753.0521-1 -> qt5-webengine-5.10.1-2 -> ffmpeg-1:4.0-2 -> libass-0.14.0-1 -> freetype2-2.9.1-1
Way to package freetype2-cleartype-2.9.1-1: freetype2-cleartype-2.9.1-1

!! we could not find a solution
!! if you think that there should be one, rerun aurman with the --deep_search flag
```

## Expected Behavior
1.  I'm not suggested to run with `--deep_search` if I'm already using it
2. A resolution is found

## Current Behavior
See above

## Possible Solution
Unknown

## Steps to Reproduce
Install "conflicting" packages listed in the first section and then run as illustrated.

**Comment by polygamma** [comment]
Sorry, the instruction with "rerun aurman with the --deep_search flag" is hardcoded, going to change that. regarding the conflicts: i guess you are looking for "--optimistic_versioning", the faq in the readme of aurman explains that. does this solve your issue?

**Comment by polygamma** [comment]
regarding the "rerun aurman with --deep_search": https://github.com/polygamma/aurman/commit/9173c5108a3f0e92c79dcb1240c60a2d26dc6f27

**Comment by polygamma** [comment]
addition: discussion regarding "--optimistic_versioning": https://github.com/polygamma/aurman/issues/67

**Comment by HaleTom** [comment]
Thanks for the fast response and fix!

`--optimistic_versioning` did the trick!

BTW, is there any reason you use `_` (underscore) in `--long_option` rather than the conventional `--long-option` ?

**Comment by polygamma** [comment]
You're welcome :) Regarding the underscore: https://github.com/polygamma/aurman/issues/56
